### ISSUE TITLE
Tab-completion of paths when they are arguments of verdi commands

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida_core#1011]
Verdi commands such as `verdi export` would really benefit from the possibility to tab-autocomplete any path that is given as argument, for example:

`verdi export create /home/MYNAME/MYFOLDER/MYEXPORTFILE.aiida`

Currently one cannot tab-complete the path `/home/MYNAME/MYFOLDER/EXIMPORTFILE.aiida`.

**Comment by sphuber** [comment]
With the migration of `verdi` to `click` in #1795 this behavior is now automatically implemented when the parameters of the commands use the correct types, i.e. `Path` in this case. Therefore closing this issue, if there are any other places where custom completion needs to be supported, a separate issue should be opened.
