### ISSUE TITLE
aiida.parsers entry point not parsed correctly?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1021]
## steps to reproduce
Check out the [aiida plugin template](https://github.com/aiidateam/aiida-plugin-template), follow the README to set up the codes and run `verdi run examples/submit.py`.

In particular, consider the following excerpt from the `setup.json`
```
        "aiida.parsers": [
            "template.product = aiida_plugin_template.parsers.multiply:MultiplyParser"
        ],
```

## expected behavior

`template.product` is a valid name for an entry point (makes clear that it is a parser coming from a plugin template).
The parser should be loaded correctly.

## actual behavior

Trying to load the parser fails with
```
  File "/Users/leopold/Applications/miniconda3/envs/aiida_zeopp/lib/python2.7/site-packages/aiida/orm/implementation/general/calculation/job/__init__.py", line 134, in _validate
    "parser.".format(self.get_parser_name())
aiida.common.exceptions.ValidationError: No valid class/implementation found for the parser 'network'. Set the parser to None if you do not need an automatic parser.
```

When digging into aiida to get a more useful error message (#1019), it turns out that the actual problem is:
```
  File "/Users/leopold/Applications/aiida_ltalirz/aiida/common/old_pluginloader.py", line 255, in load_plugin
    pluginmod = importlib.import_module(real_plugin_module)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_plugin/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named template
```
i.e.  it tries to find a "template" python module.

The problem goes away when replacing the entry point `template.product` by `product`.

**Comment by sphuber** [comment]
How exactly did you try to load the parser that gives you the `aiida.common.exceptions.ValidationError: No valid class/implementation found for the parser` error? I have tried to recreate the problem on the latest develop and for me it works.

**Comment by ltalirz** [comment]
@sphuber #1019 : it's because of the name of the entry point

**Comment by sphuber** [comment]
Yes after setting up a dummy `aiida_plugin_template` code the script runs and print:

    submitted calculation; calc=Calculation(uuid='65858282-622d-47ce-a7a8-b9b05ce960cb') # ID=10230

**Comment by ltalirz** [comment]
@sphuber Thanks for giving it a try! I'll check the problem on my system

**Comment by ltalirz** [comment]
This issue was caused by me commenting out the wrong lines in aiida-core in order to get closer to the actual source of the problem.
I'll update #1019 with the actual import error.
