### ISSUE TITLE
daemon error messages & stored path to aiida module

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1031]
For some reason, on my system (MacOS 10.13.2, aiida 0.10.1) the daemon does not want to start properly:

```
$ verdi daemon status
# Most recent daemon timestamp:0h:00m:29s ago
Daemon not running (cannot find the PID for it)

$ verdi daemon start
Clearing all locks ...
Starting AiiDA Daemon ...
Daemon started

$ verdi daemon status
# Most recent daemon timestamp:0h:00m:06s ago
## Found 1 process running:
   * aiida-daemon[aiida-daemon] BACKOFF    Exited too quickly (process log may have details)

$ verdi daemon status
# Most recent daemon timestamp:0h:00m:06s ago
## Found 1 process running:
   * aiida-daemon[aiida-daemon] FATAL      Exited too quickly (process log may have details)

$ ps -ef | grep aiida-daemon
  502  1249 98105   0 12:25PM ttys003    0:00.00 grep --color=auto aiida-daemon
```

How do I go on from here? E.g. where do I find the process log?

**Comment by ltalirz** [comment]
Ok, thanks to @yakutovicha for pointing out `verdi daemon logshow` 

This leads me to a few more questions:

1) Do you guys agree with replacing `Exited too quickly (process log may have details)` by `Exited too quickly (see "verdi daemon logshow")`?

2) The problem was that the hardcoded path to aiida  used by the daemon was no longer valid.
However, the daemon actually still accepted calculation submissions. Error messages from these submissions were pointing to python files that no longer exist, e.g.
```
+-> ERROR at 2018-01-08 12:13:14.185750+01:00
|   Submission of calc 285 failed, check also the log file! Traceback: Traceback (most recent call last):
|     File "/Users/leopold/Applications/aiida_core/aiida/daemon/execmanager.py", line 475, in submit_calc
|     File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/general/calculation/job/__init__.py", line 1439, in _presubmit
|     File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/general/node.py", line 613, in get_inputs_dict
|     File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/general/node.py", line 675, in get_inputs
|     File "/Users/leopold/Applications/aiida_core/aiida/orm/implementation/sqlalchemy/node.py", line 274, in _get_db_input_links
|     File "/Users/leopold/Applications/aiida_core/aiida/backends/sqlalchemy/models/node.py", line 171, in get_aiida_class
|   TypeError: __init__() takes exactly 2 arguments (1 given)
```
I think this should not be allowed to happen?

3) The fact the path to the aiida python module is hardcoded in the daemon was something I did not expect. Sasha also told me this also caused him some problems a few days ago.
Is this necessary? When I do ``verdi daemon start`` I would naively expect that the daemon would use the aiida installation in my python path at that time.

**Comment by ltalirz** [comment]
from my discussions with @sphuber I learned that the `.aiida/daemon/aiida_daemon.conf` is gone in `develop`, and with it perhaps also the hard-coded path to the aiida python module?
If these things are solved in `develop`, this issue can be closed.

**Comment by sphuber** [comment]
With the removal of supervisord (PR #790) the daemon is now managed by celery and no longer uses a configuration file or a hardcoded path. There was an issue with the daemon as a result of incorrect logging but PR #1030 should have fixed this. Therefore I am closing this.
