### ISSUE TITLE
Upgrade to new versions of paramiko that support ECDSA ssh keys in known_hosts

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1036]
Finally, recent versions of paramiko seem to support ECDSA keys.
With the current dependency `paramiko==2.1.2`, if I connect to a computer that has a 
`ecdsa-sha2-nistp256` in the known_hosts, I get
```
SSHException: Server u'SERVERNAME' not found in known_hosts
```
(I replaced the server name with `SERVERNAME`.

After upgrading paramiko to `paramiko-2.4.0`, I manage to connect.
Note that there is a newer version of six 1.11 so I will upgrade that too.

We can also remove/simplify the docs.
This also relates to the very old #94

**Comment by sphuber** [comment]
Fixed in PR #1037
