### ISSUE TITLE
Fix broken backwards compatibility of KpointsData introduced by Seekpath implementation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1046]
PR #1015 deprecated various methods of `KpointsData` and exposed a common interface that by default would select to use the `Seekpath` library. However, the change broke backwards compatibility of the `set_kpoints_path` method. Originally, for `cartesian=False` and certain formats of the kpoints path it was not required to have defined a cell, however, the deprecation interface now always raises when the cell is not set.

**Comment by giovannipizzi** [comment]
Fixed by #1047
