### ISSUE TITLE
Use profile as part of RabbitMQ queue/exchange names

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1061]
The goal is to have RabbitMQ queues and exchanges have a prefix base on the profile.  This requires:
1) A profile migration to put a per profile general UUID
2) This be retrieved and used in work/rmq.py and used when creating the communicator.

**Comment by giovannipizzi** [comment]
Also, as a bonus change, add `indent=2` when writing the `config.json`

**Comment by sphuber** [comment]
`indent=4` perhaps? :)

**Comment by sphuber** [comment]
Fixed in PR #1201
