### ISSUE TITLE
Create unified way of submitting all Processes (including JobCalculations)

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1063]
There is an ongoing discussion on how to do this but a likely approach will be:
1) Have an inputs dictionary as 'the way'
2) Provide a 'builder' or 'submitter' that gives a CLI friendly way to build up and validate inputs before submitting

It has been commented that a 'test submit' is very useful.

**Comment by sphuber** [comment]
Fixed in PR #1116
