### ISSUE TITLE
Put in Process class information into corresponding orm node

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1064]
Currently a Process that runs (Workchain, etc) does not have information about which Process ran it.  This means the provenance of where the code is that ran that Claculation is missing and should be added to the attributes.

Notes:
* The solution should take into account the existing attribute that JobCalculations use
* Entry points are a proposed solution
* Nicolas Mounet suggests putting in the enter code string

**Comment by nmounet** [comment]
I would also store, in the repository, the full source code, if it's possible.
They are many cases when one needs to check what actually happened during some old Processes for which the code might have changed in between.
The best would be to have versioning, but in the meanwhile, I don't think it harms to store in a file the source code.

**Comment by muhrin** [comment]
Discussed with @sphuber and our ideas so far are to:
1) Leave the old type system as it is (maybe figure out a solution for `Base` types to make them consistent)
2) add a new process type string based on the entrypoint to indicate which Process class generated that node with fallback to module path
3) (optionally) make sure a new Process class can be loaded from this type string directly (to e.g., recreate the process as it was ran)

**Comment by sphuber** [comment]
After another discussion with @lekah we came up with the following proposed solution. The current database model uses the column `type` to store the type string of the `Node`. This is essentially the module path of the ORM class that should be used to load the record. Potentially we rename this to `orm_type` and then we will add a second column that will store, where applicable the `process_type`.
The `process_type` would currently only be applicable to the `JobCalculation` and `WorkCalculation` ORM classes and their value would correspond to a combination of their entry point and entry point category. For example

orm_type        |  process_type
------------------|---------------------------
code.Code.                               | 
data.int.Int.                               |
calculation.inline.InlineCalculation. | 
calculation.function.FunctionCalculation. | 
calculation.job.JobCalculation. | aiida.calculations.quantumespresso.pw
calculation.job.JobCalculation. | aiida.calculations.simpleplugins.templatereplacer
calculation.work.WorkCalculation. | aiida.workflows.quantumespresso.pw.base

The `orm_type` value will be used to determine the right class to load the database entry, whereas the `process_type`, in the case of a `JobCalculation` and `WorkCalculation`, can be used to create a new instance of the `Process` that ran it. In the case of the `WorkCalculation` this would be the corresponding `WorkChain` class, whereas for the `JobCalculation` it will be the corresponding subclass of `JobCalculation`, with `aiida.calculations.quantumespresso.pw` it being `PwCalculation`.

This setup would still allow the current way of querying for certain orm classes and maintaining their hierarchy. Appending `Calculation` to a `QueryBuilder` can still use the `orm_type` to get all records that start with `calculation.`. For a `PwCalculation` we could determine that this corresponds to a `Process` essentially (even though for historical reasons it is not actually one), which could then be reversed into its corresponding `process_type` by obtaining the entry point from the class and then query for the `process_type` column

**Comment by muhrin** [comment]
Fixed by PR #1294
