### ISSUE TITLE
Put in error code for Process failure

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1065]
When a `Process` fails there is currently no information to inform the user why it failed.  There may be something in the event log but there is no canonical way to programmatically query the failure reason.

The proposal is to add an attribute to store the failure code and have a mechanism by which the user can look up a string that gives a human readable reason.

It remains to be decided if this should be done on the `Process` or `WorkChain` level.

**Comment by muhrin** [comment]
It's not clear if the current state information (process_state) is enough to do this already.  Further investigation needed.

**Comment by DropD** [comment]
It seems that for `WorkChain`s the terminal `Process` state `finished`, additional information in form of an error code is required for the case when no exception is raised (which would lead to `failed` state), but the outcome is not the desired one (not converged, etc).

Care should also be taken that in all of the UI, the state `finished` is always presented with additional information associated to the error code (or lack thereof).

**Comment by DropD** [comment]
This mechanism is not required on the `JobCalculation` level, because the `JobCalculation`-state `PARSINGFAILED` already provides a way to indicate that the calculation finished but did not deliver the desired results.

**Comment by muhrin** [comment]
Ok, so:

1) Calculation nodes should have a new attribute `exit_state` (or something like that) with setter/getter.
2) `JobProcess` need to set this based on outcome of parsing, status update, etc
3) `WorkChain`s will provide an object to be returned during the step, e.g. `Abort` with a required exit status.
4) Verdi commands should list the exit status where there is one
5) Documentation should provide a suggested way of exposing the text giving the explanation of the exit status
6) Legacy nodes will not be updated to provide an exit status (no migration) which means that verdi and other commands should gracefully cope with its absence.

**Comment by sphuber** [comment]
Fixed in #1189
