### ISSUE TITLE
Unify process and (job) calculation states

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1075]
Now the Process (which runs everything - JobCalculations, Workchains and Workfunctions) has its own process_state attribute which is considered a 'super state' of the calculation state.

This information needs to be normalised throughput the system, including for legacy casaes where there was no process state.  Things to consider:

- verdi calculation list
- verdi work list
- verdi work status

**Comment by sphuber** [comment]
Fixed in PR #1197
