### ISSUE TITLE
slurm module: problem with parsing squeue output

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1079]
This comes from the Edison Cray XC30 machine at NERSC, they are running a rather recent version of slurm (17.11.2)

It seems there is a problem with parson the squeue output, I paste the output of `verdi computer test`
```
> Testing connection...
> Getting job list...
01/25/2018 05:56:42 PM, aiida.scheduler.slurm: [WARNING] Warning in _parse_joblist_output, non-empty stderr='SLURM_TIME_FORMAT=standard: Command not found.'
* The test raised an exception!
** Full traceback:
   Traceback (most recent call last):
     File "/Users/sudabehjawahery/Documents/aiida/aiida_core/aiida/cmdline/commands/computer.py", line 779, in computer_test
       dbauthinfo=dbauthinfo)
     File "/Users/sudabehjawahery/Documents/aiida/aiida_core/aiida/cmdline/commands/computer.py", line 830, in _computer_test_get_jobs
       found_jobs = scheduler.getJobs(as_dict=True)
     File "/Users/sudabehjawahery/Documents/aiida/aiida_core/aiida/scheduler/__init__.py", line 357, in getJobs
       joblist = self._parse_joblist_output(retval, stdout, stderr)
     File "/Users/sudabehjawahery/Documents/aiida/aiida_core/aiida/scheduler/plugins/slurm.py", line 494, in _parse_joblist_output
       "Error during squeue parsing (_parse_joblist_output function)")
   SchedulerError: Error during squeue parsing (_parse_joblist_output function)
> Creating a temporary file in the work directory...
  `-> Getting the remote user name...
      [remote username: sudi]
      [Checking/creating work directory: /scratch2/scratchdirs/sudi/aiida_run/]
  `-> Creating the file tmpHM2YGW...
  `-> Checking if the file has been created...
      [OK]
  `-> Retrieving the file and checking its content...
      [Retrieved]
      [Content OK]
  `-> Removing the file...
  [Deleted successfully]
Some tests failed! (1 out of 3 failed)
```

The error `SLURM_TIME_FORMAT=standard: Command not found.` seems to be the main one... any ideas?

**Comment by sphuber** [comment]
This came up in a recent post of a user on the [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/aiidausers/UHm635ds2l0/adoCg66lBAAJ). @giovannipizzi suggested that the default shell running on the remote was most likely not `bash` and so the `SLURM_TIME_FORMAT=standard` command which is prefixing the actual command is taken as the only command.

**Comment by sphuber** [comment]
I have never really looked into that part of aiida, so I am not sure to be honest.

**Comment by giovannipizzi** [comment]
Probably one could call all commands via bash, like with e.g. `bash -c 'actual command'`, but I think it just makes things much more complex, especially for what concerns escaping of spaces etc., that now need to be escaped one more time, and escaping might not work the same on all shells...

**Comment by ltalirz** [comment]
So, do I understand correctly that currently the only solution is to ask the hpc administrator to change the default shell?
Should we perhaps think of making the shell a parameter of the hpc communication?
I don't know how much effort this would be (perhaps not so much?) but then the question also is how prominent `tcsh`  is amongst hpc systems.

**Comment by giovannipizzi** [comment]
Not obvious to do it on our side - from ssh it is not easy to just swap the shell, see e.g. https://serverfault.com/questions/162018/force-ssh-to-use-a-specific-shell

Of course one could run bash inside the current shell, but then the actual script needs to be properly escaped, that is quite tricky especially if we don't know what shell is running... If someone has a suggestion on how to do this cleanly, adding a parameter to switch shell will be very easy.

As a note, supercomputer centres should (but they don't always do) provide a way to change the shell directly as a user, without asking the admin.

**Comment by ltalirz** [comment]
> Not obvious to do it on our side 

What I meant was to actually take out shell-dependent code and plug in the correct code depending on the shell variable of the computer.
I guess in the end, there isn't that much difference for what we need (`setenv` vs `export`, etc.) but perhaps I'm wrong.

> As a note, supercomputer centres should (but they don't always do) provide a way to change the shell directly as a user, without asking the admin.

What about adding a test to the `verdi computer test` command that checks which shell is being used and, if it isn't bash,  returns a helpful message explaining how to switch to bash?

**Comment by giovannipizzi** [comment]
They are two very good points.

> What I meant was to actually take out shell-dependent code and plug in the correct code depending on the shell variable of the computer. I guess in the end, there isn't that much difference for what we need (setenv vs export, etc.) but perhaps I'm wrong.

We can think about this, even if there might be edge cases that we don't expect (and if we really want to do it, we should add tests - e.g. have a very similar docker image for ssh, but with tcsh or something else). Let's see how many users need it.

> What about adding a test to the verdi computer test command that checks which shell is being used and, if it isn't bash, returns a helpful message explaining how to switch to bash?

Very good idea! I don't think it should be too complex. You just need to execute a command to discover what is the shell, and add it as one of the tests. Note that `echo $SHELL` does not necessarily point to the current shell (e.g. try to run 'tcsh' from 'bash': it will remain to /bin/bash). [Here](https://unix.stackexchange.com/questions/43499/difference-between-echo-shell-and-which-bash) it mentions some options, even if e.g. using `/proc/$$/exe` is linux-specific and does not work on Mac for instance. Probably parsing `ps -p $$` or using `echo $0` is a bit more reliable (even if e.g. on my Mac I get `-bash` and not simply `bash`, and I don't know what happens if the user has an alias, e.g. uses /bin/sh that in reality is bash).

So maybe I would check known shells in a list, raise an error if it's tcsh for instance, but just print a warning if we're not sure.

Another option is to instead check for capabilities (e.g. running a command like `A=astring echo $A` and check if the output is `astring`).

**Comment by ltalirz** [comment]
PR #1502 should address this issue in the `v0.12.x` series - the issue still needs to be kept open until this is merged into `develop`, since it touches some functionality that has changed quite a bit.

For reference: PR #1502 should allow commands to be run on systems, where bash is not the default login shell. One then still needs to make sure that the schedulers are using bash as well.

For slurm and SGE, this should be achieved automatically by using the default shebang (`#!/bin/bash`) during `verdi computer setup`.
For torque, one might need to pass it as an extra parameter to the calculation like so:
`calc.set_custom_scheduler_commands(“#PBS -S /bin/bash”`) (to test)

**Comment by giovannipizzi** [comment]
@ltalirz could you check if this can is fixed in develop/can now be closed?

**Comment by giovannipizzi** [comment]
My understanding is that #1502 is merged in develop already, closing
