### ISSUE TITLE
Write (more) WorkChain stepper persistence tests

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1080]
Currently these are poorly tested, particularly the `save/load_instance_state` methods which are vital to daemon persistence.

**Comment by muhrin** [comment]
We skipped the (perhaps only) test of `load/save_instance_state`, this should be fixed.

**Comment by sphuber** [comment]
The majority of the `WorkChain` logical constructs have been migrated to `plumpy` and have been tested more rigorously there
