### ISSUE TITLE
Improve multi-user mode with correct security permissions

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#109]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Probably allow each daemon to run only on a selected number of users; maybe give each daemon an UUID, and register the daemon on a (DbSettings?) table at startup, and check it is the correct daemon upon execution.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/109

**Comment by giovannipizzi** [comment]
This could be achieved instead by having single-user instances, but effective sharing mechanisms.

**Comment by DropD** [comment]
As already mentioned we are moving away from multi user mode towards single user + sharing, therefore closing this.
