### ISSUE TITLE
Automated parser test discovery for installed plugins

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1091]
I implemented an addition to the `PwParser` of the `aiida-quantumespresso` and wanted to write some tests for this as well. I found a folder `parser_tests` in the `tests` folder of the plugin repository and subsequently found in the developers documentation that these used to live in `aiida-core` in the path `aiida.backends.tests.parser_tests` and the test class in `aiida.backends.tests.parsers` would know how to read the content of those directories and automatically run a standard test. Since the tests were moved to the `aiida-quantumespresso` package, the `verdi devel tests db.parsers` command now runs zero tests. I guess the functionality to discover parser tests through the plugin system has not yet been implemented? Is this the case? I remember that we released `v0.11.1` this month because it contained new functionality regarding the testing of plugins. Was this not included?

**Comment by ltalirz** [comment]
I think this is a question for @DropD

**Comment by sphuber** [comment]
Pinging @giovannipizzi I just checked into this issue again and realized that currently the `aiida.backends.tests.test_parsers` is never even being run, because it is (unintentionally) being shadowed by `aiida.backends.tests.parsers.test_parser`. Is this still being used by anyone? I am not even sure anymore how this was triggered and how one could extend it from a plugin. Was this ever possible? If not, maybe we can remove it as with the `pytest` approach and fixtures, I think we have a better alternative.
