### ISSUE TITLE
Improve import/export

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#110]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

* Make import and export more reliable.

Issues:

* If UPF are imported with different uuid but same MD5, there will be some problem (the new node will probably not be created, but then this poses problems for provenance)

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/110

**Comment by szoupanos** [comment]
Part of these comments will be considered when addressing issue #999
