### ISSUE TITLE
Get rid of leading underscore convention in non database storable Process inputs

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1101]
Originally the convention was that in order to mark `Process` inputs as non database storable, one had to use a name with a leading underscore. We now have a proper mixin,  `WithNonDb`, for the `InputPort` which adds the `non_db` attribute, which when set to `True` indicates that it is not to be stored as a `Node` in the database. Old default work process inputs such as `_label`, `_description` and `_options` will have to be updated by removing the leading underscore and just use the attribute

**Comment by muhrin** [comment]
Done in PR #1105.
