### ISSUE TITLE
Source code of inline calculations to be put in the repository

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida_core#1107]
The source code of an inline calc. can represent a large amount of data, and I don't think it makes sense to have it queryable. The function name is, instead, enough for queries.

So we should instead store the source code in the repository, rather than in the Attributes.

**Comment by sphuber** [comment]
The recent change effectuated in PR #1082 that removed the source file of `InlineCalculations` from the attributes, created a bug in the `TcodExporter`. For the functionality to create a standalone script based on the `InlineCalculation` it relies on the source file being available which is no longer the case. The proposed solution therefore is the following:

1) Remove the function source from the attributes (does not have to be queryable)
2) Add the function name to the attributes (only reasonable thing for querying)
3) Add the source file to the repository

The only potential problem that I could see is that I am not sure if it is easy to extract just the function source from the entire source file if you just have the function name. It should be possible but it might not be very easy/clean to do and if people often want to retrieve just the function source, we might want to store this separately in addition to the entire source file

**Comment by sphuber** [comment]
Fixed in PR #1196
