### ISSUE TITLE
Missing plugin and falling back to node type

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida_core#1110]
Issue:
If plugin is not available for the node to load (e.g. in verdi calculation show or load_node()) it falls back to the base Node type with below message:

##### INPUTS:
02/09/2018 12:57:57 PM, aiida: [ERROR] Unable to find plugin for type 'calculation.job.quantumespresso.pw.PwCalculation.' (node= 24945), will use base Node class

Proposed solution:
If node type is not available, fall back to its parent type. If parent node type is also not available, fall back to its parent and so on.. instead of directly using the base Node type.

**Comment by giovannipizzi** [comment]
I think it is safe to have the following fallback rule:
- Code->always available
- *Data->Data (probably not needed at this stage to do a cascading and fall to the parent, unless it's easy to do - probably it is more complex now with plugins etc)
- subclasses of JobCalculation->JobCalculation (no cascading)
- other Calculation classes should not have subclasses defined in plugins so can stay (WorkCalculation, JobCalculation, ...)
