### ISSUE TITLE
Docs workflows: workflow development best practices

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1130]
Document the best practices when designing and developing workflows. This should not just focus on how `WorkChains` can be best implemented, but also when to use a `WorkChain` or a `workfunction` and when to subworkflow.

A stub has already been created in the documentation source, search for the string `ISSUE#1130`

**Comment by greschd** [comment]
Doesn't this depend on the expose functionality as well?

**Comment by sphuber** [comment]
It would, but that is not the only thing that should go in the best-practices, although granted it is an important one.

**Comment by sphuber** [comment]
Fixed in PR #1459
