### ISSUE TITLE
Document that '.' cannot be used in output names

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1138]
The dot ``.`` is currently reserved for separating namespaces. Previously, it was possible to use it in workflow outputs, but not calculation outputs.

Two ways in which this could be fixed:
- Document clearly that ``.`` should not be used in output keys, and change the example in the documentation to not use them
- Change the namespace implementation so that there is a different separator, or the namespace can be set explicitly.

**Comment by greschd** [comment]
Actually, they _can_ technically be used in workflows, but it just automatically creates a namespace.

**Comment by sphuber** [comment]
Fixed in PR #1459
