### ISSUE TITLE
Docker or virtual machine for the general public

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#114]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Think of creating a docker image or a virtual machine (e.g. Amazon EC2 image) that people can download to test AiiDA (docker: http://www.docker.com).

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/114

**Comment by giovannipizzi** [comment]
This is now addressed in a different repository for AiiDA docker (it's under work). I close this.
