### ISSUE TITLE
Docs workflows: add section that documents breaking changes and how to upgrade

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1147]
The next release is expected to contain multiple backwards compatibility breaking changes and therefore these have to be clearly documented. This will also make it easier to refer to them in the release notes and point users to the right location.

This will be a checklist of changes that will have to be documented:

- [x] Global submit in `WorkChain` should be replaced with `self.submit`
- [x] The `_options` input for `JobCalculation` is now `options`
- [x] The import `aiida.work.run` has moved to `aiida.work.launch`
- [x] The future returned by `submit` no longer has the `pid` attribute but rather `pk`
- [x] The `get_inputs_template` class method has been replaced by `get_builder` #1146 
- [x] The import `aiida.work.workfunction` has been moved to `aiida.work.workfunctions`
- [x] The `input_group` has been deprecated for `PortNamespaces`  creatable by `input_namespace`
- [x] Document that attributes set in constructor of `WorkChain` won't be properly recreated when 
running over the daemon
- [x] The use of `.` (period) in output keys is not supported in `Process.out`, unless the output namespaces are explicitly created beforehand

**Comment by muhrin** [comment]
Fixed in PR #1460
