### ISSUE TITLE
builder.launch() doesn't work inside a workchain

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1149]
The reason for this is that ``builder.launch`` will not hook into the correct event loop. For this to work, it would need to have access to the executing workchain.

Suggested solution: Remove the ``launch`` method, and instead allow for ``run(builder)`` and ``submit(builder)``.  To make this easier to do from the command line, one could add ``run`` and / or ``submit`` to the automatically imported names in the verdi shell.

Pros:
- The ``ProcessBuilder`` is now purely for inputs, and there is no name clash with the ``launch`` method.
- There are no "two ways of doing things" for running / submitting calculations -- everything goes through the same methods.

Cons:
- The discoverability of the ``run`` and ``submit`` functions is a bit worse than having the ``launch`` method, since it cannot directly be tab-completed from the builder.
- In the ``submit`` / ``run`` method, we might have to do a switch on the type of input given.

**Comment by greschd** [comment]
To Do:
- [ ] Allow the run / submit free functions to take a builder.
- [ ] Allow the run / submit methods to take a builder.
- [ ] Add a ``submit_test`` method to the process, which can also take a builder.

**Comment by greschd** [comment]
WIP branch: https://github.com/greschd/aiida_core/tree/fix_builder_launch

**Comment by sphuber** [comment]
I am not sure if we really need the `submit_test` functionality. It only really makes sense for `JobCalculations`. Since it won't be a method of the `ProcessBuilder` itself, we would have to create a separate launch function for this. @giovannipizzi do you think this functionality is really important to have?

**Comment by greschd** [comment]
**Update**: The ``submit`` free-function is now broken again -- I added a test for this in #1419.

**Comment by sphuber** [comment]
Fixed in #1450
