### ISSUE TITLE
Remove 'enabled' column from computer (leave it only in DbAuthInfo)

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1154]
So that we reduce the number of columns that can change after storing in DbComputer. Anyway the logic is already in DbAuthInfo, one should just remove the column with a migration, making sure that if the computer was disabled, the information is moved to the DbAuthInfo table, and adapt the 'verdi node enable/disable' commands, so that if -u is not specified, instead of setting the disabled/enabled property in DbComputer, it still follows the logic used when -u is specified, but for the `get_automatic_user()` user.

**Comment by sphuber** [comment]
Since this requires a database migration, ideally we want to do this before the migration reset after v1.0.0 release
