### ISSUE TITLE
Submitting a WorkChain results in node instnace being sent over RMQ

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1157]
There is a problem on _task_finished which tries to send a node direrctly in an RMQ message.  This causes problems in SQLA because their model classes cannot be serialised.  The solution is to convert the node to it's PID (or perhaps better UUID) and then deserialise it (i.e. `load_node`) on the other side.

This can be seen in `test_launch_with_inputs` when running the SQLA tests.

Found by Giovanni, here: https://travis-ci.org/giovannipizzi/aiida_core/jobs/343728634#L1740

**Comment by sphuber** [comment]
Fixed in PR #1162
