### ISSUE TITLE
Autogrouping

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#116]
Originally reported by: **Andrea Cepellotti (Bitbucket: [acepellotti](https://bitbucket.org/acepellotti), GitHub: [cepellotti](https://github.com/cepellotti))**

----------------------------------------

Extend the AutoGroup class to make it accessible to the user also outside of verdi run.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/116

**Comment by sphuber** [comment]
The functionality is available to the user. The user can instantiate the `AutoGroup` class and set all the specific parameters that they desire and subsequently set the global variable in `aiida.orm.autogroup.current_group` to the created instance, and all subsequent `Node` instances that are stored in the same interpreter will be automatically added to the group. Therefore this issue can be closed.
