### ISSUE TITLE
Document transitive closure

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#117]
Originally reported by: **Andrea Cepellotti (Bitbucket: [acepellotti](https://bitbucket.org/acepellotti), GitHub: [cepellotti](https://github.com/cepellotti))**

----------------------------------------

Add a description in the docs

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/117

**Comment by giovannipizzi** [comment]
I put this with a QueryBuilder topic since anyway it's mainly related to how to query.

**Comment by giovannipizzi** [comment]
Transitive closure removed in 0.10.0, so this does not apply anymore
