### ISSUE TITLE
Bug in List  base data type

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida_core#1171]
It is not possible to store an empty list. To reproduce the error one needs to do the following: 

```
In [1]: from aiida.orm.data.base import List
In [2]: l = List()
In [3]: l.store()
```

The error message is the following:

> 
> /home/epfl/work/aiida_core/aiida/orm/data/__init__.pyc in _set_attr(self, key, value, **kwargs)
>     115         if self.is_stored:
>     116             raise ModificationNotAllowed(
> --> 117                 "Cannot change the attributes of a stored data node.")
>     118         super(Data, self)._set_attr(key, value, **kwargs)
>     119 
> 
> ModificationNotAllowed: Cannot change the attributes of a stored data node.

After that any attempt to access the stored empty list is followed by exactly the same error:
```
In [5]: print l
```

However, if an empty List is accessed at least one time before the storage  - everything works correctly

```
In [1]: from aiida.orm.data.base import List
In [2]: l = List()
In [3]: print l
[]
In [4]: l.store()
Out[4]: <List: []>
In [5]: print l
[]
```

**Comment by sphuber** [comment]
Fixed in #1203
