### ISSUE TITLE
Add support for WorkChain subclasses in the QueryBuilder

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1195]
Currently the `QueryBuilder` won't allow to `append` a `WorkChain` class or subclass. However, I think it would be very useful to be able to do this. I feel that adding this would not be too difficult as soon as we have a canonical way to map the `WorkCalculation` nodes stored in the database onto the specific `WorkChain` process class. This problem is being addressed in issue #1064

**Comment by giovannipizzi** [comment]
Ideally in 1.0 if possible within the timeline. We need anyway to to the same for `CalcJob` if load_node starts returning only CalcJob and not the specific plugin subclass

**Comment by sphuber** [comment]
Fixed in PR #2421
