### ISSUE TITLE
Add optional requirements to setup.py in categories

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#121]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

We need to add some Python libraries to requirements.txt, to make the ICSD importer work, at least:
MySQLdb
ASE

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/121

**Comment by giovannipizzi** [comment]
More generally, we should take all dependencies in optional_dependencies, and put them in extras_require in the setup.py (and then, remove the optional_requirements.txt file)

**Comment by DropD** [comment]
This has been done a while ago.
install_requires and extras_require are now in setup_requirements.py, there is a script to create a requirements.txt from it.
