### ISSUE TITLE
List nodes cannot be loaded

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1215]
In 'workflows' branch.

Steps to reproduce:

```
from aiida.orm.data.list import List

l = List()
l.extend([1, 2, 3])
l.store()

load_node(l.pk) # raises an error
```

It seems that invalid ``kwargs`` are passed in the ``super()`` call of the List ``__init__``.

**Comment by sphuber** [comment]
Fixed in #1216
