### ISSUE TITLE
Tie daemon uniquely to database/repository through profile UUID

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1218]
The new daemon allows each profile to run its own daemon, but currently there is no check that two or more daemons don't access the same resources (database and or repository), which might lead to all sorts of problems. We need to only allow a single daemon to run for a given db/repo, so we should couple the profile UUID that is running the daemon to the db and repo and lock it.

**Comment by muhrin** [comment]
Discussed this and the main way we can see this causing a problem is now logged in #2064
