### ISSUE TITLE
Consider replacing Django with SqlAlchemy as ORM

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#123]
Originally reported by: **Boris Kozinsky (Bitbucket: [bkoz37](https://bitbucket.org/bkoz37), GitHub: Unknown)**

----------------------------------------

4 Major Advantages:

- Very general query structure for joins and filters across multiple graph links
- Single-table inheritance support on query level - can directly cast data objects to correct type
- Support for jsonb in Posgres 9.4 provides ability to query within JSON attached as attribute to any node in DB. Very powerful for property lookups
- Unit of work architecture gives transaction support (sessions) that is also thread-safe

This would require supporting only Postgres, which is the best DB choice anyway.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/123

**Comment by giovannipizzi** [comment]
SQLAlchemy is now implemented as a second backend, and will be released as stable soon, so I close this.
