### ISSUE TITLE
The daemon circus ports are not guaranteed to be unique across aiida installations

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1235]
The new daemon that is daemonized by circus, needs three unique ports to be able to communicate with the circus daemon. Since each profile can have its own daemon, these ports need to be guaranteed to be unique across the different profiles. Currently, when a new profile needs to be created or an existing one has to be migrated to the new schema, to determine the first available port, the port generating function simply finds all the existing profiles, adds three from a fixed starting point `6000` (currently hard-coded) and return the next integer.

This method suffers from a couple of problems. It is very fragile. If at some point the starting point is changed or some profile changes its circus port, since the ports are not checked explicitly, an overlapping port may be generated.

Even worse, these ports have to be unique not just across the profiles of the aiida installation, but system wide. If a user runs multiple aiida installations, their configuration files will be separated, but the ports they use still need to be unique.

The most straightforward and perhaps first solution would be to have an aiida installation wide starting port number or range, that can be configured on setup time (with some default), and the profiles for that installation can then take ports from that range. It is then up to the user to make sure that the ports do not clash across aiida instances.

Note that this problem is not aiida specific as one may also be running circus daemons on the same system for completely different applications, so the same limitations apply

**Comment by greschd** [comment]
Do these ports really need to be static, or could they be generated e.g. when the daemon starts? The advantage would be that you can then actually _scan_ for free ports. To communicate to the submitting interpreter maybe the daemon could store somewhere which ports it is using _right now_, and the submitting script checks that before trying to connect to the daemon?

I'm not really sure if that would work though, since I don't have too much insight into how the daemon works now.

**Comment by sphuber** [comment]
The thing is that when the daemon is started a `circus` `arbiter` is created that has three endpoints, with three different ports. To be able to communicate with the daemon, one has to know these ports. So it is more that when the daemon is launched with a given set of ports, that are determined dynamically, these values need to be stored somewhere for the corresponding profile, such that when a given profile needs to interact with its daemon, it has the right ports. Not sure where we would persist this information. I think in the `config.json` would be the wrong place. There should be some file in the `daemon` folder most likely, profile specific, that contains them. However, then the question still remains on how to determine which ports are currently available. Currently I am not sure how to do this and maybe (although unlikely I would say) this is not even possible in a sure fire way.

**Comment by greschd** [comment]
I think you can let the OS pick an available port, see https://stackoverflow.com/questions/1365265/on-localhost-how-do-i-pick-a-free-port-number.

In principle if all processes follow this rule and don't hard-code the ports, then all should work fine. In practice however, I don't know...

**Comment by sphuber** [comment]
Fixed in #1279
