### ISSUE TITLE
Order of workflow steps, calculations or subworkflows

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#124]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

In workflows, steps / calculations / subworkflows are typically ordered by time (see e.g. in method get_steps from aiida.orm.workflow). This might be a problem with MySQL (for which the time quanta is the second), since objects might have the same creation / modification time and be ordered randomly.
 

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/124

**Comment by giovannipizzi** [comment]
We've dropped support for MySQL, so I close this.
