### ISSUE TITLE
Add automatically generated API doc

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1242]
While working on #1228 I noticed that basic classes like `Group` or `User` were not part of the [module guide](http://aiida-core.readthedocs.io/en/latest/module_guide/index.html#).

I suggest we use [sphinx-apidoc](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html) to produce an automatically generated & complete API documentation.
Probably, quite a few of the `docs/source/.../dev.rst` files can be removed (even though in some cases there may be some value in selecting subset of the actual documentation).

**Comment by ltalirz** [comment]
`build succeeded, 1162 warnings.`

**Comment by sphuber** [comment]
Didn't know that existed, but sounds like a great plan. Just tag me if you open PR or a branch and need help with fixing docstrings

**Comment by ltalirz** [comment]
I'll be working on this here: https://github.com/ltalirz/aiida_core/tree/issue_1242_sphinx-apidoc
Down to 80 issues now that actually need looking into.

If it's like usual, then most of these will be simple formatting problems.
I wonder whether there are any tools for helping with formatting the documentation according to sphinx's standards...

**Comment by ltalirz** [comment]
@sphuber I'm now down to 42 warnings
Many of those related to imports of things that either don't exist or don't want to be imported...
Happy for your assistance, when you find the time (you already have edit rights on my fork)

**Comment by sphuber** [comment]
Excellent, I will see if I can take a look soon, thanks

**Comment by sphuber** [comment]
I have had a look and fixed a bunch of errors. We are now down to 3, that I don't really now how to fix.
These are the warnings:

```
/home/seb/code/aiida/env/dev/aiida-core/docs/source/apidoc/aiida.backends.djsite.db.rst:43: WARNING: autodoc: failed to import module u'aiida.backends.djsite.db.tests'; the following exception was raised:
Traceback (most recent call last):
  File "/home/seb/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/seb/code/aiida/env/dev/aiida-core/aiida/backends/djsite/db/tests.py", line 34, in <module>
    raise InternalError("aiida_test_list is not set, but you are trying to run the tests...")
InternalError: aiida_test_list is not set, but you are trying to run the tests...
/home/seb/code/aiida/env/dev/aiida-core/docs/source/apidoc/aiida.backends.sqlalchemy.migrations.rst:17: WARNING: autodoc: failed to import module u'aiida.backends.sqlalchemy.migrations.env'; the following exception was raised:
Traceback (most recent call last):
  File "/home/seb/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/seb/code/aiida/env/dev/aiida-core/aiida/backends/sqlalchemy/migrations/env.py", line 13, in <module>
    from alembic.context import config
ImportError: cannot import name config
/home/seb/code/aiida/env/dev/aiida-core/docs/source/apidoc/aiida.restapi.common.rst:10: WARNING: autodoc: failed to import module u'aiida.restapi.common.caching'; the following exception was raised:
Traceback (most recent call last):
  File "/home/seb/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/seb/code/aiida/env/dev/aiida-core/aiida/restapi/common/caching.py", line 11, in <module>
    from aiida.restapi.api import app
ImportError: cannot import name app
```

The second and third are import errors. They come from the restapi and alembic (SqlAlchemy migrations). Maybe you know about the first and we can ask Spyros about the latter.

The first warning is due to an internal error that we raise related to testing in `aiida/backends/djsite/db/tests.py`. Looking at the code, I think this is an old file that is no longer used, after the test system was adapted to be able to run both backends. I think we could remove the file, but am not sure. Let's find out tomorrow

**Comment by ltalirz** [comment]
@sphuber Thanks a bunch, this is moving forward much faster than I expected!

The restapi error looks like a typo (should be `App`), but correcting the typo yields another error
```
 File "/Users/leopold/Applications/miniconda3/envs/aiida_nanoporous/lib/python2.7/site-packages/flask_cache/__init__.py", line 121, in __init__
    self.init_app(app, config)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_nanoporous/lib/python2.7/site-packages/flask_cache/__init__.py", line 134, in init_app
    base_config = app.config.copy()
AttributeError: type object 'App' has no attribute 'config'
```
@waychal `aiida/restapi/common/caching.py` was written by you, could you please fix this? I have given you write access to my fork as well. 
https://github.com/ltalirz/aiida_core/tree/issue_1242_sphinx-apidoc
I guess this code anyhow never gets called, so perhaps it should best be deleted(?)

**Comment by ltalirz** [comment]
This work continues in #1330

**Comment by ltalirz** [comment]
#1330 merged
