### ISSUE TITLE
growing size of kombu_message table

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida_core#1253]
I found my aiida database has grow quite a bit in size over time. Looking into the tables I found that the size of `kombu_message` is unusually large (4GB) while the second largest db_dbattribute is only 190MB in size. According to aiida's documentation this table is created and used by `celery`. I assume it is for storing messages but shouldn't the historical messages be cleaned up regularly? I found it has messages with time-stamp back to the creation of the database.  I wonder how to clean it manually and safely.

I am using 0.11.0 at the moment, updated from 0.10.0.

**Comment by sphuber** [comment]
Thanks for the report. Indeed the `kombu_message` table is being used by celery. I have to admit that I am not a hundred percent sure if older messages are required for it to work properly, but I will discuss it tomorrow with @giovannipizzi . If it is safe to delete at least part of it, we could give you a sql statement to delete messages older than a certain date. It is probably good to mention that soon a new daemon will be merged in to `develop` and subsequently releases, which no longer uses `celery` and so this table will no longer be necessary.

**Comment by giovannipizzi** [comment]
Yes, indeed, it is something that I had noticed as well some time ago.
I think that it is safe to stop the daemon and clear all rows of the table, I did it once and I didn't see any problem (@sphuber - good to maybe add the deletion of these tables in the migrations in the workflows branch as well?).

**Comment by sphuber** [comment]
Yes, that would be an important thing to remember. I will add an issue for it, so we won't forget.

**Comment by zhubonan** [comment]
Thanks for the replies. @sphuber  Could you please give me a SQL statement for deletion of the messages? I am taking nightly snapshot backups and noticed my db backup has grown considerably in  size.

**Comment by sphuber** [comment]
Sure. Just enter the `psql` shell as your `postgres` user and connect to the correct database. For example if your database is called `aiida_db`, enter `\c aiida_db`. Then you can first check how many rows there are currently:

    SELECT COUNT(*) FROM kombu_message;

then for example to see all the messages that are older than one day:

    SELECT COUNT(*) FROM kombu_message WHERE timestamp < (NOW() - INTERVAL '1 DAYS');

If you are happy to delete those execute:

    DELETE FROM kombu_message WHERE timestamp < (NOW() - INTERVAL '1 DAYS');

**Comment by zhubonan** [comment]
Thank you very much.
