### ISSUE TITLE
old psycopg2 version

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#1261]
I ran into [this issue](https://github.com/psycopg/psycopg2-wheels/issues/2) on Ubuntu 17.10. I believe the fix would be to update or better loosen the requirements on the psycopg2 version.

**Comment by sphuber** [comment]
@ltalirz has an open PR #1259 to update the version to `2.7.4`. Would that fix your issue?

**Comment by oschuett** [comment]
Yes, I think that will fix it.

**Comment by oschuett** [comment]
Ok, I'll close the issue. Thanks for the help!
