### ISSUE TITLE
Better name for "locality" of codes

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#127]
Originally reported by: **Andrea Cepellotti (Bitbucket: [acepellotti](https://bitbucket.org/acepellotti), GitHub: [cepellotti](https://github.com/cepellotti))**

----------------------------------------

Nobody has ever guessed the meaning of this label by its name alone. Any idea on a better name convention to distinguish a script from a compiled executable?

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/127

**Comment by nmounet** [comment]
To fix the ambiguity about "local" vs "remote", it would be enough to put a sentence explaining what is set there (in "verdi computer setup"), and maybe renaming it "pre-installed" (="remote", currently) and "uploaded" (="local", currently)

So in "verdi computer setup", one could say someting like:
Uploaded (default=False) (True to upload the code from your local machine to the remote computer)

**Comment by DropD** [comment]
This is already fixed in DropD/aiida-verdi (where the plugin-aware verdi is being developed).
I will leave this open for now, as it is not in develop yet.
However, it would be trivial to just change remote to "installed" and local to "upload" (i suggest upload over uploaded, because the former represents the code being uploaded each time better).

**Comment by szoupanos** [comment]
Maybe it can be fixed in develop before the final migration of the verdi commands to click.
We had some new users recently confused by this.

**Comment by ltalirz** [comment]
Below my conclusions after discussion with @szoupanos:

1. In principle, AiiDA should not be responsible for copying/installing codes on remote machines.
Even for a python script, it would not be too much to ask that a user manually copies it to a remote cluster (say, his home directory), makes sure it works and adds the path to a 'remote code'.
2. There is, however, one good reason for storing codes inside AiiDA: preserving provenance, when using scripts/software that is not clearly versioned (and that may not be uniquely identified by  label/description).

These two points are in conflict: How to ensure that a code stored inside AiiDA is being used, if AiiDA is not supposed to copy it to the remote computer? This has lead to the current implementation, where a 'local' code is copied over to the computer at every job submission.

I currently see no user friendly way of resolving this discrepancy.
However, the naming can be made more clear (see suggestions below).

# Suggestions
* Change `verdi code setup` user interface from
  ```
  => Label: aiida_plugin_template
  => Description: aiida template plugin
  => Local: True
  => Default input plugin: template.multiply
  => Folder with the code: /your/path/to/aiida_plugin_template
  => Relative path of the executable: code.py
  ```
  to 
  ```
  => Label: aiida_plugin_template
  => Description: aiida template plugin
  => Default input plugin: template.multiply
  => Copy code from local directory: True
  => Local directory with the code: /your/path/to/aiida_plugin_template
  => Relative path of executable inside directory: code.py
  ```
* rename `is_local` to `is_stored_locally`

**Comment by DropD** [comment]
Closing, because the naming has changed during migration to click
