### ISSUE TITLE
SSH connections inside docker inside travis sometimes fail

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1278]
This causes failing tests. The error appears randomly and typically restarting the travis run hides the problem. Probably it is not a problem in AiiDA itself, but it is quite annoying so I put a note here (also because when the run is restarted, the logs disappear). I mention a few people here so if you get the same problem, before restarting the daemon you can copy here the relevant message to help debugging): @sphuber @szoupanos @DropD @muhrin @ltalirz 

(Here I will attach a full log, in the future probably only the relevant error can be copied to avoid this issue to become too long).

In the future, when we identify closer what the problem is (currently a `SSHException: SSH session not active`) probably we can add some debug, i.e. printing at the end of the job, when it fails, also some logs from within the Docker image).

**Comment by giovannipizzi** [comment]
I cannot put the whole log in a comment (too long) so I attach it.
[log-failing-docker-travis.txt](https://github.com/aiidateam/aiida_core/files/1809989/log-failing-docker-travis.txt)

**Comment by sphuber** [comment]
Do you want more logs? I have another one, but since it does not contain any specific debug statements, I wonder if it is going to be of use.

**Comment by giovannipizzi** [comment]
You can put only the snippet with the actual error, and only if it's different from the one I report above, so at least we collect the possible errors that appear and in a few weeks after we have enough statistics we try to debug deeper. Maybe report anyway at least the error to know how often it happens

**Comment by sphuber** [comment]
My case had in addition to the familiar `SSH  session not active` another exception `Service connection dropped`:

```
03/14/2018 05:16:10 PM, aiida.execmanager: [ERROR] Submission of calc 107 failed, check also the log file! Traceback: Traceback (most recent call last):
  File "/home/travis/build/sphuber/aiida_core/aiida/daemon/execmanager.py", line 508, in submit_calc
    t.chdir(remote_working_directory)
  File "/home/travis/build/sphuber/aiida_core/aiida/transport/plugins/ssh.py", line 544, in chdir
    self.sftp.chdir(path)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/paramiko/sftp_client.py", line 626, in chdir
    if not stat.S_ISDIR(self.stat(path).st_mode):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/paramiko/sftp_client.py", line 460, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/paramiko/sftp_client.py", line 780, in _request
    return self._read_response(num)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/paramiko/sftp_client.py", line 812, in _read_response
    raise SSHException('Server connection dropped: {}'.format(e))
SSHException: Server connection dropped: 

03/14/2018 05:16:11 PM, aiida.execmanager: [ERROR] Submission of calc 110 failed, check also the log file! Traceback: Traceback (most recent call last):
  File "/home/travis/build/sphuber/aiida_core/aiida/daemon/execmanager.py", line 495, in submit_calc
    remote_user = t.whoami()
  File "/home/travis/build/sphuber/aiida_core/aiida/transport/transport.py", line 613, in whoami
    retval, username, stderr = self.exec_command_wait(command)
  File "/home/travis/build/sphuber/aiida_core/aiida/transport/plugins/ssh.py", line 1307, in exec_command_wait
    ssh_stdin, stdout, stderr, channel = self._exec_command_internal(command, combine_stderr, bufsize=bufsize)
  File "/home/travis/build/sphuber/aiida_core/aiida/transport/plugins/ssh.py", line 1271, in _exec_command_internal
    channel = self.sshclient.get_transport().open_session()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/paramiko/transport.py", line 767, in open_session
    timeout=timeout)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/paramiko/transport.py", line 854, in open_channel
    raise SSHException('SSH session not active')
SSHException: SSH session not active
```

**Comment by giovannipizzi** [comment]
I'm adding some additional debugging. When it crashes, I also do a `docker ps` and cat the content of `/var/log/syslog` inside the docker image.
Unfortunately the output is not too helpful:
```
ERROR! Some return values are different from the expected value
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                   NAMES
cd869f0c686c        torquessh           "/sbin/my_init"     6 minutes ago       Up 6 minutes        0.0.0.0:10022->22/tcp   torquesshmachine
Apr 26 15:24:48 cd869f0c686c syslog-ng[95]: syslog-ng starting up; version='3.5.6'
```
(the last line is, apparently, the only content of `syslog`.
The useful information here is the that docker image is running and didn't crash in the meantime, so the problem has to be inside it. Unfortunately the log does not show anything. If you have in mind some additional log files, let me know.

Another option is to drop completely the docker thing, and run on 'localhost' putting what is now into the docker image inside the travis container. Opinions?

**Comment by sphuber** [comment]
@giovannipizzi without wanting to jinx it; we have not seen this in a while correct?

**Comment by giovannipizzi** [comment]
No, indeed. Let's close.
