### ISSUE TITLE
set_extras() for a single node gets slower if the total number of queried structures is large (sqlalchemy backend)

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida_core#1289]
This already becomes noticeable if the number of queried structures (limit_number) is  > 10:
```
    qb = QueryBuilder()
    qb.append(CifData)
    qb.limit(limit_number)

    for m in qb.all():
        n = m[0]
        n.set_extras(some_dict)  # Time to execute this function gets larger if the limit_number increases
```

To reproduce the behaviour I attach 3 files in set_extras.tar.gz.

1) upload_cif.py - to upload 10000 identical cif files in aiida database
2) stcuture.cif - structure to upload
3) test_extras.py - shows the time needed to to run set_attrs 10 times.

Here is the output of test_extras.py ran on my computer: 

limit: 1  time: 0.207682847977
limit: 2  time: 0.296581029892
limit: 4  time: 0.594248056412
limit: 8  time: 1.23671007156
limit: 16  time: 1.63905119896
limit: 32  time: 1.69909787178
limit: 64  time: 1.76452803612
limit: 128  time: 1.94920706749
limit: 256  time: 2.31963801384
limit: 512  time: 3.12534379959
limit: 1024  time: 4.67655014992
limit: 2048  time: 7.62787103653
limit: 4096  time: 13.6172299385
limit: 8192  time: 25.796120882

[set_extras.tar.gz](https://github.com/aiidateam/aiida_core/files/1820590/set_extras.tar.gz)

**Comment by szoupanos** [comment]
Is it different to #1456 ? It looks the same issue to me. 
I will close it and if you think that it is not the same case, please @yakutovicha or @ltalirz re-open it.

**Comment by ltalirz** [comment]
It's identical, I didn't remember that Sasha had opened essentially the same issue before.
