### ISSUE TITLE
Sharing data between computers

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#129]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

I often find it useful to work on the data on multiple computers, even offline (e.g. on my laptop while traveling). 
We should devise an automated, efficient way to sync two different AiiDA instances (maybe limiting to a given group/query/...) that is easy to run (I'd say as easy as a 'git pull'). It may be an extension of the current import/export functionality, but it must be more straightforward to use.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/129

**Comment by szoupanos** [comment]
There have been several discussions & architecture documents on sharing that include the mentioned features. This issue is not needed any more and it will be closed
