### ISSUE TITLE
Copying and deepcopying not implemented for Node

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1298]
The normal way to `copy` or `deepcopy` an object in python is to call `copy` or `deepcopy` methods from the `copy` module, for example.

    import copy
    obj = SomeObject()
    shallow_copy = copy.copy(obj)
    deep_copy = copy.deepcopy(obj)

Under the hood, this will call the `__copy__` and `__deepcopy__` class methods of the object. However, for the `Node` class these are not implemented, yet there is a `copy` method that seems to do what should be done by `__copy__`. This means that creating a copy of a `Node` does not actually give you a copy at all.

**Comment by greschd** [comment]
Should this really create a copy of the node in the database, or only a copy of the Python object itself? For example, an open file also cannot be copied.
