### ISSUE TITLE
CP parser (and versioning)

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#130]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Fix the CP parser, as the order of columns in the .evp file changed in v.5.1.1… (actually in rev. 11158).
Add the svn revision to the parsed data, when available.
Good occasion to think to versioning of parsers.
Maybe think to a low-level command to:
* substitute a node with another one (check also if outgoing nodes exist, …)
* using the substitution above, a command to reparse a node if nobody is using the parsed nodes.
* make sure the above commands are not shown to the user.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/130

**Comment by giovannipizzi** [comment]
I'm using the plugin and it works, so I assume the bug has been fixed (I remember working on it)
