### ISSUE TITLE
Implement soft shutdown for the daemon's DaemonRunner

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1304]
Currently when calling `verdi daemon stop`, this is directly passed to the `circus` controller, with the `quit` command, which shuts down the `arbiter` immediately. This will kill the `run_daemon` process, which is running the `DaemonRunner`. Instead, it should by default send a signal to the `DaemonRunner` to stop itself. Only when we receive confirmation that the internal event loop has been stopped, should we call the `quit` command on the `circus` client to stop the `arbiter`.

**Comment by greschd** [comment]
Is that related to #1274?

**Comment by sphuber** [comment]
Yes, I think so. Currently there is no mechanism to tell the `DaemonRunner` to shutdown neatly. The `verdi daemon stop` and indirectly `verdi daemon restart` directly interact with the `circus` controller, which will depending on the command directly shut down the `arbiter`, which will simply kill the process of the `DaemonRunner`. Anything that it was running will then be lost. I will now be implementing a remote procedure call to stop the event loop of the `DaemonRunner` and only after receiving the okay do we send the `quit` command to the `circus` controller. Hopefully this should give the `DaemonRunner` the chance to persist all its tasks and reschedule any tasks in the queue.

**Comment by greschd** [comment]
As far as I understand so far, the `DaemonRunner` is supposed to capture Keyboard interrupt and sigint through its `tornado.io.IOLoop`. However, I think it should also wait until at least the `TransportTask`s are done.
There should be some concept of whether a task needs to be run before the loop can be shut down, or how they are persisted when the daemon is shut down.

**Comment by muhrin** [comment]
Fixed by #1311
