### ISSUE TITLE
CIF syntax errors produced by PyCifRW

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#132]
Originally reported by: **Andrius Merkys (Bitbucket: [merkys](https://bitbucket.org/merkys), GitHub: [merkys](https://github.com/merkys))**

----------------------------------------

PyCifRW (as of versions 3.6.2 and 4.1) contains a bug producing syntactically incorrect CIF files. MWE for 4.1 is attached:

```
#!python

import CifFile
c = CifFile.CifFile()
c.set_grammar("1.1")
c.NewBlock("new")
b = c["new"]
b['_tag'] = '[value]'
c.WriteOut()
```

Produced CIF file has a CIF value starting with opening square bracket ('['), what is a syntax error. Developer of the package promised to fix it in the next release, someone will have to track that and update the dependency/code.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/132

**Comment by nmounet** [comment]
The current version in the requirements for PyCifRw is 3.6.2.1. This still has the bug mentioned above.
4.2.1 does not have it, but a comment in 'setup_requirements' mentions that tests fail with version > 4.
I presume we have to check those failing tests.

**Comment by nmounet** [comment]
Moreover, PyCifRw 3.6.2.1 fails for this COD cif [https://www.dropbox.com/s/uyl0kjyfgiwnvun/7106415_longline132.cif?dl=0]

**Comment by szoupanos** [comment]
We have to check the version used, the tests that we have and finally close the issue.

**Comment by waychal** [comment]
We are still using the version 'PyCifRW==3.6.2.1'. Similar issue for CIF is being discussed in issue #901.

As discussed in issue #882, we are switching from pycifrw to pycodcif library.
So this issue is no longer needs to be fixed and I am closing it now.

**Comment by nmounet** [comment]
I wouldn't close this important issue. From #882 In understand that switching to `pycodcif` is not yet ready. In the meanwhile, this issue remains.
