### ISSUE TITLE
remove duplicate (de)serialization code

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1339]
While fixing issues in the documentation for producing the API docs, I noticed what seems like a duplicate function (quite a few lines):

https://github.com/aiidateam/aiida_core/blob/82b4562579661098cbd2ae285f8743c3d02bb10a/aiida/common/deserialization.py#L19
https://github.com/aiidateam/aiida_core/blob/82b4562579661098cbd2ae285f8743c3d02bb10a/aiida/backends/djsite/db/models.py#L308

Can one of these be eliminated?

**Comment by sphuber** [comment]
Fixed in #1340
