### ISSUE TITLE
Bundles don't get the right class loader

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1345]
Copied from a discussion in #1335.

- In ``AiiDAPersister.save_checkpoint``, ``aiida.work.class_loader.CLASS_LOADER`` is passed to ``Bundle``
- In ``Bundle``, ``utils.class_name`` is used to save the loader to the bundle
- When unbundling, ``utils.load_instance`` is used to get back the class loader

Now the problem is that ``aiida.work.class_loader.CLASS_LOADER`` is not a separate class, but just an instance of ``plumpy.class_loader.ClassLoader``. So the ``utils.class_name`` just returns that.

I think we could just use ``yaml.dump`` and ``yaml.load`` instead to save / load the class loader.

**Comment by greschd** [comment]
Ah sorry, didn't see that you self-assigned this. Anyway, if you want to do it via ``yaml`` there's a PR in plumpy.

**Comment by sphuber** [comment]
Fixed in PR #1449
