### ISSUE TITLE
Local code setup crashes if paths in code folder have non-ASCII symbols or are broken symlinks

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#136]
Originally reported by: **Andrius Merkys (Bitbucket: [merkys](https://bitbucket.org/merkys), GitHub: [merkys](https://github.com/merkys))**

----------------------------------------

Setting up a new local code with `verdi code setup` crashes if any file in code folder, specified during setup as `Folder with the code:`:

* contain non-ASCII symbols (i.e. Carbó-bibliography.txt)
* are broken symbolic links

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/136

**Comment by giovannipizzi** [comment]
As stated above, this was fixed but the issue not closed
