### ISSUE TITLE
Cached calculation processes end up in excepted state

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1364]
While the calculation itself is ``FINISHED``, the associated process ends up being excepted.

**Comment by sphuber** [comment]
Does it have an actual exception message in the log?

**Comment by greschd** [comment]
Maybe we should add a test in the ``test_daemon.py`` which checks the process state, not only the state of the calculations.

**Comment by sphuber** [comment]
It actually does check the process state, but only if it is terminated, which includes `excepted`. After that is finished we should simply verify that they were all `finished` with `finish_status` equal to `0`.

**Comment by sphuber** [comment]
[In this branch](https://github.com/sphuber/aiida_core/tree/fix_1364_cached_calculations_excepted_state) I have added checks at the end of the `test_daemon.py` on Travis, to verify that all processes are `is_finished_ok`. This should in principle then fail the tests if the cached calculations end up in the excepted state. What I don't understand yet is why the caching in the tests seems to be working but were failing for you locally. Do you have MWE for the exception you mentioned?

**Comment by sphuber** [comment]
Fixed in #1407
