### ISSUE TITLE
SQLA attributes not current when read

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1372]
If you create a and save `Node` in one interpreter instance, set some attributes (either column or db_attributes) in a different interpreter instance and then try to read them in the original the updated value is given back.  This is because we use a session that is not committed, rolled-back or refreshed when reading the value and thus the 'session cached' value is given back.  

This is not the expected behaviour.

Using `session.refresh(db_node)` fixes the issue and this needs to be before all reads to SQLA model attributes.

**Comment by sphuber** [comment]
Fixed in #1379
