### ISSUE TITLE
Make Node.copy() call optional_inline-decorated internal function

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#138]
Originally reported by: **Andrius Merkys (Bitbucket: [merkys](https://bitbucket.org/merkys), GitHub: [merkys](https://github.com/merkys))**

----------------------------------------

``Node.copy()`` could call internal function ``_copy_inline()``, which would be decorated with ``@optional_inline``. Thus, by invoking ``copy(store=True)`` one would be able to record the provenance of copying the node. Drawback: after copying the node with ``copy(store=True)`` one would not be able to modify it.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/138

**Comment by giovannipizzi** [comment]
inline_calculations are superseded by WorkFunctions, I close this
