### ISSUE TITLE
ph parser

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#139]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

The ph parser should parse the xml file (from its pw parent) to get such info as the cell, etc.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/139

**Comment by giovannipizzi** [comment]
Won't fix this for now - anyway the ph parser should/will be moved to a different branch
