### ISSUE TITLE
Allow passing a JobCalculation to the launch free functions

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1392]
Since the launch free functions (`run`, `submit` and companions) expect a `Process` class as the first argument, if one wants to launch a `JobCalculation` one has to call `JobCalculation.process()` to generate the `JobProcess` class. However, this could just as well be done by the launch function by checking the class of the first argument and this would make it a lot easier for the user

**Comment by muhrin** [comment]
Fixed by #1404
