### ISSUE TITLE
kpoints class - triclinic case

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#140]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

The  _find_bravais_info method in the array.kpoints class is failing for several triclinic cases, in particular for the 3 following structures extracted from ICSD:

S8Tc4 (ICSD no 81816)
Re4S8 (ICSD no 75459)
CrS2 (ICSD no 75420)

Attached is an export of the three corresponding AiiDA structures.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/140

**Comment by sphuber** [comment]
This issue will be addressed in #1001

**Comment by giovannipizzi** [comment]
We will deprecate the interface and not fix it for the time being (see #1015).
The "legacy" version will be kept as it is useful in 2D; for 3D, seekpath is preferred.
