### ISSUE TITLE
Create parser tests for Quantum-ESPRESSO

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#142]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

Parser tests for QE have to be created/renewed, using the framework of the import_and_export branch.
There is one example in aiida_epfl/aiida/djsite/db/subtests/parser_tests, in the nwchem branch (in which import_and_export was merged).

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/142

**Comment by giovannipizzi** [comment]
We have parser tests now. They might need to be improved, but I close this for the time being
