### ISSUE TITLE
PYTHONPATH is set on calculations launched to localhost through the daemon

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1420]
This is a problem for calculations which execute a python script themselves, because they might load the wrong version of libraries.

The problem appears only when ``PYTHONPATH`` is also set on the submitting process. Since the daemon seems to do that, the problem manifests itself there.

I guess in general the solution should be to create a clean environment when submitting to the direct scheduler / localhost.

**Comment by greschd** [comment]
After some digging around, it seems there's no clean way to do this short of actually SSH-ing to localhost (which causes the whole login stuff to be executed). Maybe the best solution is to document somewhere that the direct scheduler inherits the environment it's called from, and let the user make sure that everything is correct with the prepend text.

@giovannipizzi, thoughts?

**Comment by muhrin** [comment]
@greschd Sorry I'm a bit thick but what's the problem with the PYTHONPATH being set in the subprocess environment?  Surely that will just mean that the child process is launched with the same environment as AiiDA itself which is what we want, no?

**Comment by greschd** [comment]
It's a combination of two things that make this a bit non-obvious:

- The environment we get is not that of the shell that launches the daemon, but it's modified in between. I don't know what modifies it (and it doesn't really matter) but that makes the issue hard to reproduce. It also doesn't appear with ``run`` or ``verdi devel run_daemon``.
- It's different than how remote computers work. There, you get a "fresh" environment because you log in via SSH.

Now the specific issue I had was where I wanted to launch a ``click`` application as a calculation, but in a different virtualenv. Because click doesn't need the venv to be loaded, I just gave the abspath to the script as code. However if the PYTHONPATH is set that just messes up completely because it tries loading the wrong (Py2) libraries. 

Anyway, apart from the specifics of this case it's hard to debug because simply using ``gotocomputer`` and then ``bash -e _aiidasubmit.sh`` doesn't give the same environment.

If we wanted to get the same environment as the process _launching_ AiiDA we could save the env to a file when launching the daemon, amd then pass that to the suprocess.. but that strikes me as quite ugly.

**Comment by greschd** [comment]
But yeah, I think it's not 100% clear what the right environment to load is.. as a user the prudent thing to do is just to set/unset everything that might influence your calculation.

**Comment by sphuber** [comment]
Fixed in PR #1437
