### ISSUE TITLE
verdi commands documentation

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#143]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

We should find a way to update dynamically (i.e. automatically from the code) the documentation for the 'verdi' commands.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/143

**Comment by DropD** [comment]
I assume you mean sphinx documentation. In that case, it could be something like running through all commands, grabbing the help page and pasting it into an rst template? (click provides an easy way to run commands programmatically)

**Comment by nmounet** [comment]
yes, that's what I meant

**Comment by DropD** [comment]
Maybe in the meantime it is worth writing a script that works for the existing `click`-implemented commands.
