### ISSUE TITLE
Limiting ressources (licenses)

### ISSUE THREAD

**Issue by n4562** [aiidateam/aiida_core#1431]
Hello,

Newbie here with aiida, love what I am seeing so far.
I have a specific use case, I have 2 remote hpc with their own scheduler. Because of license restriction, I am only allowed to run X simulations concurrently (i.e. across the 2 hpcs).
How would I handle this from a aiida point of view?

Thanks,

**Comment by giovannipizzi** [comment]
We have some plans to fix this (see #88). 
I'm closing this to keep the discussion in issue #88
