### ISSUE TITLE
how to add aiida daemon system service?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1434]
For our quantum mobile machine, we'd like to add the aiida daemon as a system service so that it is always running when a user starts the machine.

I'm not familiar with daemonization, so perhaps some of the folks working on this can give a few pointers.

Here is an example aiida-daemon.service file for systemd (that doesn't work, however - I guess this will be obvious for people who know how this is supposed to work)
```
[Unit]
Description=AiiDA daemon service
After=network.target


[Service]
ExecStart={{ aiida_venv }}/bin/verdi daemon start
ExecStop={{ aiida_venv }}/bin/verdi daemon stop
User={{ ansible_user }}
Group={{ ansible_user }}
Restart=always
RestartSec=60                       # Restart service 60 seconds if it crashes
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=aiida-daemon

[Install]
WantedBy=multi-user.target
```

**Comment by ltalirz** [comment]
I guess the problem is that the `verdi daemon start` command exits after the daemon has started, which leads `systemd` to believe that the service is down...

```
Apr 16 13:08:22 qmobile systemd[1]: Started AiiDA daemon service.
Apr 16 13:08:22 qmobile aiida-daemon[29158]: Clearing all locks ...
Apr 16 13:08:22 qmobile aiida-daemon[29158]: Starting AiiDA Daemon (log file: /home/max/.aiida/daemon/log/celery.log)...
Apr 16 13:08:22 qmobile aiida-daemon[29158]: Daemon started
Apr 16 13:08:22 qmobile aiida-daemon[29169]: Daemon not running (cannot find the PID for it)
Apr 16 13:08:22 qmobile aiida-daemon[29169]: AiiDA Daemon shut down correctly.
Apr 16 13:08:23 qmobile systemd[1]: aiida-daemon.service: Service hold-off time over, scheduling restart.
Apr 16 13:08:23 qmobile systemd[1]: Stopped AiiDA daemon service.
Apr 16 13:08:23 qmobile systemd[1]: Started AiiDA daemon service.
Apr 16 13:08:23 qmobile aiida-daemon[29174]: Clearing all locks ...
Apr 16 13:08:23 qmobile aiida-daemon[29174]: Starting AiiDA Daemon (log file: /home/max/.aiida/daemon/log/celery.log)...
Apr 16 13:08:23 qmobile aiida-daemon[29174]: Daemon started
Apr 16 13:08:23 qmobile aiida-daemon[29184]: Daemon not running (cannot find the PID for it)
Apr 16 13:08:23 qmobile aiida-daemon[29184]: AiiDA Daemon shut down correctly.
Apr 16 13:08:24 qmobile systemd[1]: aiida-daemon.service: Service hold-off time over, scheduling restart.
...
```

**Comment by ltalirz** [comment]
After reading the [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html) I've made some progress, but for some reason the daemon still doesn't want to start properly, when called from systemd: 
```
Apr 16 13:28:29 qmobile systemd[1]: Started AiiDA daemon service.
Apr 16 13:28:30 qmobile aiida-daemon[979]: Clearing all locks ...
Apr 16 13:28:30 qmobile aiida-daemon[979]: Starting AiiDA Daemon (log file: /home/max/.aiida/daemon/log/celery.log)...
Apr 16 13:28:30 qmobile aiida-daemon[979]: Daemon started
Apr 16 13:28:30 qmobile aiida-daemon[993]: Daemon not running (cannot find the PID for it)
Apr 16 13:28:30 qmobile aiida-daemon[993]: AiiDA Daemon shut down correctly.
```

The same works just fine, if I call it from the command line:
```
 max@qmobile:~/.aiida/daemon/log$ /home/max/.virtualenvs/aiida/bin/verdi daemon start
Clearing all locks ...
Starting AiiDA Daemon (log file: /home/max/.aiida/daemon/log/celery.log)...
Daemon started
```


here the updated .service file
```
[Unit]
Description=AiiDA daemon service
After=network.target

[Service]
type=forking
PIDFile={{ ansible_env.HOME }}/.aiida/daemon/log/celery.pid
ExecStart={{ aiida_venv }}/bin/verdi daemon start
ExecStop={{ aiida_venv }}/bin/verdi daemon stop
ExecReload={{ aiida_venv }}/bin/verdi daemon restart
User={{ ansible_user }}
Group={{ ansible_user }}
Restart=on-failure
RestartSec=60                       # Restart service after X seconds if crashes
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=aiida-daemon

[Install]
WantedBy=multi-user.target
```

**Comment by ltalirz** [comment]
In essence it was just a typo (`Type`).

Will add this to the docs now.
```
[Unit]
Description=AiiDA daemon service
After=network.target

[Service]
Type=forking
ExecStart={{ aiida_venv }}/bin/verdi daemon start
PIDFile={{ ansible_env.HOME }}/.aiida/daemon/log/celery.pid
# 2s delay to prevent read error on PID file
ExecStartPost=/bin/sleep 2

ExecStop={{ aiida_venv }}/bin/verdi daemon stop
ExecReload={{ aiida_venv }}/bin/verdi daemon restart

User={{ ansible_user }}
Group={{ ansible_user }}
Restart=on-failure
RestartSec=60       # Restart daemon after 1 min if crashes
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=aiida-daemon

[Install]
WantedBy=multi-user.target
```

**Comment by ltalirz** [comment]
@giovannipizzi asks about how to generalize this for a per-user service

There is such a thing as [user services](https://wiki.archlinux.org/index.php/Systemd/User).
It seems to me that the aiida daemon should probably better run as a user service (although this means it will be killed when the user logs out).

**Comment by giovannipizzi** [comment]
Are you sure it will be killed at logout? The note in "How it works" at your link says it's per-user and not per-session that makes me think the opposite, but I didn't test.
I think that if it is killed at user logout, it's not a good idea to use it (unless the user prefers so). Anyway your configuration runs as the correct user, so it should be ok. The only thing is to allow multiple users to configure their service, or actually even more importantly, a given user to run two or more daemons for different profiles (this is now possible in the new developments happening in the workflows branch)

**Comment by ltalirz** [comment]
> Are you sure it will be killed at logout? The note in "How it works" at your link says it's per-user and not per-session that makes me think the opposite

The second sentence in "How it works" literally reads: "This process will survive as long as there is some session for that user, and will be killed as soon as the last session for the user is closed."

> Anyway your configuration runs as the correct user, so it should be ok.

Well, it's still a system-wide service, meaning for example you can't run two identical ones on the same machine.
If there are multiple users on a server who want to use AiiDA, one might want to run things on a user-basis instead of having a system-wide service for everyone's daemons.
But I do also see the value of having the daemon running without the user being logged in... 
so for the moment let's not worry about the multi-user scenario. 

There is something called "[unit templates](https://www.freedesktop.org/software/systemd/man/systemd.unit.html)", which allow you to run a `aiida-daemon@myprofile.service` and should solve the issue of running one daemon per profile.

**Comment by giovannipizzi** [comment]
> meaning for example you can't run two identical ones on the same machine.
Yes exactly, but if you give two different names, you can have two services (e.g. aiida-user1-profile1 and aiida-user1-profile2)

Moreover, I think it is very useful to have AiiDA running when not logged in (I can log out and the daemon will still take care of my simulations). Imagine e.g. that AiiDA runs on a non-graphical server, where nobody is logged in but still you want AiiDA to check your calculations and submit new wf steps.

**Comment by giovannipizzi** [comment]
This is a script that works for the AiiDA 1.0.0 series (there are some variables to change, this is taken from a template of a ansible script):
```
[Unit]
Description=AiiDA daemon service
After=network.target

[Service]
Type=forking
ExecStart={{ aiida_venv }}/bin/verdi daemon start
PIDFile={{ ansible_env.HOME }}/.aiida/daemon/circus-default.pid
# 2s delay to prevent read error on PID file
ExecStartPost=/bin/sleep 2

ExecStop={{ aiida_venv }}/bin/verdi daemon stop
ExecReload={{ aiida_venv }}/bin/verdi daemon restart

User={{ ansible_user }}
Group={{ ansible_user }}
Restart=on-failure
RestartSec=60       # Restart daemon after 1 min if crashes
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=aiida-daemon

[Install]
WantedBy=multi-user.target
```
This needs just to be updated in the docs

**Comment by giovannipizzi** [comment]
Update this for 1.0

**Comment by giovannipizzi** [comment]
As soon as the beta is out, this can be fixed in the Quantum Mobile, and this issue closed. We have already prepared the correct script for the tutorial last May (and I think it is the code I pasted above).

**Comment by ltalirz** [comment]
Here and updated config for the aiida 0.12 series which fixes two issues
```
[Unit]
Description=AiiDA daemon service
After=network.target postgresql.service

[Service]
Type=forking
ExecStart={{ daemon_aiida_venv }}/bin/verdi daemon start
PIDFile={{ daemon_user_home }}/.aiida/daemon/log/celery.pid
# 2s delay to prevent read error on PID file
ExecStartPost=/bin/sleep 2

ExecStop={{ daemon_aiida_venv }}/bin/verdi daemon stop
ExecReload={{ daemon_aiida_venv }}/bin/verdi daemon restart

User={{ daemon_user }}
Group={{ daemon_user }}
Restart=on-failure
# Restart daemon after 1 min if crashes
RestartSec=60
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=aiida-daemon

[Install]
WantedBy=multi-user.target
```

**Comment by ltalirz** [comment]
And here comes the equivalent configuration for aiida 1.0

```
[Unit]
Description=AiiDA daemon service
After=network.target postgresql.service

[Service]
Type=forking
ExecStart={{ daemon_aiida_venv }}/bin/verdi daemon start
Sockets={{ daemon_user_home }}/.aiida/daemon/log/circus-{{ aiida_profile_name }}.sockets
# 2s delay to prevent read error on PID file
ExecStartPost=/bin/sleep 2

ExecStop={{ daemon_aiida_venv }}/bin/verdi daemon stop
ExecReload={{ daemon_aiida_venv }}/bin/verdi daemon restart

User={{ daemon_user }}
Group={{ daemon_user }}
Restart=on-failure
# Restart daemon after 1 min if crashes
RestartSec=60
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=aiida-daemon

[Install]
WantedBy=multi-user.target
```

All that remains to be done is to add links to the docs
