### ISSUE TITLE
Process inputs template: setting `_label` does not lead to calculation label being set.

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1435]
Reproduce (requires aiida-vasp):

```
vasp_process = DataFactory('vasp.vasp').process()
inputs = vasp_process.get_inputs_template()
inputs._label = 'This label'
## ... continue setting inputs
info = submit(vasp_process, **inputs)
calc = load_node(info.pid)
assert calc.label == 'This label'
```

Weirdly, setting `intputs['_label'] = 'That label'` seems to work.

**Comment by sphuber** [comment]
Are you doing this off of `workflows`? The old convention for non database storable inputs was to use the leading underscore, however, in the `workflows` branch we have implemented this properly and so we could get rid of the underscore. Just try `label` as an input
