### ISSUE TITLE
Add a "cookbook" to the docs

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#144]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

I.e., add a page with a collection of short scripts or code snippets for specific AiiDA-related tasks. See existing examples in our codes or past emails.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/144

**Comment by giovannipizzi** [comment]
The page exists now so I close
