### ISSUE TITLE
verdi data list -> support for multiuser

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#146]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

By default, the 'query' method in the Listable class assumes in the query that we are looking only to data from the default user. Have the possibility instead to list the data objects from all users, or for a specified user, from the command line (possibly with the same command line options of other commands that support multiusers).

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/146

**Comment by szoupanos** [comment]
There is the argument there in the command line but in any case, it uses the deprecated query method of Django. It should be converted to use QueryBuilder to be compatible with SQLA too.

**Comment by szoupanos** [comment]
This is very related to issue #901

**Comment by szoupanos** [comment]
Fixed by PR #1007
