### ISSUE TITLE
Icsd dbimporter

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#147]
Originally reported by: **Nicolas Mounet (Bitbucket: [mounet](https://bitbucket.org/mounet), GitHub: [nmounet](https://github.com/nmounet))**

----------------------------------------

Some query keywords do not work (e.g. spacegroup, element)

For instance,

importer.query(element='C')
would return only 100 entries, and

query_results=importer.query(spacegroup=166)
would not return anything.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/147

**Comment by nmounet** [comment]
The first issue mentioned above results from a misunderstanding of the output, which is chuncked by group of 100. Actually:
```
q = importer.query(element='C')
len(list(q))
```
returns the correct number of entries (more than 4000).

**Comment by DropD** [comment]
can you reproduce the second problem?

**Comment by nmounet** [comment]
There are real issues though:
- formula query fails with an error,
- empty query also fails with an error.

**Comment by giovannipizzi** [comment]
Fixed in #458
