### ISSUE TITLE
Document how to cleanup celery task list in the cookbook

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#149]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Check if the following still applies:

# The celery-taskmeta table grows over time because it stores
# the result of each completed task.
# To clean it up with postgresql, and reduce space:

in 'verdi shell':

from djcelery.models import TaskMeta, states
TaskMeta.objects.filter(status=states.SUCCESS).delete()

in 'psql -U postgres -W -h localhost':

SELECT pg_size_pretty(pg_database_size('aiidadb'));
\c aiidadb

VACUUM;
REINDEX TABLE celery_taskmeta;

SELECT pg_size_pretty(pg_database_size('aiidadb'));

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/149

**Comment by giovannipizzi** [comment]
@nmounet could you check the size of that table and see if this is still a problem? I think that there was an issue when DEBUG=True with django-celery, but now we are setting DEBUG=False and we don't use django-celery directly. If the table remains small, can you close this issue?

**Comment by nmounet** [comment]
Issue is fixed (celery_taskmeta table is now quite small)
