### ISSUE TITLE
Comparing values of ProcessBuilder with None is broken

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1495]
```
$> AddCalculation = CalculationFactory('simpleplugins.arithmetic.add')
$> builder = AddCalculation.get_builder() 
$> builder.x
None
$> builder.x is None
False
```

The comparison returns `False` even though the comparison is actually `True`

**Comment by broeder-j** [comment]
Also: The process builder initializes a lot of things with None, which have to be set, otherwise they will fail later in the evaluation: 
```
ValueError: invalid attribute value: expected int for dictionary value @ data['max_memory_kb'].
```
Maybe this is connected to this None issue (because before it did not matter), or the validation check should also allow for None values.
