### ISSUE TITLE
`verdi code update` now crashes

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1500]
As it should as nodes shouldn't be updatable.
I would replace this with `verdi code duplicate` that works the same, but at the end it saves a new code (and gives the option to hide the previous code if this is a replacement (and maybe leaves some comment in the extras that the node comes from another one?)

**Comment by ltalirz** [comment]
> I would replace this with verdi code duplicate that works the same, but at the end it saves a new code (and gives the option to hide the previous code if this is a replacement

I second this. 

One of the problems I'd like to solve is to be able to share configurations of machines like quantum mobile, which can have multiple clones.
Ideally, this would happen through aiida export files that simply contain the codes, but currently one would have to create separate export files for each clone.

If verdi code duplicate was available, one could reuse the same aiida export file and simply replace the computer for all codes.
