### ISSUE TITLE
simplify connecting to computer in verdi shell

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1503]
This came out from a discussion with @giovannipizzi 

Currently, this is what one needs to do in order to connect to a computer in the verdi shell
```
c = Computer.get('deneb')
t = c.get_transport_class()(machine=c.hostname,load_system_host_keys=True, **c.get_transport_params())
with t:
    print t.listdir()
    print t.exec_command_wait("whoami")
```
(possibly some differences depending on the transport plugin)

Most users probably are probably not aware that this is even possible, and it would be nice if there was a convenience function in the `Computer` class for this.

**Comment by giovannipizzi** [comment]
As a note, after the refactoring in develop, this is now achieved differently:
```
from aiida.orm.backend import construct_backend
from aiida.common.utils import escape_for_bash
b = construct_backend()
a = b.authinfos.get(Computer.get("deneb"), b.users.get_automatic_user())
t = a.get_transport()
#s = a.computer.get_scheduler()
#s.set_transport(t)
#print s.getJobs(user="aiidauser")

with t:
   print t.whoami()
```

**Comment by giovannipizzi** [comment]
Probably we could have a `Computer.get_active_transport(user=None)` that returns `t` (closed).
If `user is None` it uses by default the `b.users.get_automatic_user()`. What do you think?

**Comment by ltalirz** [comment]
sounds good to me

**Comment by giovannipizzi** [comment]
> Just on the side: I don't even know what "open/closed" or "active/inactive" means in this context.
If possible, I think it would be great if we could do it in such a way that users don't need to bother with this.

I'm not sure if it is possible.
Closed means that there is no SSH connection yet, open means that you have opened a connection. I think it is good to expose this concept to the user (and it should be easy enough to understand).
If a user does not want to bother, they can just use the `with` construct.

**Comment by ltalirz** [comment]
And what is 'active/inactive'?
