### ISSUE TITLE
verdi command that returns the pk of a node given its uuid

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#1515]
Needed for the tutorial (@giovannipizzi)

**Comment by giovannipizzi** [comment]
See also discussion of #934  (potentially a duplicate?)
Also, see this comment:
https://github.com/aiidateam/aiida_core/issues/934#issuecomment-387446065

**Comment by szoupanos** [comment]
Thanks, I summarize here what I will implement:
- _verdi node show pk_  will change to _verdi node show identifier_, where the _identifier_ will be by default a pk and if the flag --uuid is passed, it will be treated as uuid
- I will try to find a general way to do this (if possible) in order to use it easily to all the other commands that accept pks.

**Comment by giovannipizzi** [comment]
Fixed in #1536
