### ISSUE TITLE
Add sorting functionality for attributes.state in QB in django

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida_core#1559]
QB supports sorting by attributes.state in SQLA but not in django backend.
Check if it could also be supported in django?

**Comment by sphuber** [comment]
This should be fixed when JSONB fields are implemented for Django.

**Comment by sphuber** [comment]
Note, however, that the old `state` attribute that was used by `JobCalculation` is still used, but 1) has different values and 2) is only there while the calculation is active and is then removed. The more appropriate attribute to query for the "state" of a calculation is the `process_state` attribute. This will have a value of the `aiida.engine.processes.ProcessState` enum and will always be there.
