### ISSUE TITLE
remove $ from bash commands in docs for copy-paste

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1561]
In some places in the aiida docs ([like here](http://aiida-core.readthedocs.io/en/latest/install/installation.html#install-aiida)), bash commands are preceded by dollar signs, meaning you cannot simply copy-paste them into your shell.

Either simply get rid of them like [here](http://aiida-core.readthedocs.io/en/latest/install/quick_installation.html) or see whether one can have it in such a way that the prompt is not marked when selecting.

**Comment by astamminger** [comment]
#2271

**Comment by sphuber** [comment]
Fixed in PR #2273
