### ISSUE TITLE
improve error message when %aiida does not work

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1562]
When people don't manually [create the ipython config file](http://aiida-core.readthedocs.io/en/latest/install/installation.html#using-aiida-in-jupyter), they get an error message when trying `%aiida` inside a jupyter notebook.

To investigate:
 * Could the error message hint to what the likely problem is?
 * Is it possible to add this configuration automatically, when selecting the [jupyter] extra?

**Comment by sphuber** [comment]
Fixed in PR #2272
