### ISSUE TITLE
default `return` label for WorkFunctions

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1570]
The `return` keyword is reserved and therefore doing

`calc.out.return` will not work (syntax error).
I think that, therefore, we should not use `return` as the default. Suggestions for a better name?

**Comment by sphuber** [comment]
Maybe `result`? Should this also be fixed for the tutorial?

**Comment by sphuber** [comment]
But there is no point in the tutorial where they are asked to do `out.return` for a workfunction? i.e. this is not a problem there?

**Comment by giovannipizzi** [comment]
I'm not sure, I think it's not explicitly asked but people might want to do it. If you think it's something that can be done by tomorrow, I'm also OK to change this now.

**Comment by sphuber** [comment]
I can fix it now and merge it into the tutorial branch. I think it is best as it seems something that people might easily hit when experimenting a bit

**Comment by giovannipizzi** [comment]
great, thanks!
