### ISSUE TITLE
"You are not the daemon user" - Why not?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1575]
We've all been there - you install aiida and it refuses to start the daemon:
```
$ verdi daemon start
        You are not the daemon user! I will not start the daemon.
        (The daemon user is 'aiida@localhost', you are 'richard.wagner@leipzig.de')

        ** FOR ADVANCED USERS ONLY: **
        To change the current default user, use 'verdi install --only-config'
        To change the daemon user, use 'verdi daemon configureuser'
```
This is one of the first things people stumble over when installing aiida. Is this really the default behavior we want?

My gut feeling tells me that in >90% of all cases people want the daemon user to be the user associated with the profile that the daemon is currently running on.
I.e. if you run `verdi daemon start`, it should by default use the user of the current daemon profile.
Of course it's fine to have an option that allows to run the daemon using a different user, but I've never encountered a use case of it in the wild (have you?).

Mentioning @giovannipizzi @sphuber 

P.S. Interestingly, `verdi daemon stop` works also, if you are *not* the daemon user.

**Comment by giovannipizzi** [comment]
It should have been already removed in aiida-1.0.x

**Comment by sphuber** [comment]
Note that the entire concept of a daemon user is gone in `develop` and so it will only be a problem in `v0.12.*`

**Comment by ltalirz** [comment]
Ok, thanks for the quick clarification!
Somehow it still shows up in the search results on readthedocs 
https://aiida-core.readthedocs.io/en/latest/search.html?q=you+are+not+the+daemon+user&check_keywords=yes&area=default
but if you then click on the links it's gone...

Looking forward to being able to build the docs again :-)
