### ISSUE TITLE
verdi click: migrate verdi data

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1584]
Migrate the verdi command `data` to use the new `click` framework

**Comment by szoupanos** [comment]
Sasha: Upf, Bands
Spyros: Cif

**Comment by yakutovicha** [comment]
@sphuber it seems to me that the transition is completed. 
@szoupanos is taking care of writing the tests. 

@sphuber do you think it makes sense to already make a PR or should we wait until @szoupanos  is done with the tests?

I've also noticed that 
> verdi data {cif/structure/trajectory} deposit
is not working at all. It has nothing to do with the click interface but rather with the "deposit" function in "aiida/tools/dbexporters/tcod.py" file.

**Comment by yakutovicha** [comment]
Created PR  #1738
