### ISSUE TITLE
Possibly add some documentation on aiida core vs epfl version

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#159]
Originally reported by: **Leopold Talirz (Bitbucket: [ltalirz](https://bitbucket.org/ltalirz), GitHub: Unknown)**

----------------------------------------

The context is the following:

I have been using aiida_epfl-0.4.1 for some time without any problems.
In order to test some recent improvements made by Giovanni Pizzi, I then downloaded the develop branch of AiiDA_core (sha1 hash 7cdc01a54598171a5109409e341ae5b84f4084a7) and copied it over my aiida_epfl-0.4.1 (is this allowed?).
I restarted the daemon, performed the upgrade of the database as requested, and everything seemed fine.

However, I noticed that in my QE geometry optimizations performed after the upgrade that they are now missing the output_trajectory and output_bands nodes (previous calculations in the database remained unaffected).

```
#!bash
$ verdi calculation show 873
[...]
remote_folder 874 RemoteData
output_array 878 ArrayData
output_parameters 877 ParameterData
retrieved 875 FolderData
output_structure 876 StructureData
```

If desired, I will provide a reduced example of the calculations, but maybe the problem is already apparent from what I did with the aiida core/epfl versions. In my opinion, it could be quite helpful to spend a few words in the "installation" section of the official documentation on the relation between the aiida core and the epfl version and how the two can (or can't) be mixed.

Best,
Leo

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/159

**Comment by giovannipizzi** [comment]
We are going to convert aiida_epfl to an external package, not a copy of AiiDA plus the plugins. Putting this on hold.

**Comment by giovannipizzi** [comment]
I'm closing this as for the next release we are not going to release a aiida_epfl package, as everything that we want to make public is currently in the aiida_core branch (see PR #379)
