### ISSUE TITLE
Add element X

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#1606]
Sometimes it would be nice to not associate a position with an atom or simply not set a symbol to one of the current entries in aiida.common.constants.elements{}. 

Please consider to add element X, for instance at slot 0 in this dictionary.

This would be useful for parsing, when the user specifies non-elemental names (which can be set to names), while we still need to enter a valid entry for symbols. One could of course put in one of the existing elements as a dummy, say H, but that might cause confusion. We would also like to raise something that forces the user to set the potentials manually in cases where e.g. X is defined. Such a feature would not be easy if, say we put it to H.

**Comment by giovannipizzi** [comment]
It looks like a good suggestion. I'll think a bit more about it, but I don't see major downsides (and I didn't see the use case when I first implemented it). I know ASE supports it, do you know if pymatgen supports this? Do you think you would be able to prepare a PR? Maybe we can discuss this next week together.

**Comment by espenfl** [comment]
I do not know pymatgen that well, but their construction is a bit different. I know for instance they have a DummySite, where X is used. They also have Site.PeriodicSite.Lattice etc. and then the Site are bonded to this. I mentioned to Rico that maybe in the long term we should consider to detach symbols from the structure object and only allow points/positions. Then we have other objects, like Atoms, Species, Orbitals, Particles, whatever the users wants that we tie to the selected positions. This probably involves a lot of rewrite and potential merge conflicts with plugins and is probably better left for integration when we for instance want to generate something like a 'material' plugin that houses i.e. VASP, Abinit, QE etc. Yes, let us discuss next week.

**Comment by sphuber** [comment]
Fixed in PR #1613
