### ISSUE TITLE
readthedocs: links for switching versions not working

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1615]
On http://aiida-core.readthedocs.io/en/latest/, the link for switching to a different build of the docs (in the sidebar) is currently not working.

The other versions of the docs, like http://aiida-core.readthedocs.io/en/v0.12.0/, are still there but people will only reach them if they know where to look.

**Comment by sphuber** [comment]
It seems to be working for me now. Do you still have this problem?

**Comment by ltalirz** [comment]
Great, works again!
