### ISSUE TITLE
aiida export: error while creating a large export file (>2 Gb).

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida_core#1617]
While trying to export a large AiiDA database I encountered the following error: 

> STARTING EXPORT...
> STORING DATABASE ENTRIES...
> Exporting a total of 209522 db entries, of which 209520 nodes.
> STORING NODE ATTRIBUTES...
> STORING NODE LINKS...
> STORING GROUP ELEMENTS...
> STORING DATA...
> STORING FILES...
> Traceback (most recent call last):
>   File "/usr/local/bin/verdi", line 11, in <module>
>     sys.exit(run())
>   File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/verdilib.py", line 1050, in run
>     aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
>   File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/verdilib.py", line 1035, in exec_from_cmdline
>     CommandClass.run(*argv[command_position + 1:])
>   File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/baseclass.py", line 217, in run
>     function_to_call(*args[1:])
>   File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/commands/exportfile.py", line 31, in cli
>     verdi()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/commands/exportfile.py", line 134, in create
>     outfile=outfile, overwrite=overwrite, **additional_kwargs
>   File "/usr/local/lib/python2.7/dist-packages/aiida/orm/importexport.py", line 2173, in export_zip
>     export_tree(what, folder=folder, silent=silent, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/aiida/orm/importexport.py", line 1956, in export_tree
>     dest_name='.')
>   File "/usr/local/lib/python2.7/dist-packages/aiida/orm/importexport.py", line 2157, in insert_path
>     real_dest)
>   File "/usr/lib/python2.7/zipfile.py", line 1148, in write
>     self._writecheck(zinfo)
>   File "/usr/lib/python2.7/zipfile.py", line 1114, in _writecheck
>     " would require ZIP64 extensions")
> zipfile.LargeZipFile: Files count would require ZIP64 extensions
> 

To reproduce the error I've created the [following script](https://github.com/aiidateam/aiida_core/files/2067087/zip_test.py.txt).

The corresponding output looks as follows on my PC:
> testing fsize : 953 (Mb) time(allow64) : 1.90 (sec) time(Notallow64) : 1.89 (sec)
> testing fsize : 1049 (Mb) time(allow64) : 2.04 (sec) time(Notallow64) : 2.07 (sec)
> testing fsize : 1144 (Mb) time(allow64) : 2.23 (sec) time(Notallow64) : 2.27 (sec)
> testing fsize : 1239 (Mb) time(allow64) : 2.49 (sec) time(Notallow64) : 2.38 (sec)
> testing fsize : 1335 (Mb) time(allow64) : 2.60 (sec) time(Notallow64) : 2.65 (sec)
> testing fsize : 1430 (Mb) time(allow64) : 2.76 (sec) time(Notallow64) : 2.80 (sec)
> testing fsize : 1525 (Mb) time(allow64) : 2.99 (sec) time(Notallow64) : 2.97 (sec)
> testing fsize : 1621 (Mb) time(allow64) : 3.14 (sec) time(Notallow64) : 3.54 (sec)
> testing fsize : 1716 (Mb) time(allow64) : 3.47 (sec) time(Notallow64) : 3.36 (sec)
> testing fsize : 1811 (Mb) time(allow64) : 3.60 (sec) time(Notallow64) : 3.59 (sec)
> testing fsize : 1907 (Mb) time(allow64) : 3.74 (sec) time(Notallow64) : 3.81 (sec)
> testing fsize : 2002 (Mb) time(allow64) : 4.00 (sec) time(Notallow64) : 3.95 (sec)
> testing fsize : 2098 (Mb) time(allow64) : 4.05 (sec)
> Traceback (most recent call last):
>   File "tip_on_fly.py", line 24, in <module>
>     print "time(Notallow64) : %.2f (sec)" % make_zip(create_file(size), allowZip64=False)
>   File "tip_on_fly.py", line 14, in make_zip
>     zipf.write(infname)   
>   File "/usr/lib64/python2.7/zipfile.py", line 1148, in write
>     self._writecheck(zinfo)
>   File "/usr/lib64/python2.7/zipfile.py", line 1114, in _writecheck
>     " would require ZIP64 extensions")
> zipfile.LargeZipFile: Filesize would require ZIP64 extensions

As one can see there is no time difference (apart from a statistical error) whether one enables or disables allowZip64 flag. Therefore I would propose to enable this flag in AiiDA by default.

I will prepare a pool request for that.

**Comment by giovannipizzi** [comment]
Good for me! Mentioning also older issue #998

**Comment by yakutovicha** [comment]
solved: 9241c5fb2bbc64e8a11cc9f05e772dd12a471e12
