### ISSUE TITLE
Transition all ORM classes to new backend design

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1621]
Currently we have some of the ORM models in the 'old' system whereby the backend being used is selected at import time.

We have developed a new backend design that doesn't rely on using run-time import selection and instead uses a concrete instance of an abstract backend to do all provenance graph interaction.  So far we have ported:
* User
* Authinfo
* Log entry

to this new system.  We may want a plan to migrate all the ORM classes to the new way of doing things.

The new system has one major advantage which is that multiple backends can be loaded simultaneously (even across types e.g. Django and SQLA).

**Comment by sphuber** [comment]
Done and done
