### ISSUE TITLE
Add timeout to Jenkins scripts

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1627]
See e.g.
https://stackoverflow.com/questions/38096004/how-to-add-a-timeout-step-to-jenkins-pipeline?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

I've experienced jobs remaining stuck and therefore running for hours.
Even just putting a safe limit like 1 hour should be better than nothing.

**Comment by sphuber** [comment]
Fixed in PR #1629
