### ISSUE TITLE
reduce size of pypi install

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1632]
As of today, after installing AiiDA 0.12.0 via pip, the package takes up 19MB on disk space, 8.4MB of which is a single file:
https://github.com/aiidateam/aiida_core/blob/develop/aiida/backends/tests/export_import_test_files/parents_of_6537645.aiida

Can this file be replaced?

A few other packages for comparison
```
1.4M	paramiko
1.5M	setuptools
3.5M	tornado
5.8M	IPython
8.2M	sqlalchemy
19M  	aiida
```

**Comment by sphuber** [comment]
Fixed in PR #1645
