### ISSUE TITLE
Abstract help option definition for all verdi commands and sub commands

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1638]
The default help option for any `click` command only accepts the `--help` flag, however, we would like to have both `-h` and `--help` be recognized as valid help string options. This should be added once for all commands and sub commands to keep the interface consistent. Tests should be added to guarantee that both options work for all `verdi` commands

**Comment by DropD** [comment]
Is it possible that context_settings only propagates when `@pass_conext` is used? If yes, we might have to do that on every leave command or alternatively extend `click.Command` and use the subclass consistently.

**Comment by sphuber** [comment]
Fixed in #1795
