### ISSUE TITLE
Legacy workflows not instanciable from outside 'aiida.workflows'

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1652]
## Background:
 * It is unclear how much legacy workflows are still in use
 * Legacy plugin loading (from folders) will go away in 1.0 
 * Workflow.__init__ still enforces that it's caller must be inside aiida/workflows

## Problem:
Legacy workflows are currently impossible to istanciate from a plugin.

**Comment by sphuber** [comment]
I helped migrate @tsohier to `develop` this morning and now `load_workflow` is broken, exactly for the reason you stated, as it attempts to use the full module path of the workflow as an entry point. Within the group there are still quite some people relying on the old workflows. The basic Quantum ESPRESSO one have been ported, but some higher level wrapping ones have not.

**Comment by sphuber** [comment]
This is a known "problem" and will not be supported as legacy workflows will be deprecated
