### ISSUE TITLE
Problem with the ExitCode enum

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1653]
The changes introduced in #1648 are partially incorrect.

For instance, calling `sys.exit(ExitCode.UNKNOWN)`
1. prints `ExitCode.UNKNOWN` on the screen before exiting (this is because `ExitCode.UNKNOWN` is  a special type and not simply its value. One e.g. should do `sys.exit(ExitCode.UNKNOWN.value)`. It would be ideal if we find a way to have an enum passing directly its values rather than going in the code and putting a `.value` everywhere, but I  don't know if it's possible
2.  always exits with error code 1 as `sys.exit()` does not know how to get the value from that object

The same problem in e.g. `echo_critical` (that I would still like to be called  `echo_critical_exit` ;-) ), even if point 2 is less apparent because `ExitCode.CRITICAL` is 1

**Comment by sphuber** [comment]
Fixed in PR #1654
