### ISSUE TITLE
Implement click bash completion for verdi user update

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1662]
I couldn't figure out how to do bash completion using the 'click' way so it works now with the hybrid system we have in place (i.e. auto-completes emails for user modify) but if we switch to pure click I think it won't work.

Need help.

**Comment by sphuber** [comment]
`verdi user update` is now done by `verdi user configure` which takes the `email` of the user as an argument. This argument should be autocompleted
