### ISSUE TITLE
Document Group.query

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1674]
I would have expected `my_group.query` to be a convenient shortcut for querying nodes inside the group.
Apparently that's not what it does - please document it
https://github.com/aiidateam/aiida_core/blob/e2a8269d16c613f6a0cfbfd39da35d1ec2bcb324/aiida/orm/implementation/sqlalchemy/group.py#L261-L264

**Comment by yakutovicha** [comment]
This function is now deprecated. It can be replaced by standard QueryBuilder. So I will close this issue
