### ISSUE TITLE
JobCalculation submission fails with "TypeError: load_node() got an unexpected keyword argument 'parent_class'"

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1689]
## Steps to reproduce
Start any JobCalculation on the current develop branch (In my case it was a VaspCalculation)

## Expected behaviour
The calculation gets submitted and runs

## Observed behaviour
Submission fails, logshow output follows:
```
*** 5932: SUBMISSIONFAILED
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> ERROR at 2018-06-27 14:09:57.163604+00:00
|   Submission of calc 5932 failed, check also the log file! Traceback: Traceback (most recent call last):
|     File "/home/hauselmann/Documents/aiida-fork/aiida/daemon/execmanager.py", line 137, in submit_calc
|       folder, use_unstored_links=False)
|     File "/home/hauselmann/Documents/aiida-fork/aiida/orm/implementation/general/calculation/job/__init__.py", line 1606, in _presubmit
|       this_code = load_node(code_info.code_uuid, parent_class=Code)
|   TypeError: load_node() got an unexpected keyword argument 'parent_class'
```

**Comment by sphuber** [comment]
The `parent_class` keyword has been changed to `sub_class` in the `verdi` branch. My suspicion is that you switched between `develop` and `verdi` in the same environment, and a lingering `*pyc` file is being caught. I would suggest cleaning the `pyc` files and restarting the daemon and I think that should fix it

**Comment by DropD** [comment]
Thanks a lot, that did it!
