### ISSUE TITLE
create_requirements.py - dead code?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1692]
This file looks to me like dead code
https://github.com/aiidateam/aiida_core/blob/release_v0.12.2/utils/create_requirements.py

 * it isn't used anywhere in aiida
 * it looks for `dependency_links` inside `setup_requirements.py` which does not exist

@giovannipizzi 
Can this file be deleted?

**Comment by sphuber** [comment]
This was used to generate the `requirements.txt` but we no longer use this because we already put explicitly dependency versions in the `setup_requirements.py`, so as far as I am concerned we can get rid of the file

**Comment by giovannipizzi** [comment]
ok with me to remove it

**Comment by sphuber** [comment]
Fixed in #1702
