### ISSUE TITLE
`verdi code setup` allows to setup code with identical name on same computer

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1719]
Currently it is possible to create two codes with an identical name on the same computer, e.g. `doubler@localhost` and `verdi code setup` will not complain. However, loading either of these codes will then be impossible because the loader will always throw an `MultipleObjectsError`

**Comment by ltalirz** [comment]
So, my first question is about policy:
Do we want to require code labels (`<code>@<computer>`) to be unique?
What happens if you import one from a database?

I guess, the answer is: no.

This leaves the question of what to do when the user requests to set up a code with the same label.
Just issue a warning?

> loading either of these codes will then be impossible because the loader will always throw an `MultipleObjectsError`

Is this true, i.e. can the code not be loaded by PK?

**Comment by sphuber** [comment]
With the new entity loaders that I implemented for the `click` migration, yes they can be loaded. The loaders will infer the identifier type from the value, since through the command line all values are strings and type information is lost. In fact, one can always use the pk's since that is the first type that is attempted by the loader and those are guaranteed to be unique. I guess regarding policy, we can allow it. We should just think about replacing older ways of loading entities, because `Code.get_from_string` will of course be useless in that situation, but this is a separate issue I would say

**Comment by ltalirz** [comment]
Seems to me this is already fixed in `develop`:

```
$ verdi computer list
# List of configured computers:
# (use 'verdi computer show COMPUTERNAME' to see the details)
* localhost

$ verdi computer setup
Info: enter "?" for help
Computer label: localhost
Hostname: localhost
Description []:
Enable the computer? [True]:
Transport plugin:
Transport plugin:
Transport plugin:
Transport plugin: local
Scheduler plugin: direct
Shebang line (first line of each script, starting with #!) [#!/bin/bash]:
Work directory on the computer [/scratch/{username}/aiida/]:
Mpirun command [mpirun -np {tot_num_mpiprocs}]:
Default number of CPUs per machine:
Default number of CPUs per machine: 2
Critical: A computer called localhost already exists.
Use "verdi computer update" to update it, and be careful if you really want to modify a database entry!
```
@sphuber Let's close this?

It's just the last info message that should be deleted.

**Comment by sphuber** [comment]
Already fixed in verdi click migration and error message adjusted in PR #1952
