### ISSUE TITLE
Remove PATH manipulation workaround on travis setup (after travis fixes the PATH)

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1739]
**Status: currently blocked**

### Explanation
PRs #1736 and #1726 put the workaround in place, ensuring that postgres 9.5 is the first on PATH to be picked up by mlocate and therefore pgtest. The fine folks at Travis-CI are working on fixing this on their side. When they are done, we should remove our workaround.

**Comment by dev-zero** [comment]
@DropD do you have a reference that they're working on it? As far as I understood it from what I read is that this was intentional behaviour. Btw, `mlocate/locate` is not part of the equation anymore: if `pgtest` finds `pg_ctl` in `$PATH` it doesn't use use `locate` to find it.
