### ISSUE TITLE
JobCalculations that are cached do not have anything in their repo folder

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1744]
Therefore, for instance, doing a `verdi calculation inputcat` on a cached calculation gives an error.

I think the correct behaviour should be, beside copying all attributes, also copying the whole repository folder.
@greschd do you agree? Where is the code to do this?
Also, I think maybe this should be fixed both in 0.12.x and in develop?

**Comment by greschd** [comment]
I agree, it should also copy the folder contents. In principle that is done in the ``Node._store_from_cache`` method, but I need to check why this fails.

Do you have a minimal failing example for testing?

**Comment by giovannipizzi** [comment]
Well, I imagine is reproducible, our was in a workflow, but I think that if you enable caching and run e.g. the file 
`examples/submission/quantumespresso/test_pw.py` from aiida-quantumespresso and run it twice, it should show the problem (notes: the example already has the pseudos; but it is still written in the "old-style").

**Comment by greschd** [comment]
As far as I can tell, it's the ``get_folder_list`` method which is broken (doesn't return anything).

**Comment by greschd** [comment]
Ah I see, that only returns things which are inside the ``path``, while the inputs are in the ``raw_input`` folder. So, what's the best way to copy the whole folder?

**Comment by giovannipizzi** [comment]
if new is the node you are creating, and old the one you are caching from, this should work:
```python
new.folder.replace_with_folder(old.folder.abspath, move=False, overwrite=True)
```

**Comment by greschd** [comment]
Figured it out in the meantime :+1: 

For the v0.12 version, this is implemented in ``Node.copy``. Do you know if it is safe to change there, or might this have unintended consequences?

**Comment by giovannipizzi** [comment]
Thanks @greschd!

**Comment by giovannipizzi** [comment]
@AntimoMarrazzo FYI this is now fixed
