### ISSUE TITLE
verdi data (click): reuse options

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1747]
* many of the commands use e.g. a --format option, and others. All these should be defined only once and reused
* some of the commands have options like group_name, user_name, etc and then do manual checking to verify that it is a group name or user name etc. The standard options for user / group / what have you should be used which makes the manual checking superfluous, even if in the end only the name is used.

**Comment by dev-zero** [comment]
@DropD besides options there is for example the `plugins` subcommand which is implemented twice (three times with PR #1755), but each time differently.
