### ISSUE TITLE
Export/import of comments

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#1760]
The export/import of comments on nodes should be done under this ticket.
We should see if people are interested about this.
- [x] Export
- [x] Import (SQLA)
- [x] Import (Django)

**Comment by giovannipizzi** [comment]
@szoupanos I got a feedback this morning to keep this.

**Comment by CasperWA** [comment]
- [ ] Export
- [ ] Import

**Comment by sphuber** [comment]
Fixed in PR #2413
