### ISSUE TITLE
Export/import of extras

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#1761]
We should decide what we do with node extras. If we decide to export them, the export procedure is straightforward. 

However, we should discuss and decide what we do during import and especially when the node already exists on the receiver side and has extras. In that case should we update the extras (add additional values and update existing), overwrite them or concatenate them?

**Comment by DanielMarchand** [comment]
@sphuber suggested that I give this issue a thumbs up :D Please, 'the community' really would like this feature!

**Comment by DanielMarchand** [comment]
Hi everyone, I highly encourage this feature! Actually it will soon become fairly needed in our project. I was thinking of writing a hack workaround but if its going to be added the next release I'll wait :)

**Comment by sphuber** [comment]
@DanielMarchand it will certainly be part of `v1.0.0` but it might not make it into `v1.0.0b1` unfortunately. We will keep you updated

**Comment by yakutovicha** [comment]
To continue the discussion I want to emphasize the following points:

1. To formalize dictionary merging let's consider all possible outcomes. We note that those operations can be applied in the situation where we want to update `old_extras` of an existing node in our database with a `new_extras` of the same imported node.

| `old_extras` | `new_extras` | possible operations |
| -------------- | -------------- | -------------- |
| 'a': 1 |   | keep/not keep |
|  | 'b': 2  | create/not create |
| 'c': 3 | 'c': 4 | update/keep old value/delete |

where
- *keep* / *not keep* means to keep or to not keep an existing extra in `old_extras` if it is not present in `new_extras`
- *create* / *not create* means to create or to not create a new extra in `old_extras` if it is only present in `new_extras`
- *update* / *leave* / *delete* operations will be performed in case there is a name collision. *update* will take value from the `new_extras`, *leave* will keep the value from the `old_extras` and *delete* will delete the extra.

| keep initial?  | create new? | update/leave/delete?  | implemented? | name |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| N | N | U | N |  keep_updated_only |
| Y | N | U | N | keep_initial_and_updated |
| N | Y | U | Y | **mirror** |
| Y | Y | U | Y | **update_existing** |
| N | N | L | N | keep_old_if_in_both |
| Y | N | L | Y | **none** |
| N | Y | L | N | keep_new_and_old_if_same |
| Y | Y | L | Y | **ignore_existing** |
| N | N | D | N | delete_all |
| Y | N | D | N | keep_only_old |
| N | Y | D | N | keep_only_new |
| Y | Y | D | N | keep_only_old_new |

2. **Default** for the non-private extras should be either **ignore_existing** or asking every time there is a collision.

3. If value of an extra is a dictionary, I would just do a simple comparison (`if a == b`) and proceed according to the specified path (from the table above).

4. Together with @giovannipizzi we agreed that it would make seance to have a table of default operations for every private extra as it is hard to define a "good enough" default behavior that would work for all the cases.

**Comment by yakutovicha** [comment]
After today's discussion we agreed that the aiida extras (#2231) related functionality should be provided independently from the "standard" extras. Therefore, this issue will only focus on the latter ones.

**Comment by giovannipizzi** [comment]
Note: caching uses at least another key (beside the hash): `_aiida_cached_from`

**Comment by sphuber** [comment]
Fixed in PR #2416
