### ISSUE TITLE
Group insertion performance at the SQLA import can be improved

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#1770]
In the end of the of the SQLA import we add nodes to group(s).
It seems that some time is spent there.
We should see if we can get ideas from #1319 to improve the performance

**Comment by giovannipizzi** [comment]
In practice, this issue is a duplicate of #1319 
Probably close one of the two...

**Comment by szoupanos** [comment]
Discussion will continue in #1319
