### ISSUE TITLE
Bug in string formatting of memory directive of direct scheduler

### ISSUE THREAD

**Issue by mikeatm** [aiidateam/aiida_core#1778]
Looking at this line in the direct sheduler, i think its a bug,  it should be string interpolation
[append](https://github.com/aiidateam/aiida_core/blob/e98f3f9d6ec103e7c4f9000ef1437e3aadba36dc/aiida/scheduler/plugins/direct.py#L152)

**Comment by sphuber** [comment]
Fixed in PR #1779
