### ISSUE TITLE
LocalTransport: too many public methods (?)

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1784]
The class surpasses the limit we set for pylint for the amount of public methods.

```
pylint: too-many-public-methods / Too many public methods (31/20)
```

The message is ignored for now, but we should think about whether we need to raise the limit or refactor the class in the long run.

**Comment by giovannipizzi** [comment]
I think it's ok to keep the default, and to ignore for transports where we actually need many methods
