### ISSUE TITLE
Fresh AiiDA installation gives error for verdi command

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida_core#1796]
I created new virtualenv and installed aiida with "pip install -e .[all]" command.
If I try to use verdi its gives below error:

```python
|aiidapy|py-2.7.6 theospc24 in ~/git/workarea/aiida_core
± |develop ✓| → verdi
Traceback (most recent call last):
  File "/home/waychal/git/workarea/aiidapy/bin/verdi", line 5, in <module>
    from aiida.cmdline.commands import verdi
  File "/home/waychal/git/workarea/aiida_core/aiida/cmdline/commands/__init__.py", line 28, in <module>
    from aiida.cmdline.commands import (cmd_calculation, cmd_code, cmd_comment, cmd_computer, cmd_data, cmd_daemon,
  File "/home/waychal/git/workarea/aiida_core/aiida/cmdline/commands/cmd_shell.py", line 195
    exec (compile(handle.read(), pythonrc, 'exec'), imported_objects)  # pylint: disable=exec-used
SyntaxError: unqualified exec is not allowed in function 'shell' it contains a nested function with free variables

```

**Comment by sphuber** [comment]
on which branch/commit or version does this occur?

**Comment by waychal** [comment]
@sphuber I was using develop branch. But the issue was with python version 2.7.6. It seems like we can not use aiida with that version. I upgraded my python to 2.7.12 and it worked fine.
I am closing this issue.

**Comment by waychal** [comment]
AiiDA throws above error for verdi command when installed with python version 2.7.6. It works fine when installed with python >=2.7.7
Either fix this issue in AiiDA or add note somewhere saying that it requires python >=2.7.7
