### ISSUE TITLE
Auto-completion of cli parameters is broken in combination with InteractiveOption

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1802]
Click commands specifying a parameter with auto-completion through the `complete` method, in combination with another option that uses the `InteractiveOption` class, are broken when hitting `<tab><tab>`. It seems that instead of just hitting the `complete` of the parameter in question, the prompt loop for all the other parameters is activated. This results in the command hanging.

**Comment by giovannipizzi** [comment]
I'm working on it.
To reproduce, it's easier to call
`COMP_WORDS="verdi computer setup -" COMP_CWORD=4 _VERDI_COMPLETE=complete-bash verdi`
