### ISSUE TITLE
Update installation documentation to reflect new verdi completion command

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1810]
Because the old `verdilib` has been ripped out and replaced with `click`, the completion activation also changed. This has not been reflected in the documentation yet. It should also be included in the migration notes, to tell users to update their bash activation scripts.

The new line should be
```
eval "$(_VERDI_COMPLETE=source verdi)"
```
Note, that currently `verdi completioncommand` no longer exist. Investigate if it is possible to reintroduce it such that the old line
```
eval "$(verdi completioncommand)"
```
would still work in a backwards compatible way

**Comment by giovannipizzi** [comment]
@sphuber is `_VERDI_COMPLETE=source` our extension or something from click? in the latter case, is there a link to the respective doc? (useful for me to address #1802 #1830)

**Comment by sphuber** [comment]
[it's from click](https://click.palletsprojects.com/en/7.x/bashcomplete/)

**Comment by giovannipizzi** [comment]
thanks! I'll look into the issues now. would it make sense, for back compatibility, to keep the completioncommand as it was but return the output from click?

**Comment by sphuber** [comment]
That is what I was trying at first and so I looked into that, but I could not get it to work and decided there were other more pressing things. But if you can make it work that would be nice
