### ISSUE TITLE
Exceptions caught in TransportTasks for JobProcess should be more robust

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1814]
In the `TransportTasks`, there are a multitude of calls over ssh that can except in various ways. Connections can be unavailable, scheduler calls can except etc. Instead of triggering `on_excepted` for the `JobProcess` straight away, depending on the exception, it should be rescheduler for a retry after a certain amount of time, potentially multiple times, ultimately putting the `Process` in the paused state. The user can then inspect the problem and if resolved, resume the process. This issue should be tackled in two steps:

- [x] #1834 Implement an automatic retry mechanism for transport tasks with exponential backoff
- [x] #1835 Optional pausing of process for certain exceptions after the exponential backoff retried the maximum number of allowed attempts

**Comment by broeder-j** [comment]
u.a it causes Failed calculation to get stuck in the RETRIEVING state, if certain expected files are not there on the remote. In a solution this case should also be tested.
