### ISSUE TITLE
Heartbeat timeout is causing daemon connection to be reset

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1821]
Each connection between a daemon worker and RabbitMQ will have a timeout set. Half this time is what is known as the heartbeat interval. Each heartbeat interval, RabbitMQ will send a request to each subscriber to confirm it is still alive. If the subscriber fails to respond to a heartbeat request within the timeout (i.e. it missed two consecutive heartbeats), RabbitMQ will consider the subscriber to be dead and will close the connection.

The timeout value is determined by the server by taking the minimum value of the default for the server and the value requested for the specific connection by the client. Unfortunately, since RabbitMQ 3.5.5 the default value for the server has been lowered from 580 seconds to 60 seconds. This means that the client, AiiDA, can at most set a timeout of 60 seconds. Given that many tasks in AiiDA, such as ssh transport commands, can take more than 60 seconds, there is a large chance of it missing the heartbeat. This is the reason that RabbitMQ was closing the connections, which resulted in the `socket error 104` from the `pika` library.

Unfortunately, the only way that the heartbeat timeout can be raised, is by changing the configuration of the RabbitMQ server, which requires root privileges. However, having to configure RabbitMQ is something we would like to prevent if at all possible, because it will greatly increase the difficulty of installing AiiDA.

**Comment by muhrin** [comment]
`plumpy` v0.11 fixes this (via the complete `kiwipy`, `topika` stack).  Not, it's not easy to test and prove this.  One idea I have is to set a low RMQ heartbeat and, say, block on the main thread for something a little more than 2x this and check if the connection is still alive.  @sphuber, do you think this is about the best that we can do?

**Comment by sphuber** [comment]
That depends. The connection might actually drop but be reconnected by the automatic reconnecting functionality (which should now also work? In any case that should also be tested somehow). If blocking the main thread would mean that this functionality is also blocked, this potential issue would of course be neutralized.

**Comment by muhrin** [comment]
So, the main thread isn't involved in this process at all so in some sense it's expected that blocking the main thread wouldn't knock over the connection.  I'm trying to devise a test for this in `kiwipy`.  The idea I have is to schedule a task in the loop that sleeps for more than 2x the heartbeat interval.  Then the loop will continue and the connection code will now have to deal with the fact that it now finds that the connection has fallen over.
