### ISSUE TITLE
Authinfo backend is set wrong

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1832]
The ``DjangoAuthInfoCollection._from_dbmodel`` sets the ``backend`` to ``self``:

```python
def _from_dbmodel(self, dbmodel):
    return DjangoAuthInfo._from_dbmodel(self, dbmodel)
```

I think this is wrong (it should be the ``_DJANGO_BACKEND`` instead), but since I'm not familiar with that part of the code maybe somebody else should double-check it.

**Comment by sphuber** [comment]
I coincidentally ran into this problem as well and the problem was not just there. I fixed it and the rest of the problems in PR #1839 so I am closing this. Thanks for the report though
