### ISSUE TITLE
Type of projected uuid from QueryBuilder

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#1862]
Currently, when a uuid is added to a query projection, QB returns a uuid.UUID type of value.
e.g.
```
        qb = QueryBuilder()
        qb.append(Node, project=['uuid'],
                  filters={'id': {'==': n.id}})
        [uuid] = qb.first()
```
This is not what happens in Django. Moreover, it causes other problems as we see at issue #1861 
This should happen because uuid is stored as uuid.UUID type in SQLA.

The behaviour of the QB should be uniform in both backends (I would say, return always a unicode uuid, but I am open to suggestions etc)

**Comment by sphuber** [comment]
Fixed in #2259
