### ISSUE TITLE
verdi graph generate throws "String ran past end of line" on graph generation

### ISSUE THREAD

**Issue by astamminger** [aiidateam/aiida_core#1874]
When executing ``verdi graph generate`` on our cluster ``dot`` always throws the "String ran past end of line" error. We are using
```
$ dot -V
dot - graphviz version 2.26.3 (20100126.1600)
```
and the issue is obviously caused by the two ``\n``-newline characters in `aiida.common.graph` [here](https://github.com/aiidateam/aiida_core/blob/develop/aiida/common/graph.py#L58) and [here](https://github.com/aiidateam/aiida_core/blob/develop/aiida/common/graph.py#L61). If I escape those two newline-chars everything works as expected (no errors and the produced graphs look as intended). Is there any special reason for those two chars not being escaped?

**Comment by astamminger** [comment]
A small bump: Any thoughts on that topic?

**Comment by giovannipizzi** [comment]
Indeed, having a literal `\n` in the code is probably better. I checked also in newer versions of `dot` (`dot - graphviz version 2.38.0 (20140413.2041)`) and it actually a literal `\n` produces a newline in the PDF, so I'm ok with this fix.

**Comment by sphuber** [comment]
Fixed in PR #2275
