### ISSUE TITLE
SyntaxError: unqualified exec is not allowed in function 'shell' it contains a nested function with free variables

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#1884]
When running `verdi` this appears:

`SyntaxError: unqualified exec is not allowed in function 'shell' it contains a nested function with free variables`

From `cmdline.commands.cmd_shell`. Do we need to use exec? I am running python 2.7.5 here. Have not yet tried a newer python version, so that could be the cause. If so, dependencies should be updated.

**Comment by sphuber** [comment]
This is a known issue (see #1796 ) for python <= 2.7.6
Those versions are really old, but unfortunately there are still some OS'es that ship with it as the default.
At this point it is not clear if it can be fixed easily, or if maybe we should just document it and add hard requirement of `python >= 2.7.7`

**Comment by espenfl** [comment]
That already reported issue escaped my mind. Sorry. Yes, not only does it ship with this as default, but some production clusters refrain from doing system updates past base packages. Especially python related stuff. E.g. packaging utils etc. might brake, which is important to keep intact. However, in most cases the user can install a new python version locally or load a module. So supporting older python versions is not very important. However, I think one should make a hard requirement as it simply wont run on 2.7.5/6.

**Comment by sphuber** [comment]
I think I found a fix. I tested it locally for 2.7.6. I am seeing now if I can run the entire test suite on Travis for 2.7.6. However, I have done this fix on `develop`. Since this had to be done in the command line code, which has changed enormously, it might not be trivial to port it on the release branch. How important do you think it is to have this fix on the release branch?

**Comment by espenfl** [comment]
I am not sure when you want to merge `develop` and `release`. I suspect most (me included) run `develop`, even in production at this stage, but I might be wrong. #1796 was also on `develop`.  From time to time I have been using 2.7.5 and that worked on `develop` until one of the recent commits. Due to this I do not think the fix is necessary for `release`, but I am not sure.

**Comment by sphuber** [comment]
The tests ran successfully on Travis for `2.7.6` but they do not have `2.7.5` available so could not test that

**Comment by sphuber** [comment]
Regarding the branch, I just verified that this problem was introduced in the migration of `verdi` to `click` and therefore is only present in `develop`.
