### ISSUE TITLE
Handle ANSI escape and csi characters

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#1887]
In the latest `develop` many of the tests fail if the `stdout` has some csi characters prepended when using `LocalTransport` (SshTransport seems fine, but YMMV). This was not an issue until recently (possibly the new click command things).  We have also seen this in isolated cases in `schedulers.plugins.direct` when working on workchain tests that run locally. Here, also stdout etc. is analyzed. Both cases can be fixed by removing such characters in the `exec_command`. Right now I do not know of any python library that has a filter to handle all known cases of "functionality" ANSI codes. There is `ansifilter`, but not sure if we want to be dependent on that. I suspect we would have to build a list based on reported issues. In my case I have `\x1b[H\x1b[J` (CSI H CSI J) that needs removing. Have you considered this before? I can submit a PR on some suggestions if you want.

**Comment by dev-zero** [comment]
well, if it is really necessary, we should use the library since these kind of character mangling is very error prone, especially when you want to do proper string encoding (bytes, vs strings, see Python 3).

On the other hand, it would be nice to know which commands return such ANSI code sequences since most *nix programs disable them if they detect that their stdout is not connected to a terminal but a pipe.
And we should do the same.

**Comment by espenfl** [comment]
Yes, a library would be better for sure. These things usually appears from the commends of the direct scheduler. They would most likely not be a bit problem during production, but seems to cause a bit of headache in a testing and developer environment.

**Comment by espenfl** [comment]
Investigated colorama. That seems great for adding color to printout. Would probably give a nice additional feature to the click and verdi. But I am not sure the effort is worth it. Furthermore, for this particular case I do not really see any direct functionality in colorama. Colorama sets up the `stdout` and `stderr` when initializing with `init(strip=True)`. If we then pipe whatever we get through here it should in theory work. No idea of the overhead. I suspect this will mostly only be an issue with the direct scheduler. However, there are plans to introduce monitoring of the `stdout` and `stderr` of specific jobs (in order to act) and here, these issue might appear unless the user runs a clean system. Further thoughts on where to take this?
