### ISSUE TITLE
Complaints about TERM environment variable not set in tests

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#1890]
If a user has for instance `clear` in e.g. `.bash_profile`, this appears running `verdi devel tests`:

`AssertionError: 'TERM environment variable not set.\n' != ''`

When running the `ssh` tests.

How strict should Aiida be with respect to the system config files?  Commands like clear in your `.bash_profile` etc. should possibly be allowed (albeit not always a smart thing to do). Possibly, the `-t` option can be used. Or checking for this error and ignoring it. If neither it should maybe be mentioned explicitly in the documentation? There is of course other system based workarounds to this which is not related to Aiida, like the obvious, removing or moving the clear statement.

**Comment by giovannipizzi** [comment]
I think this is not (necessarily) a problem in AiiDA, and actually I think it is not easy to solve from the AiiDA side.

The problem occurred after our PR to enforce the loading of a "login shell" over SSH. Before, this was not the case and only .bashrc was loaded, now .bash_profile is loaded.

I think the right solution is to "guard" the calls in the .bash_profile that act on output (produce output, work with the terminal) with proper checks to run only if you are in an interactive shell.

Ubuntu for instance does it by default at the beginning of .bashrc, and this should be done also in .bash_profile.

The correct way to put a `clear` is therefore:
```bash
case $- in
    *i*)
       clear;;
esac
```

Note that putting things that produce output e.g. in the .bashrc is in general a problem also for other codes, e.g. sftp.
For instance, if I add a `echo A` at the top of my .bashrc, and then I run 
```
sftp localhost:Desktop/fname.txt .
```
I obtain the following error:
```
Received message too long 1091174400
```
while with the guard I describe above this does not happen (and still, if one logins interactively, clear is run).

So my suggestion to close this issue is to document this and explain what is the "correct" way of doing this.
@espenfl would you be willing to push a PR for the docs?

**Comment by espenfl** [comment]
Thanks for you comments. Yes, sure, this is not related to Aiida at all, but makes Aiida choke unless the users take the correct measure. The problem is when issuing a login shell for non-interactive ssh. The default behavior (on most) systems is to just load `.bashrc` (in which you should be careful to put stuff...most users do not). In `.bash_profile` many users have checks, tests or something that informs them of something important (or even a simple clear in order not to fuss with to many `/dev/null` pipes). Quite typical in cluster environments, particularly if you are a developer.

Since we force non-standard behavior we should document. I can submit a PR on the docs when time permits. Let us close the issue when the PR is accepted.

**Comment by giovannipizzi** [comment]
I will write the docs now.

@ltalirz : do we really need to have a login shell (see #1502)?

I think there are two things achieved in that PR:
1. to always use bash as a shell (good)
2. to always use a login shell
From Espen's comment, it might not be the best choice to do it - a careful user could differentiate between the two.

At the moment anyway I will say that we don't support printing in the bash_profile.

**Comment by ltalirz** [comment]
> do we really need to have a login shell (see #1502)?

It was convenient for the Quantum Mobile, and it might be what novice users expect - in the sense  "when I log into my cluster and do X it works, but when I configure AiiDA to do X, it doesn't work".

I didn't realize, however, that non-interactive login shells are rather unusual (agrees with this [SE post](https://unix.stackexchange.com/a/46856) ).
To me, this makes it a decision between the benefit (imagined, I admit) for novice users and the benefit of standard compliance.

I'm not leaning strongly in either direction.

**Comment by giovannipizzi** [comment]
I'm writing the docs now. 
I suggest, then, to keep the call to bash, but removing the `-l` option. As this is also implemented for local transports, this might also solve #1887 
Are you ok with this?

**Comment by ltalirz** [comment]
No real objections from my side.
My only request would be to make this change both in 0.12 and in develop to be consistent.

Note to self: need to check that Quantum Mobile setup still works.

**Comment by giovannipizzi** [comment]
Thinking better about this, though, and discussing with @dev-zero, we are thinking to keep the `-l` (login shell).
The idea is that we had experience in the past of users getting confused by having a different environment (often the $PATH) for interactive and non-interactive. Actually even some supercomputer centres have this issue with e.g. `qstat` and similar (these are the user issues I remember).

On the other hand if the user is advanced enough to have changed the shell, he will know how to change it to add the guard described above (if correctly pointed to by the docs).

The only edge case I see is if the computer admins put something weird that prints and is not guarded in the global profile, but then they could have done the same with the .bashrc, and users will then ask admins to fix this.

Finally: what I realized that I can do is to add an additional test in `verdi computer test` to check if there is any problem and stop, in that case.

As a final suggestion from @dev-zero (for the future): one could always print a special string before executing any command, and then in the output take the `.rpartition()[2]` of that. We need though to check carefully that indeed that string is very rare to be found in a typical extraneous output.

Another option that has been discussed with @dev-zero and @ltalirz (but complex to implement) is to follow the approach of ansible, that first pushes a python script on the server, and then interacts through it.

**Comment by giovannipizzi** [comment]
As suggested by @dev-zero in #2132, more often the guard looks like:
```bash
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi
```
