### ISSUE TITLE
codecov omits files with same name, shows wrong data

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#1905]
Codecov seems to have a problem with files with the same name but in different packages/directories.

Example: `utils.py`. While the coverage report is there for `aiida/plugins/utils.py`, the files `aiida/common/utils.py` and `aiida/work/utils.py` are completely omitted.

The same goes for the `__init__.py` files and possibly others, see also
* codecov/codecov-python#136
* codecov/codecov-python#125

Furthermore, there is also a mismatch of the data. Take https://codecov.io/gh/aiidateam/aiida_core/src/develop/aiida/common/archive.py#L130 as an example: while the function itself is called twice, its body seems to be completely uncovered.

**Comment by giovannipizzi** [comment]
That might explain the random numbers we were seeing!! :-) Is this fixed by #1907?

**Comment by dev-zero** [comment]
Sorry, I should have been more clear why I opened this bug.
Unfortunately there is not much we can do as far as I've seen, as long as we haven't done anything wrong in setting up the coverage. The error is really on the server side of codecov.io. The only thing we could do is to switch to Coveralls instead or ignore it.
I've sent the Codecov support team an email today, but I'm not very confident that we're going to hear anything from them, given that their Slack chat is unreachable and you get an out-of-office reply from their COO when using the official contact address.
So, I opened this bug to start a discussion: should we wait, turn it off completely, or switch to Coveralls?
Maybe someone could add the Coveralls app to the aiidateam project to try it out?

**Comment by giovannipizzi** [comment]
I don't have any specific preference so I'm ok to use Coveralls if it is better.
There is a 'Coveralls Pro' already registered among the "settings->Third party access" section (I don't know who put it there), is this enough/the correct one?

Also, do you know if the coverage on Jenkins is more correct? 
See e.g. the first accordion named "shell script" here: https://theossrv6.epfl.ch/jenkins/blue/organizations/jenkins/aiida_core_aiidateam/detail/PR-1872/14/pipeline
(this should sum the coverage of both Django and SQLA, that is possible on Jenkins as they both run in the same "virtual machine", I'm not sure what is done by Codecov and if it sums the coverages of the different tests).

**Comment by ltalirz** [comment]
> There is a 'Coveralls Pro' already registered among the "settings->Third party access" section (I don't know who put it there)

I believe Rico set it up for `aiida-vasp`. By the way, coveralls is now included by default for plugins created by the AiiDA plugin cutter, see https://github.com/aiidateam/aiida-diff

do they also have a way of adding the results directly to a PR?

**Comment by giovannipizzi** [comment]
I think we still have a few fixes to do.
For instance, here https://github.com/aiidateam/aiida_core/pull/1964#issuecomment-422218445 it says that the coverage went down for a number of files.
I think the reason is that it picks only the last report it gets from the Travis CI build matrix, whatever ends last. So e.g. it will keep complaining that some parts of sqlalchemy vs. Django are not tested.

Maybe there is a simple way to fix this, see this: https://docs.coveralls.io/parallel-build-webhook

**Comment by giovannipizzi** [comment]
Also, what is quite annoying now is that when coveralls decides (sometimes by mistake, see above) that the coverage went down too much, it will mark the PR as failed (one can still merge as it's not required to pass, but looking at the list of PRs, many seem failed even if they are not).

**Comment by sphuber** [comment]
Even though there are still multiple messages coming in from Coveralls, one for each finishing build, eventually the cumulative status will be updated. So even if it at first fails, when just one build has finished and the coverage appears to have gone down, later it should be updated to a check mark once the other builds have finished as well. So although not ideal, it is workable
