### ISSUE TITLE
Quicksetup / control.postgres improvements

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#1910]
## determine setup
- [ ] look for a dbuser in the config file. if found try first to connect through psycopg2 with that user and password

## environment creation process
- [ ] after creating the dbuser, the connection type should be switched to psychopg2 and database creation should happen through that. This way if the dbuser password is wrong or unknown (perhaps because that dbuser existed already in another aiida config file or outside aiida), the profile does not get created in the first place.

## other related
- [x] migration of the config format from 0.12.1 to 1.0.0aX should not invalidate saved postgres db user passwords

**Comment by ltalirz** [comment]
> look for a dbuser in the config file. if found try first to connect through psycopg2 with that user and password

We can try that but as far as I understand in most cases this won't help, since the user created by `verdi quicksetup` and the one created when following the documentation does not have the privilege to create new databases.

**Comment by ltalirz** [comment]
> after creating the dbuser, the connection type should be switched to psychopg2 and database creation should happen through that. This way if the dbuser password is wrong or unknown (perhaps because that dbuser existed already in another aiida config file or outside aiida), the profile does not get created in the first place.

I don't think this makes much sense either, since the aiida DB user doesn't have the privilege to create databases. 
See "manual" attempt of this on ubuntu 18.04 below:
```
(aiida) max@workhorse:~$ sudo su postgres
[sudo] password for max:
postgres@workhorse:/home/max$ psql
psql (10.7 (Ubuntu 10.7-0ubuntu0.18.04.1))
Type "help" for help.

postgres=# CREATE USER myuser WITH PASSWORD 'testpw';
CREATE ROLE

postgres=# create database testdb1 owner myuser;
CREATE DATABASE

postgres=# \q

postgres@workhorse:/home/max$ psql -U myuser -d testdb1 -h localhost -W
Password for user myuser:
psql (10.7 (Ubuntu 10.7-0ubuntu0.18.04.1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

testing2=> CREATE DATABASE testdb2 OWNER myuser;
ERROR:  permission denied to create database
testing2=>
```
@giovannipizzi do you agree?
If yes, we can close this.

**Comment by giovannipizzi** [comment]
agreed
