### ISSUE TITLE
Batch scheduler updates

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#1913]
In the new system for each job process a request is made for transport and each job separately calls the scheduler update command to get the current status of the job.  This can lead to a lot of calls to the update command which is not appreciated by certain supercomputing centres.

A possible solution is to have a central point for updating the job status which queries all jobs on a particular computer and caches them.  This still means that separate workers will each do their own updates but at least this should lead to a significant reduction in the number of update calls.

**Comment by muhrin** [comment]
This is being worked on in #1929

**Comment by sphuber** [comment]
Fixed in #1929
