### ISSUE TITLE
PyCifRW broken with Python 3

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#1931]
The currently used version of PyCifRW, 4.2.1 does not work with Python 3.
Version 4.4 [breaks Python 2](https://bitbucket.org/jamesrhester/pycifrw/issues/14/pycifrw-44-fails-with-python-27-and-long) and I haven't figured out a way to monkey-patch it.

**Comment by dev-zero** [comment]
unfortunately upstream wanted to have some more fixes in for a new release: https://bitbucket.org/jamesrhester/pycifrw/issues/17/new-release-for-improved-python-2-and-3

We can solve this for the moment by using Python-dependent dependencies since the PyCifRW API doesn't seem to have changed.

**Comment by merkys** [comment]
Fixed in #2092.
