### ISSUE TITLE
(COD) DB Import/Export broken with Python 3

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#1932]
The main reason for this is the improper handling of `bytes` vs. `str`. Unfortunately there seem to be some general problems hidden in there (which may also effect Python 2). Examples:

* missing default encoding when writing/reading files which may break under different system encoding and/or when changing the default system encoding between save&load. Also, some tests start failing when running with Japanese or Chinese locale.
* including file contents as strings in JSON files without prior base64 encoding which could introduce subtle bugs and differences (for example in hashing or due to double encoding).

**Comment by giovannipizzi** [comment]
Fixed in #2092
