### ISSUE TITLE
Consider to make _AbstractNodeMeta public

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#1949]
In the VASP plugin we previously utilized `JobCalculation.__metaclass__`. With the recent changes with `six.add_metaclass` we had to change this and go to the source (thanks Tiziano), which is `_AbstractNodeMeta`. We can utilize this and functionality is back. However, if we are going to continue to use this, it makes sense that it is made public in `aiida_core`. Or, is there another solution?

**Comment by giovannipizzi** [comment]
@espenfl could you link a snippet of the code where you need to use this, and explain why you are trying to access that meta class? This should be AiiDA internals and hopefully nobody should need to directly access it from a plugin.
So we understand if there is a different way to do this or if we need to add some functionality exposed to plugins that achieves your goal.

**Comment by espenfl** [comment]
Check out `calcs.base`. We override the `__new__` such that we can do:

```
@six.add_metaclass(CalcMeta)                                                                                                                                                                                 
        MyCalculation(JobCalculation):                                                                                                                                           
            potential = Input(types='vasp.potcar', param='kind')                                                                                                                                                     
                                                                                                                                                                                                                     
        my_calc = MyCalculation                                                                                                                                                                                      
        potential = load_node(...)                                                                                                                                                                                   
        my_calc.use_potential(potential, kind='Someelement')
```
This was done before I was involved, but I quite like it.

**Comment by sphuber** [comment]
@espenfl please let us know if with the changes brought in `aiida-core==1.0.0b1` you still need the concept of the abstract meta or if you can accomplish it in other better ways

**Comment by espenfl** [comment]
No, this is no longer needed as the meta class stuff emulated the new behavior. It is now all gone, so please close this. Thanks.
