### ISSUE TITLE
Invocation of `verdi computer configure` after `verdi computer setup` broken

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#1975]
After a recent change, the user is now prompted to directly continue to configuring a newly setup computer. The invocation of `verdi computer configure` on typing yes seems to work, as a message is printed that the computer is configured, but the user is never actually prompted and in fact, the computer is not configured at all.

**Comment by ltalirz** [comment]
There are two problems

 1. the invocation of `verdi computer configure` does not prompt
 2. The function 
https://github.com/aiidateam/aiida_core/blob/9ec944564bc7e4c2af58b17f0711d1c25be8b4b6/aiida/control/computer.py#L8
only validates whether it receives valid parameter names, not whether the values of the parameters are valid.

**Comment by ltalirz** [comment]
Problem 1 is simply the default behavior of click for invoking commands.
I've opened an issue https://github.com/pallets/click/issues/1124 to ask how to proceed.

**Comment by sphuber** [comment]
A related issue is how callbacks of commands are not triggered when it is invoked from another command: https://github.com/pallets/click/issues/950

**Comment by ltalirz** [comment]
For reference, they have decided that this is the intended behavior of click, i.e. if you `invoke` a command, you are supposed to pass the already processed option values and the invoked command will not prompt
https://github.com/pallets/click/issues/1124#issuecomment-653238970
