### ISSUE TITLE
Syntax Error: 'await' is a reserved word in Python >= 3.7

### ISSUE THREAD

**Issue by cclauss** [aiidateam/aiida_core#1994]
[flake8](http://flake8.pycqa.org) testing of https://github.com/aiidateam/aiida_core on Python 3.7.0  -- Discovered via #1992

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./aiida/work/rmq.py:375:32: E999 SyntaxError: invalid syntax
        self._communicator.await(action, timeout=self.timeout)
                               ^
./aiida/cmdline/commands/cmd_calculation.py:374:54: E999 SyntaxError: invalid syntax
            result = control_panel._communicator.await(future[1])
                                                     ^
./aiida/cmdline/commands/cmd_work.py:315:26: E999 SyntaxError: invalid syntax
        communicator.await()
                         ^
./aiida/cmdline/commands/cmd_process.py:163:26: E999 SyntaxError: invalid syntax
        communicator.await()
                         ^
4     E999 SyntaxError: invalid syntax
4
```

**Comment by sphuber** [comment]
These are methods defined by the [kiwipy](https://github.com/muhrin/kiwipy) library and should be fixed there

**Comment by cclauss** [comment]
Kiwipy has done __async__ —> __wait_for__

https://github.com/muhrin/kiwipy/issues/2#issuecomment-42558742

8https://github.com/muhrin/kiwipy/blob/8c27f94f8b2e346641e7bbed7ec31c40a04f5857/kiwipy/rmq/communicator.py#L537

**Comment by sphuber** [comment]
We are underway to releasing a new `kiwipy` and adapting `aiida-core` to the api changes.
