### ISSUE TITLE
provide aiida plugin linter for transition to aiida-core 1.0

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#1999]
Since there will be a number of (minor) changes to the API when we move to aiida-core v1.0, it would be very helpful for plugin developers if we provided a lightweight linter helps pinpointing where these changes need to be made.

I've started this (so far just playing around with pylint, not yet intended for actual use)
https://github.com/ltalirz/aiida-plugin-linter

The next steps would be to
 - [x] have a list of changes to the API (here I would like some help)
 - [x] implement them in the linter (I will work on this on and off)
 - [x] finally, test the linter on an actual plugin

Once the linter is actually useful, it can be moved to the aiidateam github org.

@sphuber I remember you showed me a list of changes at some point but I wasn't able to find them again in the documentation. Could you please point me to them?

**Comment by sphuber** [comment]
Workflow related changes [can be found here](https://aiida-core.readthedocs.io/en/latest/concepts/workflows.html#upgrading-workchains-from-pre-v1-0-0) and generic changes will be [in the usual place](https://aiida-core.readthedocs.io/en/latest/install/updating_installation.html#version-migration-instructions)

**Comment by giovannipizzi** [comment]
what about providing automatic refactoring scripts? e.g. https://pybowler.io seems quite nice (it's developed by Facebook)

**Comment by ltalirz** [comment]
all for it, just needs to be actually done

**Comment by ltalirz** [comment]
Here it is! 
https://github.com/aiidateam/aiida-plugin-migrator
