### ISSUE TITLE
Define standard encoding for repository data & locale for database

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#2011]
Most likely all systems currently running AiiDA are using `utf8` encoding and both the database locale as well as the written files therefore use `utf8`. Nevertheless, there might be some who have either a CJK-locale like `EUC-JP` or working on an old system with `latin1`-style default encoding.

What we have to do (I did not check whether some of the points are already implemented):

* Define the encoding we want to use for storing text files in the repository. We can continue to use the default system encoding and let Python automatically convert to `utf8` strings when using `read()/readlines()`, resp. convert to the file encoding when using `write()` (for free in Python 3, needs `io.open()` in Python 2). When copying files from/to remotes we might have to do conversion between encodings. To  ensure that the files will still be readable when someone copies a repository to a different system, we have to store the encoding of the file in the database. The advantage is that someone could simply look at the text files in the repositories and see the correct content. The other option would be to enforce `utf8` on all the files with the drawback that if someone directly looks at the file and has a default system encoding other than `utf8`, he might see garbage. **this part is tracked in #2047 (respectively #2046)**
* Determine the remote locale when fetching a remotely generated file and either save the remote locale in the metadata or convert the file to the repository locale.
* For the database, we have a similar issue: the user could on one hand choose a different encoding, which in Python 3 should not matter since strings are automatically `utf8`. The problem with the database might be the locale which could for example change the order of entries when sorting.
* When exporting data: the generated files and metadata should probably be always `utf8` encoded to avoid that the recipient of the exported data has to run locale-detection on them.
* Hashing got its own item at #2009 but it might be important to note that hashing for all files is currently done on the byte-content of a file, meaning that the some string stored twice with different encoding will generate two different hashes for the different files.

I would also like to stress that I'm not an expert on locales or encoding, only have some experience with it from Linux system engineering, so if there is an expert on this matter: please share your thoughts!

After the last discussion, what has to be done here:

- [x] decide whether we want to enforce `utf8` on the client side and if yes, how to do that with Django and SQLA
- [x] check Django behaviour if client and server encodings differ and what kind of string we get in Python 2 if we enforce the encoding to `utf8`
- [x] check SQLA behaviour if client and server encodings differ and what kind of string we get in Python 2 if we enforce the encoding to `utf8`
- [x] add a check to AiiDA to make sure the database was initialized with some kind of multi-byte encoding (possibly even just `UTF8` when looking at https://www.postgresql.org/docs/9.6/static/multibyte.html)

**Comment by giovannipizzi** [comment]
For the DB: I think PsycoPG allows to specify the client encoding (https://stackoverflow.com/questions/43583285/python-psycopg2-not-in-utf-8) and we need to check how to this from Django and SQLA. We maybe want to check that the DB encoding is able to encode anything that can be encoded by UTF8

**Comment by szoupanos** [comment]
Locale support information for PostgreSQL
https://www.postgresql.org/docs/current/static/locale.html

It seems that the locale can be defined per database

**Comment by szoupanos** [comment]
Regarding SQLA, the encoding is defined when creating an engine
https://docs.sqlalchemy.org/en/latest/core/engines.html#engine-creation-api
As the SQLA documentation says: This defaults to utf-8 and it is the string encoding used by SQLAlchemy for string encode/decode operations which occur within SQLAlchemy, outside of the DBAPI.

In aiida this is defined at aiida/backends/sqlalchemy/utils.py (reset_session method)

**Comment by szoupanos** [comment]
Django's doc on unicode
https://docs.djangoproject.com/en/2.1/ref/unicode/

**Comment by szoupanos** [comment]
This is a summary of what I tested today and my comments. Overall, I believe that there is no problem with setting the encoding explicitly to UTF-8 and no problems (at the test level) seem to appear if another encoding is used.

I can try to run some calculations tomorrow too.

> - Python 3
>     - Django
>         - implicit utf8 encoding - used until today (prof: test_dj_p3)
>             - Tests failed:  3  /  Tests errored: 9
>         - korean db encoding (prof: test_dj_kr_p3) 
>                 - ENCODING 'EUC_KR' LC_COLLATE='ko_KR.euckr' LC_CTYPE='ko_KR.euckr'
>             - verdi setup with a database with korean encoding works well
>             - The same tests fail
>                 - However it seems after this execution more tests fail and the terminal doesn’t work as expected
>                     - After the restart of the VM everything came back to normal
>                     - The problem seems at the terminal. After closing all the terminals, reconnecting and launching the tests the correct amount of tests failed
>                     - A second execution also worked well (the terminal was left at a good condition from the previous test execution - no problem with the enter - the appearance of the problem should depend on the test order)
>                     - Again even with the terminal problem the tests ran as expected
>                     - The terminal problem doesn’t seem to be related with the korean encoding
>         - (explicit) utf-8 db encoding
>                 - ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' 
>             - verdi setup works well
>             - Tests failed:  3  /  Tests errored: 9
>     - SQLA
>         - implicit utf8 encoding - used until today (prof: test_sqla_p3)
>             - Tests failed:  3  /  Tests errored: 9
>         - korean db encoding (prof: test_sqla_kr_p3)
>                 - ENCODING 'EUC_KR' LC_COLLATE='ko_KR.euckr' LC_CTYPE='ko_KR.euckr'
>             - verdi setup with a database with korean encoding works well
>             - Same number of tests fail/error
>                 - they leave the DB at an inconsistent state - it seems to happen the same with the explicit utf8 database
>         - (explicit) utf-8 db encoding
>                 - ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' 
>             - verdi setup works well
>             - Tests failed:  3  /  Tests errored: 9
>                 - very common to have more tests failing

**Comment by szoupanos** [comment]
The database encoding was addressed at pull request #2115.
I will create a separate one for the encoding of the import/export data.

**Comment by sphuber** [comment]
With the fix in #2115 and #2047 this can be closed
