### ISSUE TITLE
Prevent two profiles with same UUID

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#2064]
If a user creates two profiles with the same UUID but different databases there will crosstalk in the RMQ communication meaning that tasks, broadcasts, etc will be picked up by the wrong daemon.  This is because AiiAD uses the UUID as a means of identifying the profile.

One way to fix the most probably way for this to arise is to check the profile when it is read to make sure there are no duplicate profile UUIDs.

Spawned from #1218.

**Comment by giovannipizzi** [comment]
I think that since the profile settings could be stored in different config.json files (using the AIIDA_PATH) I'm not sure this check is really useful... I'd rather fix is as discussed in #182

**Comment by giovannipizzi** [comment]
Closing in favour of #182
