### ISSUE TITLE
ORM interface to create Unique Partial Indexes

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#2072]
Certain data objects should be unique, like pseudopotentials and basis sets.
Without unique indexes, there is no way to ensure this without race conditions.

It would therefore be nice to have an interface to define a partial unique index, something like:

```python
from aiida.orm.data import Data

class MyDataClass(Data):
    unique_attributes = ('element', 'id, 'version')
```

which gets turned into something like:

```sql
CREATE UNIQUE INDEX IF NOT EXISTS my_data_class_unique_attributes
    ON db_dbnode ((attributes->>'element'), (attributes->>'id'), (attributes->>'version'))
    WHERE type = "data.MyDataClass";
```

SQLA directly supports [indexes](https://docs.sqlalchemy.org/en/latest/core/constraints.html#indexes), not sure about Django.

**Comment by giovannipizzi** [comment]
It's a good suggestion, but it's not obvious how to expose DB schema changes to the user without big headaches (e.g. when dealing at the same time with AiiDA-defined migrations).
This is something that requires more discussion (probably the easiest approach is to do just some checks in python, and if you need unique values and if you find multiple hits, you complain when checking this.

**Comment by giovannipizzi** [comment]
Actually, thinking better to this, I think we *should not* allow to define these conditions on the data content, but we only AiiDA should allow for unique indices for things that are defined.

The reason why I'm now thinking that it's not a good idea to put user-defined constraints is the following:
- user A has a valid DB
- user B has also a valid DB and exports his data
- user A imports the data from B, but now the new data violates a user constraints
Then user A is confused and does not know what to do, and cannot import the data from B at all.

I.e., there is no way for AiiDA to deduplicate the data automatically in a safe way.
I think instead the importer will work, and if you really need this data to be unique, when you query you will get two and the python code will complain (one can put in place ways to improve this, e.g. for UPF we only look for uniqueness within a group and not globally in the DB).

So I think for now this is a 'wontfix'. Feel free to further comment or even reopen if needed.
