### ISSUE TITLE
Jinja templates not installed in current develop branch

### ISSUE THREAD

**Issue by bonfus** [aiidateam/aiida_core#2077]
I need to use the development version of AiiDA (in order to install the most recent QE plugin). I installed it with the following command:

    pip install git+https://github.com/aiidateam/aiida_core.git

but I had to add the Jinja templates in `aiida_core/aiida/cmdline/templates/` manually.

Have these files sneaked out of setup.py or is just the install method that is not supported?

**Comment by sphuber** [comment]
They have not been included in the `MANIFEST.in` and so they will not be included in the PyPI package. I will put out a PR with the fix. Thanks @bonfus for the report
