### ISSUE TITLE
Make proecss pause/play/kill fire and forget

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#2082]
Currently if a process is running and, say, waiting for transport if one of the process commands is sent (pause/play/kill) it will time out if the process doesn't respond it time.  However, the request will still be scheduled and actioned when the event loop gets a chance.

Steps to reproduce:

1. Start a long running calculation on a computer that uses SSH transport (so that there is some time between transport requests being granted)
2. Fire off a `verdi process pause [pid]`
3. You should get an `Error: call to pause Process<[pid]> timed out` message
4 Now wait for the SSH request time, usually 30 seconds, and the process should enter the paused state as seen in `verdi process list -p1`

Expected behaviour:

By default `verdi process pause` should fire off the request for pausing and not wait for it to be done.  Optionally we can add a 'wait' flag to retain the current behaviour.  In either case it should be idempotent such that it can be called multiple times and will function correctly even if the process is already paused.

**Comment by sphuber** [comment]
Fixed in PR #2158 in commit [3b80c0a](https://github.com/aiidateam/aiida_core/pull/2095/commits/3b80c0aa64e69e0b6213a56e563e54de023ebf1b)
