### ISSUE TITLE
add version parser to aiida core utils

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2096]
This piece of code to parse the aiida version will be useful for any plugin that supports both aiida 0.12 and 1.0.

https://github.com/aiida-vasp/aiida-vasp/blob/268e2a41c96d8fda229937dd3c6f828853acb503/aiida_vasp/utils/aiida_utils.py#L127-L133

I suggest to add this in aiida/utils, both in `release_0.12.3` and in `develop`

@giovannipizzi @sphuber Do you agree?

**Comment by ltalirz** [comment]
Ok, I think this is already sufficiently covered by `aiida.get_strict_version()`

**Comment by ltalirz** [comment]
Actually, this function is missing from the 0.12.3 branch.
I will add it.

**Comment by sphuber** [comment]
Fixed in `release_v0.12.3` in PR #2099
