### ISSUE TITLE
Some tests are still skipped in py3

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2118]
See the insertion of skipping in this commit:
https://github.com/aiidateam/aiida_core/commit/f8993031ee17a9597339d6d0f81ecef2facb2b49

**Comment by merkys** [comment]
There are no tests skipped due to Python 3 in ``aiida/backends/tests/tcodexporter.py`` on ``develop``. Are you sure you are looking at ``develop``?

**Comment by giovannipizzi** [comment]
You're right, there was a problem in a merge in a different branch, sorry about the noise
