### ISSUE TITLE
Invalidate hashes in a migration now that the hashing algorithm changed

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2131]
To decide if we want first to write the tests for #2124 to check if the hashing is now doing the correct thing (currently: gets the values in memory, calls through clean_value, and then hashes and stores. This would give the same result as hashing again after reading back from the DB/deserializing, only if clean_value does what the serialisation would also do [i.e. if I have e.g. numpy arrays, clean_value converts them to lists, and if I serialise and deserialise, this should give me the same result as right after clean_value).

**Comment by sphuber** [comment]
Fixed in PR #2136
