### ISSUE TITLE
Dummy_model makes maintenance very difficult

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#2138]
Currently from what I understand QueryBuilder for Django uses a set of dummy models stored in `dmmy_model.py` to perform queries using the SQLA engine.

This is a maintenace nightmare because anyone that does a migration or wants to add support for a new model type to `QueryBuilder` has to make sure to update this file as well.  This is a good example of the problems of violating the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle.

My recommendation would be to either:

- remove this file and find another way, or,
- create a scrip that can automatically generate `dummy_model.py` from the current models

**Comment by giovannipizzi** [comment]
As a note: give a look to [aldjemy](https://github.com/Deepwalker/aldjemy) before writing our own scripts. I think @lekah checked it already but I don't remember if there were issues with it.

**Comment by lekah** [comment]
Yes, I tried aldjemy and it didn't work back then. Maybe it works now, I don't know. I know it's not ideal, but it was the only thing that does the job, dry or wet. The plan was also to not have more migrations with Django and switch to SQLAlchemy. I can't fix that in the near future, if it's important someone else needs to be assigned and do it.

**Comment by giovannipizzi** [comment]
Putting this to 1.1.0, even if probably @szoupanos already has a fix for this using aldjemy in his branch (in which case this will be closed once merged)

**Comment by szoupanos** [comment]
For the moment using Aldjemy is not very easy for the old Django model because of attributes and extras EAV of the DBNode table. It seems (from a first look) much easier if we move to JSONB

**Comment by szoupanos** [comment]
This is linked to issue #2299

**Comment by szoupanos** [comment]
The dummy model was removed from the Django JSONB and aldjemy was used that it creates automatically an SQLA schema given the Django schema. 

This is solved in branch aiida/django_jsonb
https://github.com/aiidateam/aiida_core/tree/django_jsonb
