### ISSUE TITLE
replace json implementations with simplejson

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#2142]
Following the discussion on #2107 I would like to discuss whether or not we should switch the currently used JSON implementations (both the one bundled with Python and ujson) to simplejson.

PR #2107 has shown that the Python built-in `json.dump`, respectively `json.dumps` does not have consistent interface between Python 2 and 3: `json.dumps(..., ensure_ascii=False)` only returns a unicode string iff it got unicode data in the first place, while writing to a `io.open(..., encoding="utf8")` opened file seems to always expect a unicode string.

While we could write a wrapper, the other solution would be to use `simplejson` which seems to exhibit a consistent API: `json.dumps` always returns a unicode string if `ensure_ascii=False`.

At the same time could we replace the unmaintained `ujson` library with `simplejson` instead.

The `anyjson` library which is still referenced in `setup_requirements.py` does not seem to be used anywhere (anymore) and given the list of bugs for `ujson` it seems that we do not want this kind of run-time switching for json libraries anyway.

**Comment by ConradJohnston** [comment]
Hi @dev-zero , 

We discussed it here and propose to make simplejson an optional dependency. Then, me make a json utility function which either uses simplejson, if available, or alternatively invokes regular json in the correct way for the version of Python installed.

**Comment by dev-zero** [comment]
@ConradJohnston ok, can you elaborate on the reason for supporting both options? Doesn't that mean we have to test both cases and that it is harder to reproduce should errors at the user side occur since we first have to figure out which implementation was used?

**Comment by ConradJohnston** [comment]
@dev-zero , I believe it was to avoid growing the list of dependencies, but I agree that testing both is tedious. 
I'll invite @giovannipizzi  and @sphuber  to comment.

**Comment by sphuber** [comment]
I understand the goal to try and limit the number of dependencies, but in this case I think the cost of not adding it does outweighs the benefits, so I would be in favor of adding the dependency. In reality, we are replacing it and getting rid of two others. It is available on conda-forge as well as far as I could tell, so that box is also ticked.

**Comment by ConradJohnston** [comment]
Ok, let's do the simple(json) thing. then.

**Comment by ConradJohnston** [comment]
Looking closer, the behaviour of simplejson seems to be the same as regular json, so I don't see it reducing the amount of spagetti.

**Comment by dev-zero** [comment]
@ConradJohnston what I tested is:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import io
import six

import simplejson as json
#import json

d_unicode = {'b': u'γεια σας'}

json_str = json.dumps(d_unicode, ensure_ascii=False)
print(type(json_str), json_str)

with io.open('/tmp/test..unicodedat', 'w', encoding='utf8') as dest_file:
    dest_file.write(json_str)
    
d_ascii = {'b': "something without a 'normal' string"}
json_str = json.dumps(d_ascii, ensure_ascii=False)
print(type(json_str), json_str)

with io.open('/tmp/test.normal.dat', 'w', encoding='utf8') as dest_file:
    dest_file.write(json_str)
```

works with simplejson, fails with built-in json.

**Comment by ConradJohnston** [comment]
Yes, I notice that dumps is more consistent in simplejson.
Will add a new commit to the PR shortly.
