### ISSUE TITLE
Transport task fails to copy files completely

### ISSUE THREAD

**Issue by Tseplyaev** [aiidateam/aiida_core#2163]
A transport task seems to fail to copy the full files from a job calculation. AiiDA only copied back part of the files from the directory where the calculation was executed to the repository (both on the same local machine).  The files are not large (<1.4 MB). It is reproducible and always copies the file to the same line only for this system.

daemon log says the transport was successful, but the out.xml, out and other files are cut off:

``` 
11/08/2018 03:12:02 PM <44393> aiida.execmanager: [DEBUG] [retrieval of calc 478] chdir /Users/tsep/Documents/workaiida/73/0f/d90b-bd25-4a7c-b6d5-052a80b67f21
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item 'out.xml'
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item 'inp.xml'
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item 'shell.out'
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item 'out.error'
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item 'out'
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item 'cdn1'
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item '_scheduler-stdout.txt'
11/08/2018 03:12:03 PM <44393> aiida.transport.LocalTransport: [DEBUG] [retrieval of calc 478] Trying to retrieve remote item '_scheduler-stderr.txt'
11/08/2018 03:12:03 PM <44393> aiida.execmanager: [DEBUG] [retrieval of calc 478] Storing retrieved_files=None
11/08/2018 03:12:03 PM <44393> aiida.work.transports: [DEBUG] Transport request closing transport for 
```

files in calculation folder.
```
-rw-r--r--  1 tsep  staff     0B Nov  8 10:50 _scheduler-stderr.txt
-rw-r--r--  1 tsep  staff     0B Nov  8 10:50 _scheduler-stdout.txt
-rw-r--r--  1 tsep  staff    88K Nov  8 10:51 cdn1
-rw-r--r--  1 tsep  staff    12K Nov  8 10:50 inp.xml
-rw-r--r--  1 tsep  staff   975K Nov  8 10:51 out
-rw-r--r--  1 tsep  staff   145B Nov  8 10:51 out.error
-rw-r--r--  1 tsep  staff   1.4M Nov  8 10:51 out.xml
-rw-r--r--  1 tsep  staff    68K Nov  8 10:51 shell.out
```

files partially copied to the repo
```
-rw-rw----  1 tsep  staff     0B Nov  8 10:50 _scheduler-stderr.txt
-rw-rw----  1 tsep  staff     0B Nov  8 10:50 _scheduler-stdout.txt
-rw-rw----  1 tsep  staff    88K Nov  8 10:50 cdn1
-rw-rw----  1 tsep  staff    12K Nov  8 10:50 inp.xml
-rw-rw----  1 tsep  staff   243K Nov  8 10:50 out
-rw-rw----  1 tsep  staff     0B Nov  8 10:50 out.error
-rw-rw----  1 tsep  staff   358K Nov  8 10:50 out.xml
-rw-rw----  1 tsep  staff    16K Nov  8 10:50 shell.out
```

I use AiiDA develop branch (commit d4d327), Django backend, with RMQ. Running a Fleur scf workchain.
How can I fix this? Can it be that the problem is related to #1748?

**Comment by sphuber** [comment]
This is really weird. It is good that you ran with debug log level and what we see is that the engine is using the transport to retrieve all the files from the retrieve list and it finishes this without exceptions. It just seems that apparently for certain files the transport operation stops halfway. Without more information, I have no clue what is going on, but I am pretty sure it is not related to #1748 . I am not sure what we could test more to figure out why the files are not fully retrieved. Could you maybe run the same calculation on a different machine, ideally over ssh, to see if that works. Or run a completely different calculation from another plugin, if you have that at your disposal.

**Comment by sphuber** [comment]
Could you maybe attach the `shell.out` and `out.xml` files from both folders? This way we can see if it really is just cut off at a certain point or the output is garbled.

**Comment by Tseplyaev** [comment]
I will try running the same calculation on a different machine, I hope it will help.

As further tests showed, files are not always copied to the same line. When I run a workchain which submits 3 parallel scf calculations, all of `out.xml` files are cut off to the different line (it depends, more often files are cut off to the same line). However, when the similar workchain submits only 1 scf calculation, the only `out.xml` is cut off to the lower line i.e. a bigger part of the output file is retrieved. Moreover, when I run a single scf calculation just after daemon restart `out.xml` is cut off at the lower line than if daemon was not restarted.

You can find the original `shell.out`, `out.xml` and their retrieved versions `shell_retr.out` and `out_retr.xml` in the attachment. 
[outputs.zip](https://github.com/aiidateam/aiida_core/files/2571318/outputs.zip)

**Comment by Tseplyaev** [comment]
I tried running the calculations on a cluster over ssh, it worked. All output files were successfully retrieved and parsed. There is definitely an issue with my laptop (mac).
