### ISSUE TITLE
Process interface: adapt `workfunction` decorator to new design

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2171]
Ensure that the nodes generated by functions decorated with `workfunction` get the correct node class `WorkFunctionNode`, which will be defined and refactored everywhere in #2169.
After that, make sure that it only creates `RETURN` links.
Should we warn or raise, when a user returns a node from the function that was created in that function? Since it will only get a `RETURN` link, it won't have an explicit creator. Note that this is not necessarily inconsistent, because it is perfectly fine to pass in a node as input that was created in a shell, and so does not have an explicit creator, and to return that from the workfunction. However, for the intended behavior the user should really use a `calcfunction` which would get a proper `CREATE` link. Perhaps we should therefore not allow it

**Comment by giovannipizzi** [comment]
I think that if the node is returned unstored, we should raise (but explaining in detail what is the suggestion - replace with a calcfunction, or use a calcfunction internally).

If the user calls .store() and then returns, probably we can't do much? (and as you say, it's probably ok to e.g. return a UPF that is in the DB but has no creator, e.g. a wf doing a query and returning the pseudos for a given element, I don't think we should prevent this).
