### ISSUE TITLE
verdi data upf uploadfamily fails with freshly generated UPF file from PSlibrary 1.0.0

### ISSUE THREAD

**Issue by bonfus** [aiidateam/aiida_core#2228]
The error message is:

    File "/home/pie/venvs/aiida/lib/python2.7/site-packages/aiida/orm/data/upf.py", line 301, in parse_upf
    fname))
    aiida.common.exceptions.ParsingError: Unable to find the element of UPF /home/pie/pslibrary.1.0.0/pbe/PSEUDOPOTENTIALS/manyels/Pt.pbe-n-kjpaw_psl.1.0.0.UPF

I went quickly through the code and I fixed it by reading twice the first line to get the UPF version correctly, since the headers looks like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <UPF version="2.0.1">

and replacing `match` with `search` in line https://github.com/aiidateam/aiida_core/blob/60bc39862d0a6f435830cc6f1f7458a42cb9838b/aiida/orm/data/upf.py#L295 

Pseudo-potential is attached. I'm using a fairly recent version of the AiiDA develop branch and the file `upf.py` on github and locally looks the same. Hope it's not duplicated or already solved.

[Pt.pbe-n-kjpaw_psl.1.0.0.UPF.zip](https://github.com/aiidateam/aiida_core/files/2604417/Pt.pbe-n-kjpaw_psl.1.0.0.UPF.zip)

**Comment by giovannipizzi** [comment]
Thanks for the report! I'll look into it as soon as possible
