### ISSUE TITLE
Migrating Node to new backend interface

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#2233]
Here's the plan:

1. `orm.nodes.Node`

- [x] Create concrete class with required methods for all nodes
- [x] Create `Collection` with all the `.object` required methods that require customisation e.g. `delete_node` can go here
Do not expose this class yet in the `orm.__init__.py` so that the original is still being used

2. `orm.implementation.nodes.BackendNode`

- [x] Move `AbstractNode` here and rename to `BackendNode`
- [x] Create `NodeCollection` with appropriate methods
- [x] Rename to `DjangoNode` and `SqlaNode` and convert to use `DjangoEntity`/`SqlaEntity` generics (.e. get rid of `id()`, `pk()` etc)
- [x] Create Django/SQLA collection implementations

3. Putting it together

- [x] Join up `Node` to use `BackendNode`
- [x] Expose `Node` in `orm.__init__.py` and remove conditional imports in `implementation/__init__.py`

Things to check:

- [x] What to do with `delete_code`?
- [x] Does QueryBuilder work correctly?

Anything else I've forgotten?

**Comment by giovannipizzi** [comment]
Beginning scaffolding by @muhrin now in branch [fix_2233_node_to_new_backend](https://github.com/aiidateam/aiida_core/tree/fix_2233_node_to_new_backend) where we will continue working

**Comment by sphuber** [comment]
Fixed in PR #2481
