### ISSUE TITLE
verdi --version: Error, Missing command.

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida_core#2239]
https://github.com/aiidateam/aiida_core/blob/7dfdccd0be8a5b0bf9bca6ff5a99333e5e57c9dd/aiida/cmdline/commands/cmd_verdi.py#L29

`verdi --version` cause `Missing commend.` Error. 
May be better move version to a independent subcommand called by `verdi version`?

**Comment by sphuber** [comment]
Could you please let us know what commit/version of AiiDA you are running and what the exact error message/stack trace is. Thanks

**Comment by astamminger** [comment]
The problem is that the click group expects a subcommand (unless you explicitly call it with `invoke_without_command=True`). I think the easiest fix would be to add the `--version` using the `click.version_option()`

**Comment by sphuber** [comment]
Weird, this definitely worked when I implemented this a few months ago. Also pretty bad that apparently there are no tests for it. Thanks for the hint @astamminger , I will have a look.

**Comment by unkcpz** [comment]
I think that might be the problem of click > 5.x.
@astamminger That's what I mean. Thanks.
@sphuber Sorry for not clearly explain my problem.

**Comment by sphuber** [comment]
Not at all, no worries. Thanks a lot for reporting. I put the fix into `develop`
