### ISSUE TITLE
move setup requirements from setup.py to setup.json

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2241]
Raised by @espenfl  [on the AiiDA mailing list](https://groups.google.com/forum/#!topic/aiidausers/T3wxOHr7GCY)

Pro:
  * simpler parsing

Contra:
 * duplication for extras that reuse dependencies of other extras, in particular the `[all]` extra [1] 

A side-effect would be that aiida-core could be registered on the [aiida plugin registry](https://aiidateam.github.io/aiida-registry/) (if we wanted to).

[1] Note: [PEP 426](https://www.python.org/dev/peps/pep-0426/#id1) asked for implementation of `[all]` at the pip level but it has been withdrawn. pip [will not implement [all]](https://github.com/pypa/pip/issues/4340) and an issue for `[*]` is currently [open](https://github.com/pypa/pip/issues/5039)

**Comment by ltalirz** [comment]
One could think about adding a pre-commit hook that checks the consistency of the `setup.json` and adds dependencies using [this logic](https://github.com/aiidateam/aiida_core/blob/446ce157123fdf5b17ef3573bbadfe4ced632562/setup_requirements.py#L132-L134)

As a first step, we could, however, already outsource everything that is unaffected by code duplication into a `setup.json`.

**Comment by espenfl** [comment]
When we develop on the plugin side it would be nice to confirm to Aiida version lock downs on dependencies in an automatic manner. E.g. such that any updates in Aiida are automatically inherited. I think just moving the stuff from `setup.py` to `setup.json` would be enough. Then you load that content into `setup.py`.

**Comment by ltalirz** [comment]
@espenfl what prevents you from using the `setup_requirements.py` file in the same way as you would be using the `setup.json`?

**Comment by espenfl** [comment]
In principle, nothing, like using any format as long as the information is present. The thing with `json` or `yaml` is that it is kind of build to contain such data. Some thinks it is cleaner to separate it into a `json`, but some do not. I do not have a strong feeling, but in my own opinion I would prefer to load a `json` from Aiida and do checks on that, rather than loading the actual `setup.py`. I would like to flip the question and ask, is there any reason the dependency information is in `setup.py`?

**Comment by ltalirz** [comment]
@espenfl  as described in the issue, there are extras that reuse dependencies of other extras

https://github.com/aiidateam/aiida_core/blob/92651eeb7d1fc16e32052568168aafb83eaef8a5/setup_requirements.py#L132-L134

As stated before, this could be done inside `setup.py` - the only question is whether this might be confusing people, who expect that what they see in `setup.json` to be the last word.

**Comment by ltalirz** [comment]
Please also note there is no reason to load the `setup.py`. We are just talking about the `setup_requirements.py` here.

**Comment by espenfl** [comment]
Sorry `setup.py = setup_requirements.py`. Yes, this would then move to `setup.py` (or keep `setup_requirements.py` just for that). We are mainly after the versions, so inter-dependencies are not so important.

**Comment by sphuber** [comment]
We discussed this with @giovannipizzi and we think that for now it is best to stay with the current use of `setup_requirements.py`. Ideally, we would move to a `setup.json`, for consistency with the plugins and it is a bit cleaner, however, we currently rely on the compound extra requires definitions, which we cannot map onto a json solution. We could introduce a custom field `auto_extras` that provides some rules of how to compose these compound requirements and parse them in `setup.py`, but it will make things more complicated.

@espenfl if what you are trying to do is really more difficult with the `setup_requirements.py` than from a json, could you maybe give an example? As I understand it, you just need the dependencies of `aiida-core` and their version numbers, all of which can be gotten directly from `setup_requirements.py`.

**Comment by espenfl** [comment]
Okey, then let us leave it for now. I just suggested it as I was going to enforce that we follow the Aiida versions now. No problem for us to import the `setup_requirements` and tailor from there, but a `json` solution in the future would be cleaner.

**Comment by ltalirz** [comment]
fixed in #2307
