### ISSUE TITLE
Export archives that miss the `path` repo sub folder will fail on import

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2247]
This was reported by a user that accidentally deleted some repository directories and then manually recreated them, however, they forgot to reinstate the `path` sub folder as well. The `export` did not complain in this case, as it did before reinstating the repo folders, however, the `import` complained about an incomplete export file.

**Comment by yakutovicha** [comment]
We agreed with @sphuber and @lekah that for the consistency we raise an exception during the import process if the "path" folder is not present in the file repository.

**Comment by lekah** [comment]
Shoudn't be this complaining  on export?

**Comment by sphuber** [comment]
Fixed in PR #2274
