### ISSUE TITLE
documentations for installing aiida_core in WSL

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida_core#2256]
Installing aiida_core in WSL (windows subsystem for linux) is possible but needs a few things and would be nice to have it documented.

- [x] Django backend is not working due to timezone settings, use SQLA backend to work around this problem.
- [x] Postgres service needs to be started manually before quicksetup and likely also for normal daily usage
- [x] SSH server needs to be enabled mannually for testsing
- [x] Too many files error encountered while tests
- [x] Windows Native RabbitMQ needs to be installed, ubuntu one does not work 
It would also be nice to find the problem of Django backend and make it work with WSL.

**Comment by CasperWA** [comment]
To start postgresql server write:
`sudo /etc/init.d/postgresql start`
Run also:
`sudo -u postgres psql`
from your own user to get to psql cli using the postgres user

**Comment by zhubonan** [comment]
To allow django to be used (Tested on Ubuntu 18.04 WSL):

`rm /etc/localtime`
`ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime`

From 
[https://github.com/HowardHinnant/date/issues/102#issuecomment-261742293](url)

Note negative effect and persistence to updates are unknown

**Comment by zhubonan** [comment]
Also, the ubuntu version  of rabbitmq does not work in windows - I have to install the windows version instead which seems to work.
However, `verdi devel tests ` seems to get stuck in db tests.

**Comment by sphuber** [comment]
Fixed in PR #2319
