### ISSUE TITLE
RabbitMQ queues remain after a Process is finished

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#2269]
Steps to reproduce:

    from aiida.work import WorkChain, run
    class MyWc(WorkChain):
        def run(self):
            pass
    run(MyWc) 

Running the above code in a `verdi shell` will cause a new queues to appear, e.g.:

    aiida-383bed67dff3409492b626e05cd6477f.messages-reply-22327e45-d3ac-43eb-9726-62eb0287824f | Exp | idle | 0 | 0 | 0 |   |   |  
    aiida-383bed67dff3409492b626e05cd6477f.tasks-reply-f3881054-77f1-49fc-8f54-fe991182fdd4 | Exp | idle | 0 | 0 | 0 |  

Even though the process is now in a terminal state, the queue stay around until the shell is closed.  The situation is the same for a running daemon which results in more and more queues being created until the daemon is shut down.

**Comment by sphuber** [comment]
Fixed in PR #2324
