### ISSUE TITLE
Do we really need Calculation states?

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2280]
We now have a process_state (running, waiting, ...), the process_status (human-readable string, e.g. "Waiting for pk=...", ...) and we still have the attribute "state" with the old calc_state. We should probably clean some logic and clear the use (and probably keep it for a way to query - this is only for CalcJobs).

**Comment by sphuber** [comment]
The old calculation state is currently only stored as an attribute after the separate `DbCalcState` table was dropped. Now, it just needs to be adapted to be an additional level of granularity of state information for `CalcJobs` while it has an active process state, i.e. either `Running` or `Waiting`. The business logic should no longer depend on the calculation state as it should be purely informative and serve as a way to query for specific `CalcJobs`.

**Comment by sphuber** [comment]
Fixed in PR #2389
