### ISSUE TITLE
Dangerous use of os.system() in verdi graph

### ISSUE THREAD

**Issue by ConradJohnston** [aiidateam/aiida_core#2285]
When using `verdi graph generate` , the user can inject shell script into a system call due to the use of os.system() in the underlying draw_graph function which does not sanitise input. The subprocess.call() method should be used instead. 

An example is:
verdi graph generate -f 'something ; touch "do_evil" ;' 1

touch "do_evil" can replaced by any valid shell script that the user has permissions to run.

**Comment by sphuber** [comment]
Fixed in PR #2287
