### ISSUE TITLE
documentation building takes a long time

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida_core#2298]
At the moment, building the documentations using `cd docs && make` takes a long time as the api documentation will be regenerated every time even if there is no change in the aiida code itself. This long delay makes previewing the changes of documents very slow.

Is there a way to bypass the api documentation building?

**Comment by giovannipizzi** [comment]
In my case, sphinx detects only the files that changed and is quite fast (is only a bit slow on `highlighting module code...` but maybe that is unavoidable?) If nothing changed in the docstrings, it's almost instantaneous to complete (~4sec).

**Comment by zhubonan** [comment]
On my machine it always says there are 31 environments changed every time I built and scan though them.
I am on Ubuntu 18.04 by the way.

**Comment by sphuber** [comment]
I am also on Ubuntu 18.04 and for me with `sphinx==1.8.4` it correctly identifies only the changed files after an initial build. Do you still have this problem, and if so, what version of Sphinx are you on?

**Comment by zhubonan** [comment]
I can confirm that I don't have the issue anymore. I am on Ubuntu 18.04 WSL, `sphinx==1.8.4`. 
Probably this is a machine specific problem.
