### ISSUE TITLE
Disable storing of base Node classes

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2300]
We should disable storing of `Node` or `ProcessData` and allow instantiating only `Data`, `WorkflowNode`, `CalculationNode` or their subclasses, that have clear rules for linking.
In the future this will allow also to split DbNode into three tables (and links in different tables, one per type), allowing to enforce constraints on links (data types, number of incoming or outgoing edges) at the DB level.

Note: as @muhrin pointed out, even if we put the constraints at the DB level, we should still keep the python checks/logic, as we might in the future have DB backends where these constraints are NOT enforceable.

**Comment by sphuber** [comment]
Fixed in PR #2301
