### ISSUE TITLE
Harmonization of aiida.common, aiida.control, aiida.manage, aiida.tools, aiida.utils

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2311]
There are currently a number of top-level folders in aiida, whose meaning is not well defined:

* aiida.common
* aiida.control
* aiida.manage
* aiida.tools
* aiida.utils

This leads to confusion among new developers, and has also led to different interpretations of previous developers. We should 

 1. decide what these top-level folders should contain
 2. document this in the `__init__.py` of the corresponding folders
 3. move code that is currently in the wrong place to where it belongs

**Comment by ltalirz** [comment]
@giovannipizzi @sphuber and me have discussed this issue, initially 16.11.2018, and now again 6.12.2018.

We propose the following:
- [ ] aiida.control => aiida.manage.external : controlling system software needed for AiiDA to run (postgres, rabbitmq) - [ ]- [ ][no load_dbenv required]- [ ]- [ ]
  - [ ] Actual content: Postgres
  - [ ] profile => manage.profile
  - [ ] code => tools.code
  - [ ] tools => tools.computer
- [ ] aiida.tools: interfaces external tools with the AiiDA ORM - [ ]- [ ][may require load_dbenv]- [ ]- [ ]
  - [ ] Current content is fine
  - [ ] To open issue: Think about how to expose this functionality in a more visible way (e.g. in a .tools, with an aiida.tools.data entrypoint)
  - [ ] When to put functionality in ORM classes and when to move them to tools?
     Interface of ORM classes only provides functionality to set up & access the data structure - advanced operations on the data types that may be useful but should not clutter the namespace should go into tools
- [ ] aiida.manage: controlling the configuration of aiida (profile, database or repository): e.g. validation, migration of config.json, vacuum cleaner of repository... - [ ]- [ ][may require load_dbenv]- [ ]- [ ]
  - [ ] Current content is fine
  - [ ] aiida.manage.databases: manage databases
- [ ] aiida.common: definitions of common data structures that do - [ ]not- [ ] require the DB, link types, exceptions + common utilities - [ ]- [ ][no load_dbenv required]- [ ]- [ ]
  - [ ] common.additions.config_migrations => aiida.manage.config
  - [ ] common.additions.backup_script => aiida.manage.backup
  - [ ] common.example_helpers => remove (including test)
  - [ ] common.caching => manage.caching
  - [ ] common.ipython => tools
  - [ ] common.graph => tools.graphviz
  - [ ] common.log => (partly) into orm.utils.logging
  - [ ] common.profile => manage.profile
  - [ ] common.setup => manage.setup
  - [ ] common.utils
    - [ ] Classproperty, abstractclassmethod, abstractstaticmethod => common.lang
    - [ ] Xyz_parser_iterator => tools.orm.data.structures
    - [ ] EmptyContextManager => common.lang
    - [ ] Fortran-stuff => common.fortran
    - [ ] Ask_question, query_yes_no, query_string: move to backup_setup file (only place where it is used)
    - [ ] Combomethod => common.lang
    - [ ] Prettifier, pretty_labels, join_labels => …
    - [ ] Get_mode_string, md5, sha1... => common.files
    - [ ] HiddenPrints => merge with Capturing
    - [ ] type_check => common.lang
    - [ ] get_regex_pattern_from_sql, sql_string_matchm escape_for_bash => common.escaping
- [ ] aiida.utils: will be removed entirely (mainly in favor of `common`)
  - [ ] ascii_vis => cmdline.utils
  - [ ] capturing => aiida.common.utils
  - [ ] cli: (sebastiaan: )remove
  - [ ] delete_nodes => aiida.manage + issue
  - [ ] email => aiida.common.utils
     - [ ] If possible, remove validate_email dependency (rather use from django)
  - [ ] error_accumulator => common.utils
  - [ ] find_folder => common.folders
  - [ ] fixtures => manage.fixtures
  - [ ] json => common
  - [ ] queries => common.db / manage.db
  - [ ] serialize => orm.utils.serialize
  - [ ] timezone => common.timezone
  - [ ] which => common.files

**Comment by ltalirz** [comment]
In terms of how to proceed: 
 * we wait until `provenance_redesign` is merged back into develop
 * releasing `1.0.0b1` before fixing this is acceptable
 * ideally, this should be fixed before releasing `1.0.0`

**Comment by sphuber** [comment]
Fixed in #2357
