### ISSUE TITLE
define & document API forward compatibility guarantees

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2313]
As of today, the `aiida-core` package contains numerous functions, classes, etc. that are publicly accessible (no `_` prefix) but actually intended for `aiida-core`-internal use, not for AiiDA users.
This applies, for example, to many of the functions and classes mentioned in #2311 .

We should think about which parts of the API we want to guarantee to keep working going forward (and which parts may be subject to change).

**Comment by ltalirz** [comment]
Proposal by @sphuber, @giovannipizzi, @ltalirz:

Anything that can be reached via `from aiida.<x> import <y>` should be "good to use".
API at deeper level of nesting may be subject to change.

**Comment by sphuber** [comment]
Fixed in PR #2571
