### ISSUE TITLE
Not converting DbLog backend to Log frontend object

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida_core#2321]
When trying to show log from a CalcJob an error occurs, where it tries to access DbLog object from django backend. This should be converted to the new frontend.
The code to be changed/updated is connected to the querybuilder of django (and probably SQLAlchemy as well) and can be found in `get_aiida_res`:

`elif isinstance(res, (self.Group, self.Node, self.Computer, self.User, self.AuthInfo)):`

Both Log and Comment is missing.

**Comment by sphuber** [comment]
Fixed in PR #2325
