### ISSUE TITLE
`verdi work report` raises exception when executed without pk

### ISSUE THREAD

**Issue by atztogo** [aiidateam/aiida_core#2338]
Maybe already fixed, but at v1.0.0a4, `verdi work report` raises exception when executed without pk as written in #535.

**Comment by sphuber** [comment]
Confirmed in `1.0.0a4`, but this is fixed in `provenance_design` which should be merged relatively soon into `develop`. Thanks for the report @atztogo

**Comment by atztogo** [comment]
Thanks @sphuber  for your explanation. I see the current status.
