### ISSUE TITLE
Re-enable travis linter after pre-commit ruby issue is resolved

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2362]
On 19 Dec 2018 v3.0.0 of ruby gem was released, causing `pre-commit` to fail because it uses the deprecated `--no-ri` option. For now I have disable the travis linter in `.travis.yml` but when the [corresponding issue](https://github.com/pre-commit/pre-commit/issues/890) is resolved, we should update `pre-commit ` and re-enable the travis linter.

**Comment by asottile** [comment]
as a workaround, you can use `language_version` to select on older version of ruby (or `system` I believe if you're guaranteed to have ruby already installed)

**Comment by sphuber** [comment]
This is now fixed in [`pre-commit==v1.13.0`](https://github.com/pre-commit/pre-commit/releases/tag/v1.13.0)

**Comment by sphuber** [comment]
Fixed in PR #2364
