### ISSUE TITLE
Remove legacy workflows models and add a migration

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2380]
The logic of the legacy workflows has already been removed, but the database models were maintained, because once they are removed, a migration will have to be added as well that will drop the tables from existing databases. However, before they are dropped, users might want to dump the data for later reuse. This functionality will have to be implemented first.

**Comment by sphuber** [comment]
In the models I see three classes defined:

* `DbWorkflow`
* `DbWorkflowData`
* `DbWorkflowStep`

However in the database, I see three tables (for both Django and SqlAlchemy):

* `db_dbworkflow`
* `db_dbworkflowdata`
* `db_dbworkflowstep`
* `db_dbworkflowstep_calculations`
* `db_dbworkflowstep_sub_workflows`

How are these latter two ones generated?
@giovannipizzi you happen to know how this works?

**Comment by sphuber** [comment]
Ah it seems that those are secondary tables from the many-to-many relationship on the `DbWorkflowStep` table. They are automatically dropped if I drop the parent and also automatically dumped when I dump just the parent.

**Comment by giovannipizzi** [comment]
> Ah it seems that those are secondary tables from the many-to-many relationship on the DbWorkflowStep table. 

Correct.

> They are automatically dropped if I drop the parent and also automatically dumped when I dump just the parent.

Are they? Dropping probably yes because of DB constraints. for dumping, I guess it depends on the dumping function?

**Comment by sphuber** [comment]
For django definitely they were dumped, they were attached as a list for each step entry, for sqlalchemy I am not sure

**Comment by szoupanos** [comment]
I was ready to say to drop the tables one by one, in order to be on the safe side (at least for SQLA).
But I see at the PR that you already did it.
