### ISSUE TITLE
implement a `verdi status` command

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2409]
aiida now depends on a number of services working properly:

 * postgresql database
 * rabbitmq queue
 * aiida daemon
 * file repository

Many errors that users encounter in their daily work will have to do with one of these services not running as expected.

What about implementing a `verdi status` command that checks whether these services are up and running as expected and shows green/red lights + status information?

**Comment by astamminger** [comment]
I really like this idea :)

**Comment by sphuber** [comment]
Fixed in PR #2487
