### ISSUE TITLE
Build fails with pip==19.0

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#2414]
When trying to build with the new ``pip==19.0`` version, it fails with an ``ImportError`` of ``fastentrypoints``. This seems to be an issue with either ``pip`` itself or ``fastentrypoints``, but I couldn't reproduce it trying to only install fastentrypoints itself (although admittedly I didn't try very hard).

I'm writing this here more as an FYI, since I don't believe anything needs fixing on the AiiDA side.

**Comment by greschd** [comment]
Related: https://github.com/pypa/pip/issues/6175
And probably also: https://www.python.org/dev/peps/pep-0517/

**Comment by CasperWA** [comment]
Work-around with #2415.

**Comment by giovannipizzi** [comment]
I would keep this open - I think we need to fix the problem and support pip 19 as well.

**Comment by ltalirz** [comment]
With pip 19.0.3, @broeder-j and me are getting 
` pkg_resources.DistributionNotFound: The 'aiida-core' distribution was not found and is required by the application`

**Comment by sphuber** [comment]
This was fixed in PR #2741 . Install should now with work even with `pip>=19`
