### ISSUE TITLE
Wrong migration for DbLog to be fixed

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2423]
The migration recently introduced in #2393 was incorrect: it doesn't work if there are already (more than 1) DbLogs, and moreover it would just lose completely the information of which node each log is associated to (because the objpk column is dropped and the objuuid is created without transferring data).

Moreover, now that LegacyWorkflows are removed, it's not needed anymore to have a 'objpk' and a 'objname' to know if it's related to a node or a workflow, but we can just have a foreign key to DbNode.

Tasks:
- [x] Rewrite the migrations (0024 for django and the corresponding one for SQLA) to avoid losing the data, and not defining objuuid but rather converting objpk to a foreign key
- [x] Remove the 'objname' column, writing to files (in JSON?) all logs that were of old LegacyWorkflows
- [x] Adapt the code to use the new foreign key relation (in particular the import/export requires some work)
- [x] write migration tests both for Django and SQLA to ensure that the migration is correct

Note that since the migration 0024 is wrong, it should be replaced (and we should make sure nobody run it before this issue is closed). Ideally, we should merge this before other changes.

**Comment by sphuber** [comment]
Fixed in #2447
