### ISSUE TITLE
Rebooting the computer may render the daemon unusable

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida_core#2459]
When rebooting the machine while the daemon is running, the PID file of Circus may not be deleted (`.aiida/daemon/circus-<profile>.pid`). At the next restart, any "verdi daemon" command will see the PID file and assume that Circus is running, but will fail to connect. Deleting the PID file solves the issue, but we might think of ways to avoid this situation. For instance:

- [ ] Try to catch kill signals sent to Circus during the shutdown process;
- [x] create an AiiDA system service, at least for popular linux distros (might be already done, see issue #1434);
- [ ] if Circus is not responding when it should, inform the user that they might want to delete the PID file manually, if they are sure that Circus is really not running.

**Comment by sphuber** [comment]
This should now be fixed by PR #2795 if there is a stale PID calling `verdi daemon stop` will fix it
