### ISSUE TITLE
Don't fail during the DbLog migration if there are Logs of deleted nodes

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2476]
With @sphuber we just realised another corner case that makes the migrations fail (also including the fixes of #2447).
Let's say the user created a node with `pk=7` with some logs, so there is a least a row in DbLog with `objpk=7`.
The user then deleted the node `7`. As `objpk` was not a foreign key and there was no cascading, the logs stayed.
Now, when the migration is applied, it will convert `objpk` to `node_id` and, when converting it to a foreign key, it will fail because at least one `node_id` has a value, `7`, that has no corresponding row in the `db_dbnode` table.

To solve this, I suggest to proceed as follows:
- also add a check for non-existing nodes, and dump all logs to another file (as already done for e.g. LegacyWorkflows, etc.)
- delete those rows
- then proceed with the same migration

**Comment by sphuber** [comment]
Fixed in PR #2507
