### ISSUE TITLE
Migrate v1.0.0 backward incompatible changes page to Sphinx Docs for release

### ISSUE THREAD

**Issue by ConradJohnston** [aiidateam/aiida_core#2482]
Currently, the docs on backward-incompatible changes are being composed on this [Wiki page](https://github.com/aiidateam/aiida_core/wiki/Backward-incompatible-changes-in-1.0.0) .

Before v1.0.0b is released, the following should be done:

- [x] Finalise content of the wiki page
- [x] Convert the markdown format content to restructured text. 
      One can use `pandoc` for this:  `$ pandoc wikitext.md -o sphinxtext.rst`
- [x] Replace the placeholder in the docs (docs/source/install/updating_installation) with this finalised text

**Comment by giovannipizzi** [comment]
I would do this for 1.0.0 and keep in the wiki for the beta lifetime
