### ISSUE TITLE
Imported Log entries cannot be re-exported due to metadata column content

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida_core#2484]
When importing `Log` entries (tested with a django backend), the dict in the `metadata` column in the `db_dblog` table is imported with single-quotations instead of double-quotations, making it impossible to re-export the `Log`s again, if one would want to do that.

When `Log`s are originally created, the dict in `metadata` uses double-quotations.

**Comment by sphuber** [comment]
Fixed in PR #2486
