### ISSUE TITLE
Importing "old" Comments for existing Node

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida_core#2489]
Related to #2448.

Similar tests as those related to #2448 and PR #2486.

Make sure `Comment`s related to existing `Node` are correctly imported.

Make sure that if one changes a previously exported `Comment` in their DB, the imported (old) `Comment` with the same UUID, should not overwrite the existing one.
This should not happen for `Log`s in anyway, since they should/cannot be changed once made (@sphuber this is true, right?).

**Comment by sphuber** [comment]
Yes `Log` entities are stored upon construction as they are immutable

**Comment by sphuber** [comment]
Fixed in PR #2486
