### ISSUE TITLE
move aiida.common.serialize under aiida.orm

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2499]
`aiida.common.serialize` imports `aiida.orm`, while "Modules in this sub package [common] have to run without a loaded database environment".

We should probably move it to aiida.orm.utils
@giovannipizzi @sphuber Do you agree?

**Comment by giovannipizzi** [comment]
Yes, it looks a ORM util indeed

**Comment by sphuber** [comment]
Yes, I don't think we can decouple the serializer/deserializer from the ORM so it should go in that module

**Comment by sphuber** [comment]
Fixed in PR #2501
