### ISSUE TITLE
move DBLogHandler from aiida.common.log to aiida.orm

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2500]
The DBLogHandler clearly needs the ORM but currently lives in aiida.common.log

I guess it should be moved to aiida.orm (@giovannipizzi @sphuber just let me know where exactly).

**Comment by sphuber** [comment]
I would move it into `aiida.orm.utils.log` module together with the `get_dblogger_extra` and `create_logger_adapter` functions

**Comment by sphuber** [comment]
Fixed in PR #2501
