### ISSUE TITLE
Move the conventions on aiida module importability to documentation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2527]
These conventions are being curated [on the wiki](https://github.com/aiidateam/aiida_core/wiki/AiiDA-module-hierarchy) and should be moved or copied to the documentation

**Comment by giovannipizzi** [comment]
I would move this in the docs only for the 1.0.0, keeping in in the wiki for the beta phase (like we do for deprecation/backward incompatibilities).
