### ISSUE TITLE
Why are group type strings being restricted? [provenance_redesign branch]

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida_core#2551]
https://github.com/aiidateam/aiida_core/blob/56344da6496e314f2db78a4e3d753dfc87454017/aiida/orm/groups.py#L29

https://github.com/aiidateam/aiida_core/blob/56344da6496e314f2db78a4e3d753dfc87454017/aiida/orm/groups.py#L77

In aiida-crystal17 I have a BasisSetData plugin, similar to UPF, but for gaussian basis set families. 
I'm using `BASISGROUP_TYPE = 'data.basisset.family'` for the type string, but obviously this change breaks that

**Comment by chrisjsewell** [comment]
FYI, the other thing I noticed from the provenance branch was;
is the `CalcJob` class missing an override of the base `get_builder` method?  

```python
from aiida.engine.processes.builder import CalcJobBuilder

class CalcJob(Process):
...
    @classmethod
    def get_builder(cls):
        return CalcJobBuilder(cls)
```

**Comment by espenfl** [comment]
Yes, we are also seeing the issue with `GroupTypeString`. Also for the potentials.
