### ISSUE TITLE
Validation of link labels

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2568]
There are a number of places where, I think, we assume that link labels are valid python variable names, like:
- `.inputs.<label>` and `.outputs.<label>` methods of ProcessNodes
- when passing labels as kwargs to `run()` and `submit()` (actually I think cPython does not require this and works also with invalid variable names, but other python implementations might break)

Therefore, it might be a good idea to document rules on link labels and enforce/validate these rules in `add_incoming` (and possibly other places if applicable)

**Comment by sphuber** [comment]
The validity of port names, and by extension the keys that need to be used in the launch functions, is taken care of in PR #2688 . This will also guarantee that the link labels that are generated automatically by the engine, by imploding the nested port namespaces, are valid. However, this validation is bypassed when calling `add_incoming` directly. We should add an explicit check on label validity in this method.

**Comment by giovannipizzi** [comment]
Good point
