### ISSUE TITLE
Bug in creation of `dbinfo` of `Postgres` class in `verdi quicksetup`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2595]
The `Postgres` class, used to connect to postgres, has an internal attribute `_dbinfo` which stores a dictionary of parameters that should be used to connect to the database. Defaults for the `port` and `hostname` are only set if the `dbinfo` is `None` during construction. However, in `verdi quicksetup` an actual `dbinfo` argument *is* passed, however, the `port` and `hostname` are set to `None` if they are not explicitly passed by the user, because the default values for these options are set to `None`. This leads to problems further on, because without a valid hostname and port, the connections will fail. Moreover, at the end of `quicksetup` the `port` and `hostname` are retrieved from the same `dbinfo` obtained from the `Postgres` instance, with the `get` construction, passing the defaults in the case they are not set. However, they *are* set, they are just set to `None`. As a result, `None` is set for these keys in the newly created profile and all subsequent connections will fail as a result.

**Comment by ltalirz** [comment]
thanks for noticing this, I guess this is one for me to fix
