### ISSUE TITLE
Automatic reentry scan

### ISSUE THREAD

**Issue by odarbelaeze** [aiidateam/aiida_core#2605]
This should have been solved by #632 however it seems that on a python2 fresh setup the `reentry_scan` is not performed during setup and we get:

```bash
/ # verdi
Traceback (most recent call last):
  File "/usr/local/bin/verdi", line 6, in <module>
    from aiida.cmdline.commands.cmd_verdi import verdi
  File "/usr/local/lib/python2.7/site-packages/aiida/cmdline/commands/__init__.py", line 21, in <module>
    from aiida.cmdline.commands import (cmd_calcjob, cmd_code, cmd_comment, cmd_completioncommand, cmd_computer, cmd_config,
  File "/usr/local/lib/python2.7/site-packages/aiida/cmdline/commands/cmd_calcjob.py", line 31, in <module>
    @arguments.CALCULATION('calcjob', type=CalculationParamType(sub_classes=('aiida.node:process.calculation.calcjob',)))
  File "/usr/local/lib/python2.7/site-packages/aiida/cmdline/params/types/identifier.py", line 67, in __init__
    raise ValueError('{} is not a valid entry point string: {}'.format(entry_point_string, exception))
ValueError: aiida.node:process.calculation.calcjob is not a valid entry point string: Entry point 'process.calculation.calcjob' not found in group 'aiida.node'
```

We might want to add an exception handler that suggest you to run `reentry_scan` or add a command to the setup so that the command is run in the users console after the setup is finished.

Something similar to https://www.anomaly.net.au/blog/running-pre-and-post-install-jobs-for-your-python-packages/.

Python2 is in the way out tho.

**Comment by sphuber** [comment]
> add a command to the setup so that the command is run in the users console after the setup is finished.

This should in fact already happen. If you look in the `setup.json` you will find:
```
  "reentry_register": true,
  "reentry_scan": [
    "aiida"
  ],
```
This should trigger the scan upon a clean install.
I tried to reproduce the problem on `develop` with a clean virtualenv but could not:
```
$ mkvirtualenv aiida_test
$ pip install -e .
$ verdi plugin list aiida.calculations
Registered entry points for aiida.calculations:
* arithmetic.add
* templatereplacer

Info: Pass the entry point as an argument to display detailed information
```

can you create a clean environment and try again to reproduce it please?

**Comment by odarbelaeze** [comment]
Just ran from a fresh docker image and the problem still persists:

```docker
FROM python:2.7-alpine
RUN apk add --no-cache alpine-sdk libffi-dev postgresql-dev
RUN pip install aiida-core==1.0.0b1
RUN verdi
```

**Comment by odarbelaeze** [comment]
Confirmed, it works on develop.
