### ISSUE TITLE
BadAuthenticationType: Bad authentication type in verdi computer test newcomputerinstance1

### ISSUE THREAD

**Issue by DI1504** [aiidateam/aiida_core#2609]
After installation of AIIDA .
It gives BadAuthenticationType: Bad authentication type
Here is log with traceback
`(aiidapy) ruchika@ruchika-Inspiron-3521:~$ verdi computer test newcomputerinstance1 --traceback
Testing computer 'newcomputerinstance1' for user ruchikamahajan66@gmail.com...
> Testing connection...
03/17/2019 12:55:45 PM, aiida.transport.SshTransport: [ERROR] Error connecting through SSH: [BadAuthenticationType] Bad authentication type, connect_args were: {'username': u'akashyap', 'allow_agent': False, 'gss_deleg_creds': False, 'key_filename': u'/home/ruchika/.ssh/id_rsa.pub', 'compress': True, 'look_for_keys': True, 'timeout': 60, 'gss_kex': False, 'gss_host': u'crane.unl.edu', 'port': 22, 'gss_auth': False}
** Error while trying to connect to the computer! Cannot 
   perform following tests, stopping.
** Full traceback:
   Traceback (most recent call last):
     File "/usr/local/lib/python2.7/dist-packages/aiida/cmdline/commands/computer.py", line 771, in computer_test
       with t:
     File "/usr/local/lib/python2.7/dist-packages/aiida/transport/__init__.py", line 97, in __enter__
       self.open()
     File "/usr/local/lib/python2.7/dist-packages/aiida/transport/plugins/ssh.py", line 457, in open
       self._client.connect(self._machine,**connection_arguments)
     File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 437, in connect
       passphrase,
     File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 749, in _auth
       raise saved_exception
   BadAuthenticationType: ('Bad authentication type', [u'gssapi-keyex', u'gssapi-with-mic', u'password', u'keyboard-interactive']) (allowed_types=[u'gssapi-keyex', u'gssapi-with-mic', u'password', u'keyboard-interactive'])
(aiidapy) ruchika@ruchika-Inspiron-3521:~$ cd /usr/local/lib/python2.7/dist-packages/paramiko/
(aiidapy) ruchika@ruchika-Inspiron-3521:/usr/local/lib/python2.7/dist-packages/paramiko$ gedit client.py`

**Comment by sphuber** [comment]
Can you try to reconfigure and use `/home/ruchika/.ssh/id_rsa` for the key filename, i.e. without the `.pub` suffix. To trigger the reconfigure, simply do `verdi computer configure ssh <computer_name>` again. Secondly, you set a `gss_host` but set `gss_auth` to `False`, best to leave the host blank. Also if you are logged in to the machine over ssh from which you are running aiida, try to set `allow_agent` to `True`. Finally, make sure you can really connect to the target host using the key you are defining in the configuration

**Comment by DI1504** [comment]
Thank you for the response.
I am also not able to connect through ssh -i ~/.ssh/id_rsa username@HOSTNAME.  It means there is a problem in the ssh key. Since I usually use a passphrase with the password to connect server. And my passphrase is different at every login. So that is why it is not creating a valid ssh key. Please suggest me the possible solution.

**Comment by sphuber** [comment]
Ah that will the problem. AiiDA needs a way to connect to the machine without user intervention, because the Daemon will otherwise not be able to do so automatically. This means that keys with passphrases won't work. We aware that there are systems that require a passphrase that is different everything, but currently AiiDA has no support for these systems unfortunately
