### ISSUE TITLE
No default input/output file defined by process.calculation.calcjob

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida_core#2611]
Passing an `Arithmetic.Add` `CalcJob` UUID to `verdi calcjob inputcat` or `verdi calcjob outputcat` results in:

```shell
Critical: process.calculation.calcjob does not define a default [input or output] file. Please specify a path explicitly
```

The commands `verdi calcjob inputls` and `verdi calcjob outpuls` work fine, i.e. a path exists, and I see no reason why it shouldn't be able to locate and print the contents of a file in either folder.

**Comment by CasperWA** [comment]
In short: Is the desired action that it should always look for `aiida.in` or `aiida.out` if the plugin did not otherwise specify a default input or output file?

**Comment by sphuber** [comment]
I just tried this locally on the latest `develop` and I cannot reproduce the problem. If no `path` is specified in the `verdi calcjob [in][out]putcat` commands, it will use `calcjob.get_option(input_filename)` to get the relative file path. In the current version of `ArithmeticAddCalculation`, the spec defines `aiida.in` as a default for this metadata option. Could it be that the instance of `ArithmeticAddCalculation` you were calling it for was run with a version before the beta? It could be that during development this was not correctly stored.

**Comment by CasperWA** [comment]
> ... Could it be that the instance of `ArithmeticAddCalculation` you were calling it for was run with a version before the beta? It could be that during development this was not correctly stored.

This may be the case, since the tests for `verdi calcjob [command]` essentially import an old archive with a calculation using `ArithmeticAddCalculation`. I will try and make a new archive with the updated plugin.

**Comment by sphuber** [comment]
It will, because currently the `get_option` will just try to get the corresponding attribute. However, older version won't have the `input_filename` attribute. It used to be taken from the class variable of the `JobCalculation` but now since it is configurable as an option, it has to be taken from the attributes

**Comment by sphuber** [comment]
So for new calculations this won't be a problem, however, for existing calculations that don't have the attribute, the filename will have to be explicitly specified. This is annoying, but I am not sure if we can do any better. We might try to load the process class and get the default value for the `metadata.options.input_filename` input from the spec if it is defined

**Comment by CasperWA** [comment]
That clears it up! Should we perhaps implement a function wherein import of `CalcJobNode`'s are checked against existing plug-ins and any 'default' values for new options or others are added to the metadata?

**Comment by CasperWA** [comment]
> ... We might try to load the process class and get the default value for the `metadata.options.input_filename` input from the spec if it is defined

A bit what I was suggesting, but on a more basic level for exported files. I presume what you are suggesting is for `verdi calcjob [command]` to check it itself? Both could potentially be implemented?

**Comment by sphuber** [comment]
Doing it at the import level won't really solve the problem because the original database from which it is exported will still have the same problem

**Comment by CasperWA** [comment]
> Doing it at the import level won't really solve the problem because the original database from which it is exported will still have the same problem

I was thinking to check the existing plug-in upon import and add any attributes to the relevant Nodes according to what is "needed" from the plug-in, using default values.

On another note, I have been hacking my way through trying to figure out what is going on, and what can be retrieved based on the given `CalcJobNode`. Adding the following to `verdi calcjob outpucat` I get the value I want, but it sure is ugly and probably very wrong:

```python
cls = calcjob.__class__
group, entry_point = get_entry_point_from_class(cls.__module__, cls.__name__)
process = calcjob.process_type
GenericFactory = BaseFactory(process.split(':')[0], process.split(':')[1])
test = json.loads(str(GenericFactory.spec()))['inputs']['metadata']['options']['output_filename']['default']
echo.echo_critical('group: {}, entry_point: {}, process_type: {}, test: {}'.format(group, entry_point, process, test))
```

The output (edited with newlines) from `verdi calcjob outputcat [node]`:

```shell
Critical:
group: aiida.node,
entry_point: process.calculation.calcjob = aiida.orm.nodes.process.calculation.calcjob:CalcJobNode,
process_type: aiida.calculations:arithmetic.add,
test: aiida.out
```

**Comment by CasperWA** [comment]
Talked it out with @sphuber, I will implement the following logic for `verdi calcjob [in/out]putcat NODE`:

1. Get path from `NODE.get_option('[in/out]put_filename')`
2. If path is `None`: Try: `path = 'aiida.[in/out]'`. IF success: Issue warning that the option is not specified in the node, possibly provide information on how to add it, and then show content of `aiida.[in/out]`
3. If path is (still) `None`: Throw existing critical message that `entry_point.name` does not define a default [in/out]put file.
