### ISSUE TITLE
topika/tornado making travis tests fail

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida_core#2616]
I am unsure exactly what is happening, but from [Travis](https://travis-ci.org/aiidateam/aiida_core/jobs/508443058) it seems the cause for the failing tests are due to topika/tornado.

**Comment by sphuber** [comment]
Yeah, Martin and I just released `topika==0.2.0` which will be compatible with `pika==1.0.0b2` but I haven't released the new `kiwipy` version to match those changes yet. I will do this now and push a fix
