### ISSUE TITLE
verdi import returns exit code 0 also when import fails

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2633]
this is on aiida-core 1.0.0b1

```
$ verdi import SSSP_accuracy_pseudos.aiida 
\/home/max/.virtualenvs/aiida/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Info: importing archive SSSP_accuracy_pseudos.aiida
READING DATA AND METADATA...
EXTRACTING NODE DATA...
Warning: SSSP_accuracy_pseudos.aiida cannot be imported: Export file version is 0.3, can import only version 0.4
Use 'verdi export migrate' to update this export file.

$ echo $?
0
```

**Comment by CasperWA** [comment]
Since the reason for the fail is quite verbose, it should be fine. But as an added machine-readable warning/error, I will add an appropriate error code. I will check `verdi import` and `verdi export` for this as well.

**Comment by ltalirz** [comment]
Thanks!

These things are important for automation of setup (e.g. via ansible in quantum mobile) where the exit code will determine whether a particular step is considered completed or failed.

**Comment by ltalirz** [comment]
See here for a related fix I'm preparing for `verdi status`
https://github.com/ltalirz/aiida_core/commit/c4a9c9293e190bf8b2e0603ed90f08106761ed22

**Comment by ltalirz** [comment]
in your case you might just be able to use `echo.critical` though (which will already provide exit code 1)

**Comment by CasperWA** [comment]
> in your case you might just be able to use `echo.critical` though (which will already provide exit code 1)

I will do this :)
