### ISSUE TITLE
`SinglefileData` needs way to set file from filelike

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2635]
Currently, the only way to set the file for a `SinglefileData` is through an absolute filepath. However, with the recent change in node repository interface, it is no longer possible to get an absolute filepath from for example a `FolderData` retrieved folder node at the end of a calculation. To create a `SinglefileData` from one of the files it contains, one would have to get the content and create a temporary file on disk only to pass it to `set_file` which will then read the content a gain. The `set_file` should allow both an absolute file path or filelike object.

**Comment by ltalirz** [comment]
Agreed - and I would suggest that this should be possible already in the constructor
