### ISSUE TITLE
Fix CalcJobBuilder.test_submit()

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida_core#2650]
As discussed in #2646:

- `CalcJobBuilder.test_submit()` is broken and needs to reimplement the old [AbstractJobCalculation.submit_test()](https://github.com/aiidateam/aiida_core/blob/8bf2445ddb8a674598f633cadb04ba7316fffc36/aiida/orm/implementation/general/calculation/job/__init__.py#L1728)

**Comment by sphuber** [comment]
Fixed in PR #2743
