### ISSUE TITLE
ProcessBuilderNamespace should be a MutableMapping

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida_core#2659]
For convenience, it just needs a `__delitem__` and `__setitem__`,
then you could do:

```python
builder.update({
    'input1': Node(),
    'input2': Node()
})
```

rather than have to set each attribute separately.

**Comment by sphuber** [comment]
We decided that we did not want to pollute the namespace of the `ProcessBuilder` and so did not make it a `MutableMapping`. However, there is a `_update` method that was introduced in PR #2694
