### ISSUE TITLE
Use function name/docstring for label/description of CalcFunctioNode

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#2682]
When running a calcfunction, the name of the function (here: `testing`) is shown as the process label in the  `verdi process list` command. This is obviously very useful information.

```
$ verdi process list -a
 ...
 104  7s ago     ⏹ Finished [0]  testing
 ...
```

However, when looking at the generated `CalcFunctionNode` using `verdi node show`, label and description are empty.

```
$ verdi node show 104
\/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Property       Value
-------------  ------------------------------------
type           CalcFunctionNode
pk             104
uuid           dccc4421-4349-46cd-9203-41e485bcff0d
label
description
ctime          2019-04-01 12:13:02.502981+00:00
mtime          2019-04-01 12:13:02.902249+00:00
process state  ProcessState.FINISHED
exit status    0
Inputs      PK  Type
--------  ----  ------
a          103  Int
Outputs      PK  Type
---------  ----  ------
result      105  Int
```

I propose to populate the fields
 * `label` by the name of the function
 * `description` by the docstring of the function (if exists)

**Comment by sphuber** [comment]
Seems a very useful suggestion. I think it would make the most sense that these serve as a default and that explicitly specifying either of them in the `metadata` when calling the function should override. Do you agree?

**Comment by ltalirz** [comment]
> I think it would make the most sense that these serve as a default and that explicitly specifying either of them in the metadata when calling the function should override. Do you agree?

Fully agreed!

**Comment by ltalirz** [comment]
Very nice, thanks @sphuber !
