### ISSUE TITLE
Replace `TextField` columns in Django models for JSONB

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2699]
Now that Django supports JSONB, maybe it is better to use that instead of `TextField` which was used as a temporary replacement in the original schema.
Fields that are affected:

    * `DbComputer.metadata`
    * `DbComputer.transport_params`
    * `DbAuthInfo.auth_params`
    * `DbAuthInfo.metadata`
    * `DbLog.metadata`

Ideally, this is done before the release of `v1.0.0` as this requires database migrations

**Comment by CasperWA** [comment]
I guess this is related to issue #2454? Could we gather all issues for this in a project and possibly an implementation timeline/plan or similar? Just to make sure no work is duplicated.

**Comment by sphuber** [comment]
I discussed this with @szoupanos . After I was almost done, I realized that this might overlap with the work he is doing with regards to the attributes and extras of the node model. However, in any case this work is sufficiently separate from it that it deserves a separate commits/PR. Even though its conceptually the same. The node migration will be relatively complicated and the changes here are relatively trivial. Better to do it separately and make sure everything passes

**Comment by szoupanos** [comment]
Thanks a lot Seb for this!

I understand that the migration is the following one (and the PR the #2706)
0033_replace_text_field_with_json_field.py

A rather obvious question:
I see tests for the migration but I don't see any data migration. Should I assume that the data migration is handled automatically by PostgreSQL/Django?
