### ISSUE TITLE
TypeError for 'enabled' key in computer import

### ISSUE THREAD

**Issue by PhilippRue** [aiidateam/aiida_core#2724]
For a test of my plugin I import an old calculation and then want to reuse the old input nodes to submit a test calculation. 
In my test script I have the lines 
```
        from aiida.orm.importexport import import_data
        import_data('files/db_dump_vorocalc.tar.gz')
```
where I then get an error
```
E               TypeError: 'enabled' is an invalid keyword argument for this function
```

This seems to come from commit 4f7b6d88b where the `enabled` column was removed. Going back to commit fb0d55a57 worked for the moment.

Do I maybe need to migrate my data before the import? The data I imported was previously migrated using the fork https://github.com/yakutovicha/aiida_core.git (commit f5fff1846 of branch `export_migration`) in order to be able to import it.

**Comment by sphuber** [comment]
the migration of export archives is still in flux and needs to be finalized. This is being taken care of in PR #2478 . Since we do not want to up the archive version number for the beta's, we keep updating this PR as needed until we are ready for the release of `1.0.0`. Unfortunately, this causes some inconvenience as you have noticed, apologies for that.

**Comment by PhilippRue** [comment]
I overlooked that there was an update to the PR since I migrated the files. 
I now migrated my files again from v0.3 to 0.4 using the latest changes from PR #2478 and now everything is fine.

Thanks

**Comment by CasperWA** [comment]
> I now migrated my files again from v0.3 to 0.4 using the latest changes from PR #2478 and now everything is fine.

Good to hear! But yeah, take care when using the PR code to migrate as it will not necessarily always be up-to-date.

> Thanks

You're welcome :) :+1:
