### ISSUE TITLE
.reciprocal_cell not found when KPointsData has already been stored

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida_core#2749]
When I store a k point data, the .reciprocal_cell disappears.
Simple example:
alat = 5.430  # angstrom
cell = [[0.5 * alat, 0.5 * alat, 0.,], [0., 0.5 * alat, 0.5 * alat,],[0.5 * alat, 0., 0.5 * alat,],]
structure = StructureData(cell=cell)
structure.append_atom(position=(0.000 * alat, 0.000 * alat, 0.000 * alat), symbols=['Si'])
structure.append_atom(position=(0.250 * alat, 0.250 * alat, 0.250 * alat),  symbols=['Si'])
k=KpointsData()
k.set_cell(structure)
k.store_all()

Now compare k.reciprocal_cell with load_node(pk)reciprocal_cell

Is it meant to be like that or is it a bug??
This is breaking all my siesta bands parser. Please let me know

**Comment by sphuber** [comment]
By looking at the source code `KpointsData.set_cell` seems to take the structure cell as its input, but you are passing the `StructureData` instance. Try to pass `cell` instead.

**Comment by bosonie** [comment]
Sorry, that was a little mistake in coping my example. It's supposed to be  k.set_cell_from_structure(structure) (or alternately k.set_cell(structure.cell)). 
Anyway this is not the point. My point is that the stored KpointData, never has the reciprocal_cell...

**Comment by sphuber** [comment]
The problem is because the `reciprocal_cell` attribute is set only by calling the `_set_reciprocal_cell` method. This has changed because the old design of the `KpointsData` initialized this in the constructor, but the constructor is no longer called when loading a node. So a temporary fix for you is to always call `_set_reciprocal_cell` after loading a `KpointsData`. A long term fix may be added later

**Comment by bosonie** [comment]
Thank a lot Sebastian! Just to add to the thread. Because of the problem above, the functionality get_kpoints(cartesian=True) is broken for every stored KpointData

**Comment by giovannipizzi** [comment]
Thanks for the report! I'll try to fix this today (and add a couple of tests)
