### ISSUE TITLE
Ensure that version number is increased correctly

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#2790]
This is not necessarily something that is done wrong but an issue to discuss to ensure that we have the correct behaviour.

This came to my attention with the implementation of Django JSONB project. Currently we increase the version number in SQLA when set, reset or delete attribute(s).

However, in Django we increase the node version number only on set and reset (and not on delete). The same behaviour was replicated in Django JSONB.

Which is the correct behaviour and why?
@szoupanos @sphuber @ltalirz @giovannipizzi

**Comment by sphuber** [comment]
This has become obsolete because the `nodeversion` column has been dropped in PR #2937
