### ISSUE TITLE
In develop branch, qb.first() returns implementation node

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida_core#2808]
In Querybuilder in develop branch, qb.first() does not return the object of node class but the implementation class. The expected result is qb.first() == qb.all()[0]

```python
In [22]: qh = {'project': {'user': ['email'], 'structures': ['*']}, 'path': [{'tag': 'user', 'cls': Us
    ...: er}, {'with_user': 'user', 'tag': 'structures', 'cls': StructureData}], 'filters': {'structur
    ...: es': {'id': {'==': 22131}}}, 'order_by': {'structures': {}}}

In [23]: qb = QueryBuilder(**qh)

In [24]: qb.first()
Out[24]: 
['aiida@theossrv2.epfl.ch',
 <aiida.orm.implementation.django.nodes.DjangoNode at 0x7fe7cf28a358>]

In [25]: qb.all()
Out[25]: 
[['aiida@theossrv2.epfl.ch',
  <StructureData: uuid: 824d87dd-f2b6-4491-8cbf-a18b5fac29a9 (pk: 22131)>]]
```

**Comment by giovannipizzi** [comment]
To double check. If this is confirmed, this should be solved before the tutorial. I don't see this for very simple queries (i.e. no joins) and I cannot test now because I have no data yet in my test DB.

**Comment by sphuber** [comment]
The bug only is only triggered for joins with more than one projection
