### ISSUE TITLE
Simplify export file format after JSONB migration is performed

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#2815]
Currently there is a convoluted way of storing datetimes in the export file, to mark them as date times and not as strings (the attributes dictionary is "duplicated", having `None` values in every place that maps a standard data type, except for value related a date time, where a special string is used). This is the `node_attributes_conversion` field, see [docs](https://aiida-core.readthedocs.io/en/stable/import_export/main.html#data-json)

If in #2788 we remove support for datetimes, we can safely remove this dictionary from the data.json - this will reduce the export file size, simplify the code and most probably also make import/export faster.

**Comment by CasperWA** [comment]
We need to make sure that `node_attributes_conversion` is used only for datetime objects.

When removing `node_attributes_conversion`, the newly added `node_extras_conversion` dict can also be removed from the export files.
