### ISSUE TITLE
Error during database migration

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida_core#2845]
While trying to migrate from Database schema version 1.0.30 to schema version 1.0.33 I got an error:
Running migrations:
  Applying db.0033_replace_text_field_with_json_field...Traceback (most recent call last):
  File "/home/bosoni/aiida1python3/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedObject: type "jsonb" does not exist

No idea what's going on...more info in the file
[migration_error.log](https://github.com/aiidateam/aiida_core/files/3152064/migration_error.log)

**Comment by sphuber** [comment]
Did you run `pip install -e .` to update the dependencies? This commit requires a new version of `django` that introduced `JSONB` support

**Comment by bosonie** [comment]
Yes I did...
If I go in the django folder, the version I have is VERSION = (1, 11, 20, 'final', 0). Correct?

**Comment by sphuber** [comment]
Ah I see now, it is the version of postgres that is the problem. You have version 9.3 but AiiDA requires at least 9.5 which implemented the JSONB support which we require.

**Comment by bosonie** [comment]
All right, sorry about that! Didn't realize my postgres version was so old. Now I moved to 9.6.12 and everything seems fine!
