### ISSUE TITLE
Bug in `retrieve_singlefile_list` construct of the `CalcJob`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2858]
The [code in the execmanager](https://github.com/aiidateam/aiida_core/blob/b39a9bec6a05cd5acdbe69608252a1193aa5f408/aiida/engine/daemon/execmanager.py#L406) that automatically creates `SinglefileData` output nodes for the entries in the `retrieve_singlefile_list` has a bug. The constructor should get the `file` argument.

This is an easy fix, but investigating this bug revealed another problem. Unit testing the complete chain of `CalcJob` + `Parser` is not easy, as in the naive approach it requires to run the actual calculation. In `aiida-quantumespresso` we have come up with a nice method to test the parser through pytest and the fixture manager. This allows us to test the parsers, without having to run the actual calculation and without having to manually setup a test environment. However, the concept of the `retrieve_singlefile_list` means that that part cannot be tested. Semantically it is part of the 'parsing' except it is not actually performed by the parser, but by the engine of `aiida-core` during the retrieval step.

The construct has two advantages:
1. The user does not have to do the creation of `SinglefileData` nodes themselves in the parser
2. The output file that serves as the content of those output nodes is not duplicated, as it would if you were to put it in the normal `retrieve_list` and then create a `SinglefileData` manually in the parser.

I think the first advantage is not a very strong one. Creating it manually in the parser is very easy and straightforward and will cost three lines:
```
with retrieved.open('some.file', 'r') as handle:
    node = SinglefileData(file=handle)
    self.out('single_file', node)
```
Having this code in the `Parser` makes it a lot more easy to understand as it does not hide a lot of magic deep in the code of the engine of `aiida-core`.

The second advantage is a lot stronger, however, it can be reproduced by using the `retrieve_temporary_list`. By putting the file in there, instead of `retrieve_singlefile_list` one can still create the nodes manually, but without duplicating their content in the repository through the retrieved folder.

My suggestion would be to remove the singlefile list construct and document/promote the alternative approach.

**Comment by sphuber** [comment]
Mentioning @ltalirz and @giovannipizzi for input and thoughts

**Comment by giovannipizzi** [comment]
Yes I think we've been discussing this IIRC.
Probably as you say if we suggest to use the retrieve_temporary_list it's OK, and for the moment I don't see major problems with it, so I'm ok removing the feature, documenting how to achieve this goal (also in general in the documentation of the parsers) and alert the plugin developers for those who had been using it. Maybe you can first ping them to see if they see if they are using the single file feature and if thy see problems with this change.

**Comment by ltalirz** [comment]
@sphuber Just to clarify:
```
with retrieved.open('some.file', 'r') as handle:
    node = SinglefileData(file=handle)
    self.out('single_file', node)
```
This is exactly what we [recommended plugin authors to do](https://github.com/aiidateam/aiida_core/wiki/AiiDA-1.0-plugin-migration-guide#2-accessing-the-raw-output-files-retrieved-by-the-engine) and also [what I did in aiida-zeopp](https://github.com/ltalirz/aiida-zeopp/blob/release_v1.0.0a1/aiida_zeopp/parsers/network.py).

I was not aware of `retrieve_singlefile_list`. Is this created only "on demand"?
And, importantly: do we know who is already using it?

**Comment by sphuber** [comment]
> I was not aware of `retrieve_singlefile_list`. Is this list created only "on demand"?

Yes it is completely optional, just like the `retrieve_temporary_list`. The `retrieve_singlefile_list` has been there at least since `0.6.0`, so pretty much forever. As for who is using it, I don't know. We could do a search through some of the plugins. It *was* being used by `aiida-quantumespresso`, but I removed it, because it made it difficult to test the parser, and the functionality could be easily replaced as described.

**Comment by ltalirz** [comment]
> Yes it is completely optional

When you say it's optional, do you mean the *creation*  of the list of *using* the list?

> The retrieve_singlefile_list has been there at least since 0.6.0

Ok. If it has been there forever *and* is optional, I don't think it's wise to remove it.
At the same time, it's of course fine to suggest not to use it.

It would be very helpful if you can add 1-2 sentences in the migration guide [here](https://github.com/aiidateam/aiida_core/wiki/AiiDA-1.0-plugin-migration-guide#1-change-the-name-and-signature-of-the-method-parse_with_retrieved)  on the different ways to retrieve stuff

**Comment by sphuber** [comment]
Yes it is completely optional as in you don't even have to specify it on the `CalcInfo`. My vote would be to deprecate the concept, including all the setters and related code and point to the temporary retrieve list in documentation.

**Comment by ltalirz** [comment]
Deprecation is fine with me - as long as people can keep using it if they found it handy.
