### ISSUE TITLE
Deprecate the `retrieve_singlefile_list` mechanism

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2862]
See #2858 for a discussion on why and what the preferred alternative approach is. The things to be done for this:
- [x] Deprecate `retrieve_singlefile_list` from `CalcInfo` description
- [x] Deprecate logic from `execmanager.retrieve_calculation`
- [x] Deprecate attribute getters and setters from `Node`
- [x] Add to `CalcJob` implementation documentation suggested approach using `retrieve_temporary_list` (Edit: this section already exists, but it does not make sense to add a reference here to a mechanism that no longer exists. Instead I will add a section to the wiki about plugin migration to explain how `retrieve_singlefile_list` can be replaced with `retrieve_temporary_list`)

**Comment by CasperWA** [comment]
>     - Add to `CalcJob` implementation documentation suggested approach using `retrieve_temporary_list`

It seems `retrieve_singlefile_list` was never mentioned in the docs, only `retrieve_list` and `retrieve_temporary_list`.

**Comment by sphuber** [comment]
No but there should be a section that we add that replaces its functionality still.
The idea is the following. Imagine the calculation produces a file that you want to store as a separate node. If you put it in the normal `retrieve_list` it will be stored in the `retrieved` folder data node. Then you create a new `SinglefileData` node out of it, but now you are essentially duplicating the content of that file in your repository. For big files that you create often, this becomes inefficient. Instead, there was the `retrieve_singlefile_list` that retrieved these files (in a temp folder) and created the `SinglefileData` output nodes directly for you, without duplicating the content in the retrieved folder as well. This mechanism now is deprecated but can be reproduced by using the `retrieve_temporary_list`. One just has to then manually create a `SinglefileData` node out of those files, but that is trivial enough that we do not need a separate mechanism.

**Comment by CasperWA** [comment]
Cool.
As per our offline discussion, I have now given you push access to my forked repo (I think perhaps you need to accept an invite or so). So now you can update the docs the way you wanted :sunglasses: pushing to the PR #3041.
