### ISSUE TITLE
Set the `CalcInfo.uuid` automatically

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2872]
Currently, the `CalcInfo` requires that its `uuid` attribute be set. So this forces implementations of `CalcJob` to do the following:
```
calcinfo.uuid = self.uuid
```
As far as I know, this is always done and an exception will be thrown if it is not set or set incorrectly. What was the original reason for this attribute and can't we just have the engine set it?

**Comment by sphuber** [comment]
Tagging @giovannipizzi for comment

**Comment by giovannipizzi** [comment]
Not sure there was a specific reason, except avoiding to fill some of the CalcInfo fields "automagically" but indeed maybe in this case it's better
