### ISSUE TITLE
Unable to start job due to ConnectionWrongStateError

### ISSUE THREAD

**Issue by nathanielng** [aiidateam/aiida_core#2909]
Following the tutorial [2019_MARVEL_Psik_MaX / Section 4](https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_MARVEL_Psik_MaX/sections/calculations.html)

Upon submission of the following commands

```python
from aiida.engine import run
run(builder)
```

as well as

```python
from aiida.engine import submit
calculation = submit(builder)
```

The following error appears:

```
ConnectionWrongStateError: Channel allocation requires an open connection: <TornadoConnection CLOSED transport=None params=<ConnectionParameters host=127.0.0.1 port=5672 virtual_host=/ ssl=False>>
```

- Python version: 2.7.13
- `aiida_core` version: v1.0.0b3
- `aiida-quantumespresso` version: v3.0.0a3

[full_error_msg.txt](https://github.com/aiidateam/aiida_core/files/3212327/full_error_msg.txt)

**Comment by sphuber** [comment]
This usually arises if RabbitMQ is not installed or not running. Do a `verdi status` to check the status of required external services. If this excepts, probably RabbitMQ is not installed. To do so, [follow the installation instructions](https://aiida-core.readthedocs.io/en/latest/install/prerequisites.html) online for your operating system

**Comment by nathanielng** [comment]
Okay, I think RabbitMQ not installed / not running was the problem. It's working fine now.
