### ISSUE TITLE
verdi status: reports false negative database connection 

### ISSUE THREAD

**Issue by LamaKing** [aiidateam/aiida_core#2911]
`verdi status` reports that the database cannot be connected to, however, this is not the case. All other commands run as expected. The problem is most likely because `Postgres.from_profile(profile)` is broken and does not actually correctly read the DB information from the profile.
Printing the `dbinfo` we get the following:
```
{'host': 'localhost',
 'port': 5432,
 'user': 'postgres',
 'password': None,
 'database': 'template1'}
```
This the default and not the actual profile.

**Comment by sphuber** [comment]
Thanks for the report @LamaKing . Could you remind us please what OS this was on?

**Comment by LamaKing** [comment]
Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-4-amd64

**Comment by simonpintarelli** [comment]
I have the same problem on Archlinux / Python 3.7.3. Postgres (postgres image from dockerhub) was running inside a container.

**Comment by sphuber** [comment]
I confirmed it as well. Fix is on the way. Thanks to both for the report
