### ISSUE TITLE
`aiida` pip metapackage still installs aiida-core 0.12.3

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida_core#2919]
This comes out in the docs, in the installation instructions (`docs/source/install/installation.rst`)

**Comment by sphuber** [comment]
It should probably still install `0.12.3` until the actual `1.0.0` is released.

**Comment by ltalirz** [comment]
yes. we might still want to add a beta version of the metapackage as well

**Comment by borellim** [comment]
Any news?

I think we should either:
* make a beta version of the 'aiida' metapackage, or
* remove references to the metapackage from the docs, at least until it's ready.

**Comment by borellim** [comment]
To clarify: I can change the docs, but I can't change the PyPI packages.

**Comment by ltalirz** [comment]
@borellim let me know your pypi username and I will add you

**Comment by ltalirz** [comment]
aiida 1.0.0b3 pre-release now out on pypi: https://pypi.org/project/aiida/1.0.0b3/
