### ISSUE TITLE
Drop the `transport_params` of the `Computer` model

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2927]
Metadata that can affect the execution of a calculation job on that computer needs to go in the `metadata` column, which will be included in the hash, once implemented for the computer. All other data that relate to how the connection to the computer should behave should be included in the `AuthInfo` instead (this data should *not* affect the calculation execution, e.g. connection cooldown intervals etc.)

**Comment by CasperWA** [comment]
Note for import/export:
This _will_ change import/export, since "transport_params" are (and were) exported.
