### ISSUE TITLE
Simplify the `User` database model

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2928]
The current `User` entity is mostly used to add the metadata of the owner to a `Node`. However, it includes various attributes related to using the instance as way to authenticate and authorize. This was originally added because the base user implementation provided by Django was used, which requires these additional fields. If Django can be used with a simplified model, this would be better. The only attributes we need:
- id
- email
- first name
- last name
- institution

**Comment by sphuber** [comment]
Question @ltalirz and @giovannipizzi : we didn't discuss if having first and last name as separate attributes is necessary. These things traditionally can be pitfalls. Not all people have a name that falls into this category. Take my own name for example. I would need to include my middle name to match my academic publishing name. Where do I put it? This is also the reason why git just has "name". I propose we simplify further to just a single attribute `name`.

**Comment by giovannipizzi** [comment]
ok for me

**Comment by ltalirz** [comment]
I'm ok with the change in general but I would hesitate to include this in 1.0.
I don't think it's a necessary change and it might break some things (e.g. yml files for verdi quicksetup).
Anyhow, I'm open to discussion.

**Comment by CasperWA** [comment]
Note for import/export:
This will not change anything for import/export, since only: "last_name", "first_name", "institution", and "email" are (and have been) exported.

**Comment by sphuber** [comment]
Decision has been made to merge `first_name` and `last_name` into single `name` column, but since this will introduce breaking changes, we will mark this for release `v2.0.0` see #2945
