### ISSUE TITLE
mpirun command is not appended for sge plugin

### ISSUE THREAD

**Issue by atztogo** [aiidateam/aiida_core#2940]
I am not quite sure where my problem comes, but to submit VASP calculation, `mpirun` doesn't appear in front of vasp command in `_aiidasubmit.sh`.

If I understand correctly, my previous setting for 1.0.0a worked properly. I recently set up AiiDA environment from scratch, so I may make mistake in the steps to build AiiDA setups. Currently I use aiida-core of 6cd8c6ef4ce01ccf864b0c3a60d7d4d7cb0e9d44. I use VASP plugin of f5e094c. Because I don't know where I can start to doubt, I am sorry that I can't provide pin-point information.

My setups are like below.

```
% verdi code show vasp544mpi@gpu2
--------------------  ------------------------------------
PK                    10893
UUID                  660a1a98-e0f5-4172-bb4a-1c23e4902ff4
Label                 vasp544mpi
Description
Default plugin        vasp.vasp
Type                  remote
Remote machine        gpu2
Remote absolute path  /usr/local/calc/vasp/vasp544mpi
Prepend text          No prepend text
Append text           No append text
--------------------  ------------------------------------
% verdi computer show gpu2
Computer name:     gpu2
 * PK:             2
 * UUID:           b33bbaf7-ebc4-4c99-b799-e87b8f95d4ed
 * Description:
 * Hostname:       gpu
 * Transport type: ssh
 * Scheduler type: sge
 * Work directory: /home/togo/aiida
 * Shebang:        #!/bin/bash
 * mpirun command: mpirun -np {tot_num_mpiprocs}
 * prepend text:
   # No prepend text.
 * append text:
   # No append text.
```

After gotocomputer

```
$ cat _aiidasubmit.sh
#!/bin/bash
#$ -cwd
#$ -S /bin/bash
#$ -m n
#$ -N aiida-10961
#$ -V
#$ -o _scheduler-stdout.txt
#$ -e _scheduler-stderr.txt
#$ -pe mpi* 12
#$ -l h_rt=10:00:00

'/usr/local/calc/vasp/vasp544mpi'
```

**Comment by sphuber** [comment]
Hi @atztogo , this may be due to the `withmpi` option of the `CalcJob`. This is set to be `False` by default. So unless the `VaspCalculation` overrides this to be `True` by default, it will be set to `False`. Note you can always set it to `True` manually, by passing it in the inputs:
```
inputs: {
    'metadata': {'options': {'withmpi': True}}
}
```
But probably, for something like `VaspCalculation`, one wants to run with mpi by default. If @espenfl agrees, I suggest he updates the process spec of `VaspCalculation` to set:
```
        spec.input('metadata.options.withmpi', valid_type=bool, default=True,
            help='Set the calculation to use mpi',)
```

**Comment by atztogo** [comment]
Hi @sphuber . Yes, it was my fault. Now `withmpi`: True, I could have `'mpirun'` in `_aiidasubmit.sh`. 
I will discuss with Espen about your suggestion. I think the default to be True is reasonable.
Thanks for your quick response.
