### ISSUE TITLE
Verify that tasks in the process queue of RabbitMQ are properly persisted

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2957]
There has been a report here and there that processes did not continue after rebooting the system. The only thing I can think of is that the tasks that were with RabbitMQ were not properly persisted. This would be an enormous problem, but also hard to believe. Needs to first be reproduced

**Comment by zhubonan** [comment]
I have also experienced it today. The computer was turned off without manually stoping daemon/rmq/postgres, e.g shutdown accidentally.
After reboot, I started the services and the daemon. But the daemon does not seems to continue the work. 

When I try to play, pause, kill a process with `verdi process` it says the process is unreachable.

I am running on Windows Subsystem for Linux with RMQ installed on Windows. AiiDA version is 1.0.0b3

**Comment by sphuber** [comment]
That is exactly the point. Those queues contain the tasks corresponding to the processes that need to be run. These queues are persistent, such that even when the daemon shuts down, those tasks remain there. However, it seems that maybe somehow those tasks are still disappearing when rebooting the machine. The persistence of these tasks by RabbitMQ is the very reason we have it, so if this is true, that would be very bad.

**Comment by zhubonan** [comment]
I see. I just did another test by submitting one job and there is one message in the queue:

![image](https://user-images.githubusercontent.com/33688599/58833009-0f103b00-8648-11e9-9897-ddf54ee38f29.png)

And then if I restart the RMQ  without stoping any services, now all the message is lost:

![image](https://user-images.githubusercontent.com/33688599/58833031-1899a300-8648-11e9-988c-9f216f6e2e82.png)

**Comment by zhubonan** [comment]
Just been thinking about it again. The queues are still there, just the messages are lost. So this means the persistence is configured correctly. 

It seems only the messages published with `delivery_mode=2` will be persistence. Is aiida sending messages in this mode?  [here](https://www.rabbitmq.com/tutorials/tutorial-two-python.html)

I tried to publish a `delievery_mode=2` message manually and then restart the server. The message is still there. So it very likely that the message sent by aiida was in `delievery_mode=1`.

![image](https://user-images.githubusercontent.com/33688599/58834178-96f74480-864a-11e9-8d23-2e8150ffd95b.png)

**Comment by sphuber** [comment]
Yes, this is exactly the problem. I just went into `topika`, the library deep down that `kiwipy` uses to interface with `pika` (more layers than an onion to this thing :sweat: ) and it uses the default for delivery mode in the message properties. This means that even though the exchange and queue are properly set to be durable, the messages themselves are not. I am looking now, in which library I need to place this configuration and will fix it. Thanks for the report @zhubonan !

**Comment by sphuber** [comment]
The fix needs to be done in `kiwipy`. I will push the fix, make a new release and make an announcement probably on the mailing list.

**Comment by sphuber** [comment]
This issue can be closed once [this PR on `kiwipy`](https://github.com/aiidateam/kiwipy/pull/30) has been merged and released in `v0.5.1`.

**Comment by zhubonan** [comment]
By the way, is there a way to fix the processes that have become unreachable due to the message being lost in the queue?

**Comment by sphuber** [comment]
You are on the beta's right? If so, yes, you can.
```
from aiida.manage.manager import get_manager
controller = get_manager().get_process_controller()
controller.continue_process(pk, nowait=False, no_reply=True)
```
Be wary though, if you do this on a process that still has an active task, you can cause all sorts of exceptions due to concurrency problems.

**Comment by zhubonan** [comment]
@sphuber Thanks!
