### ISSUE TITLE
Stopping the daemon always seems to hit a timeout

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#2963]
When calling `verdi daemon stop` consistently the command times out. Eventually, the circus process will be killed. This behavior is very recent and it might have to do with the recent PR #2744 which dealt with attempting to kill `Process` instances when a local runner was interrupted. Now when the daemon is shutdown, the workers receive the interrupt signal, triggering the code that was added in #2744, where they try to kill the processes that were run. However, since these processes are not *un*-registered once they are completed, the daemon will try to kill processes that are already finished, which will cause the "hanging".

**Comment by ltalirz** [comment]
One comment - I don't know how hard it is to start/stop the daemon from the python API but if it is not too hard, then a very powerful test (that would at least address one of the potential issues you mention) would be to 
  * start the daemon
  * start a calculation (that simply waits forever)
  * stop the daemon & start it again
  * check that the calculation is still running
  * kill the calculation

**Comment by sphuber** [comment]
The problem actually stems from process functions. They create their own runner instance, in order not to get blocked for nested process functions, and they also attach their own handlers for interrupt signals to kill the process. This last part is important that if you run one in a local interpreter and then press CTRL+C, the AiiDA process is also properly killed and not just the python process. Otherwise you would end up with a process node that is still `Running` in your database even though it is not. However, this is problematic, because the same interrupt signal is sent to the daemon runners if the daemon is stopped.

The thing that causes the problem described in this issue arises due to an error in the attaching of interrupt signal handlers of process functions. They are attached, but never deattached. That means that each and everyone of those will be called when the daemon runner is asked to stop, even after the functions have long since finished. On top of that, the logic in the handler is incorrect and so will hang because the process no longer exists. This is ultimately what causes the `verdi daemon stop` command to timeout

**Comment by sphuber** [comment]
Fixed in PR #2966
