### ISSUE TITLE
Handling interupts and kills

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida_core#2971]
Sometimes this happens:
```
83  5D ago     VerifyWorkChain  ☠ Killed          Process was killed because the runner received an interrupt
84  5D ago     VaspWorkChain    ⏵ Running         Killed by parent<83>
```
And it is stuck forever.

We can trigger this as well:
`1561  2m ago     VerifyWorkChain  · None`

These things can be triggered by killing the process outside of AiiDA control (e.g. with a simple ctrl+c close to the closure of the submit). It would be nice if we could catch these interrupts and kill processes, also the nested ones. In a production environment, the submission of these things might be killed by the system and then the user would suffer having to cleanup the stuck processes.

Another possibility is to make a tool to sweep the processes when the user wants (e.g. when the user knows nothing should be running) and clean whatever is stuck, including all history in the database up to the point of entry for the stuck calculation.

**Comment by sphuber** [comment]
There is already an [open issue](https://github.com/aiidateam/aiida_core/issues/2711) for this so I am closing this as duplicate
