### ISSUE TITLE
Check documentation for "working with AiiDA/Data types"

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#3022]
Check if it the section is updated to AiiDA 1.0, if it is correct, and if remove possible redundancies

https://aiida.readthedocs.io/projects/aiida-core/en/latest/working_with_aiida/index.html#data-types

**Comment by giovannipizzi** [comment]
Note that probably it makes sense to fix at the same time #3019 by bringing those examples into this section

**Comment by sphuber** [comment]
Fixed in PR #3053
