### ISSUE TITLE
Check documentation for "working with AiiDA/cookbook"

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#3031]
Check if it the section is updated to AiiDA 1.0, if it is correct, and if remove possible redundancies

https://aiida.readthedocs.io/projects/aiida-core/en/latest/working_with_aiida/index.html#cookbook

**Comment by yakutovicha** [comment]
Just as a side note, the section has only one example which is [Checking the queued jobs on a scheduler](https://aiida.readthedocs.io/projects/aiida-core/en/latest/working_with_aiida/cookbook.html).

We may definitely want to expand this section.
