### ISSUE TITLE
Remove annoying questions when running 'verdi database migrate'

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#3033]
Some annoying questions were added in #2427 to prevent unaware users from running the migrations inadvertently.

I think these can now be simplified to a single question before 1.0 as now the migrations should be well checked (still, keeping one question is good to make sure e.g. that the daemon is stopped, they have a backup, and that users know that it is not possible to go back).

Or we can keep the logic as it is, but have an undocumented "force" flag that we use internally as developers.

**Comment by sphuber** [comment]
The force flag is already there.
However, we should in any case improve the message to explicitly say to also backup the **repository** in addition to the database. This is currently not super clear.

Also, we should tell people to first complete all running calculations and workflows. We cannot guarantee that active processes can be continued after the migration.
