### ISSUE TITLE
Kill a calculation but still retrieve the results 

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida_core#3040]
In the old 0.12.x days if a calculation has been killed the daemon still tries to retrieve the results and parse the results. However, it does not seem to be the case in 1.0.0 with the `CalcJobNode` as the process is effectively terminated. 
I wonder if there is a way to reproduce this old behaviour?

**Comment by chrisjsewell** [comment]
+1 for this.
On a similar note, I have a calculation stuck in `CalcJobState.RETRIEVING`. There is an ~1Mb file that has been created in the remote folder and is in the `retrieve_temporary_list`, so I assume that something has gone wrong during this retrieval. Is there anyway to 'unstick' this?

**Comment by sphuber** [comment]
No this is indeed not possible and with the current design, there is no easy way around this. The idea is that if you kill the calculation, you are no longer interested in it, so there is no point retrieving the data. I am not sure if it is possible to add this functionality and how this could be triggered. So unless there is a really strong use case, I am hesitant to go down this route

**Comment by chrisjsewell** [comment]
@zhubonan as a fix/workaround, you might want to check out my aiidateam/aiida-quantumespresso#350 PR, for immigrating existing runs. For example, you would do:

```python
from aiida import load_node
from aiida_quantumespresso.tools.immigrate_calc import immigrate_existing

calc_node = load_node(1)
builder = calc_node.get_builder_restart()
new_calc_node = immigrate_existing(builder, calc_node.outputs.remote)
```

**Comment by zhubonan** [comment]
Thanks for @sphuber and @chrisjsewell. It is not a crucial use case for me. I guess the `immigrate` workaround makes sense (and also record the provenance). Also, at some point, I should implement immigration routine of existing plugins for my plugin.

**Comment by zhubonan** [comment]
Closing the issue as the use cases are rare and workarounds are available.
