### ISSUE TITLE
Update the export version to `v0.6`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#3056]
This should take care of a few things:
* Simplify the schema due to the migration of Django to JSONB for the attributes and extras by removing the data serialization dictionaries. This was only used for datetime objects and since they are no longer supported, the whole concept can and should be removed.
* Convert datetime objects from attributes and extras to isoformat strings, they are no longer supported
* Apply the data migration for old `JobCalculation` nodes that will be handled in #2854

**Comment by CasperWA** [comment]
This is essentially an "umbrella" issue for:

- [ ] Issue #2815: Simplify export file format
- [ ] Issue #2854: Data migration for old `JobCalculation` nodes
- [ ] Project 11: [Django JSONB](https://github.com/aiidateam/aiida_core/projects/11)

Furthermore, it should be noted that _whenever_ the export version is upped, migration functions must be made (even if it is to just up the version number in the migrated archive) and tests for it, possibly including a new archive for [`aiida-export-migration-tests`](https://github.com/aiidateam/aiida-export-migration-tests`).

**Comment by CasperWA** [comment]
I believe this issue can be closed now, correct @sphuber?

**Comment by sphuber** [comment]
Correct, this was fixed in PR #3090
