### ISSUE TITLE
setup of plugins, missing entry points

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida_core#306]
The following entry points need to be added to setup.py and implemented in the plugin loader:

1. aiida.data <- most important, otherwise the Fleur plugin cannot be installed in the new way, via pip.
(also some other data structures or all of them could be added to setup.py)

2. aiida.utils
3. aiida.tools.codespecific / aiida.tools 

The QE code specific tools should then be added to setup.py
Where is the clear difference between utils and tools anyway?

**Comment by giovannipizzi** [comment]
1. I agree on point 1.
2. On point 2, I don't think they should be pluggable. These are utility functions, and if needed by the whole code should be contributed as a pull request. Actually, I think these should be moved into`aiida.common.utils`.
3. For point 3, we can think to have entry points, but I think we should discuss how these are 'seen' by AiiDA - most of the things there are just additional code that uses AiiDA, but that AiiDA doesn't know about. So, probably there is no need to have entry points there, unless we add e.g. a `verdi` command to list all tools.

**Comment by DropD** [comment]
Hi @broeder-j 
Can you tell me more about in what way you would be using the utils and tools entry points?

the utils entry point was originally be meant to be used by plugins for internal utility functions, which don't have to be in the aiida package anymore with the new plugin system, but can be in the plugin's package as they are only accessed from the plugin.

As for tools it is clearly necessary to expose dbimporter and dbexporter entry points. Do you see other use cases?

**Comment by broeder-j** [comment]
The point I think is, everything you connect via entry points, AiiDA can be aware of and test it systematically if it functions. 

@giovannipizzi: I agree. 
I was a confused about aiida.utils and aiida.common.utils.
For me
aiida.utils: 
was meant for 'general app utility' which is not code specific, and should not/or become part of aiida core and is used externally (by users).
aiida.common.utitls was in my mind for aiida internal purposes only.

Concerning point 3.
Yes, you are right and you should clarify how you guys want it.
I guess everything AiiDA needs to know from plugins needs to be done with entry points. 
Everything else I would keep outside and install them as separate python packages.

Example @DropD:

Plugin specific:
I have some utility to merge certain 'type' of parameter nodes.
The dictionary would be Fleur specific.
Also I have 'plot' methods for parameter nodes returned by certain workflows.
All these I would distribute in a separate package from the raw plugin itself.

rather general stuff:
Structure utility, (supercells, break symmetry in a certain way, coordinate transformations ...) 
(some of it is implemented by now in AiiDA)
Cif file handling utility. (search for cif files somewhere and store structures with certain extras)
...
These are in principle not code specific.  I doubt that everything should become part of aiida-core. If such things turn out to be useful for a lot of people and easy maintainable yes, they should be improved (with tests) and pulled.

**Comment by DropD** [comment]
I'm now actively developing the new plugin system in [my fork](/Dropd/aiida_core/tree/ricoh-plugins).
The branch will be continually rebased on top of develop and it may be a while until it is ready for a pull request.

The data entry point is already exposed there and i can run calculations with a simple external plugin (DropD/aiida_mul).
More complex plugins will probably still run into problems. 

@broeder-j: I'd be grateful if you could try it with the Fleur plugin and tell me where it fails.

**Comment by DropD** [comment]
Closing, since aiidateam/aiida_core/tree/feature-plugins branch has the requested entry points.
