### ISSUE TITLE
Test the efficiency of the new Django JSONB implementation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#3067]
Note that especially we need to guarantee that appending to attributes while the node is unstored is efficient and scales linearly. The old implementation required [a fix](https://github.com/aiidateam/aiida_core/pull/733/files#diff-c251db38fcdbaac0d8bebe068face5cfR839) once to enable this.

**Comment by sphuber** [comment]
The first test is to verify the efficiency of appending to attributes before storing. Typical way is to append atoms to a `StructureData` in a loop, which should effectively update the existing attributes.
```
#!/usr/bin/env runaiida
import time
import numpy
from aiida.orm import StructureData

cell = numpy.eye(3)

start = time.time()

for i in range(10):

    structure = StructureData(cell=cell)
    coordinates = numpy.random.random((10000, 3))
    for coordinate in coordinates:
        structure.append_atom(symbols='H', position=coordinate)

end = time.time()

print(end - start)
```
We tested this script for the current `develop` and `django_jsonb` branches for both backends.
The results are given for a run of 10 structures with 10,000 atoms, but running 100 with 1,000 gives similar numbers, showing that the appending to attributes scales linearly.

Develop:
  Django: 16s
  SqlA: 18s

Django JSONB:
  Django: 12s
  SqlA: 16s

So for this particular test, the implementation is faster for both backends. This is because we did not just change the Django database implementation, but also the `BackendNode` interface has been updated to be more homogeneous and efficient

**Comment by sphuber** [comment]
# Testing high-throughput example: CIF cleaning

This test uses the `CifCleanWorkChain` of the `aiida-codtools` package to test the high-throughput behavior of the JSONB changes and compare it with the performance of `aiida-core==1.0.0b4`. The work chain takes a `CifData` as input, runs two `CalcJobs` on it consecutively and the final `CifData` is passed to a `calcfunction` that creates a `StructureData` out of it. Since this captures quite a bit of components of the engine, each entry runs a `WorkChain`, two `CalcJobs` and a `calcfunction` for four processes in total, it is a good benchmark.

Each run sets up a clean profile with empty database and creates a single group into which an archive of 500 `CifData` nodes from COD are imported. With a launch script, a `CifCleanWorkChain` is submitted for each `CifData` node. This was performed for both backends on the `aiida-core==1.0.0b4` branch and the commit on the `django_jsonb` branch that included the refactoring of the `BackendNode` interface and implementation.

Note that a few changes had to be made to the code of both `aiida-core` and `aiida-codtools` to make the test run for all configurations and for efficiency reasons. The impact of these changes will be addressed later on.

### Local changes for `aiida-core
* Disabled `expire_on_commit` for SqlAlchemy sessions
* Disabled creation of the node hash upon storing the node
* Disabled link validation in `Node.add_incoming`
### Local changes for `aiida-codtools`
* Disabled setting of extras on `StructureData` in `primitive_structure_from_cif` calculation function. This is not supported in Django on `develop` so to keep comparison fair, this was disabled for all.

Each run recorded two timings:
 * The time from submission start until submission finish (in parentheses)
 * The time from submission start until all processes are terminated

Results are below:

|Test                      | Django          | SqlA  |
|-----------------------|------------------|----------------|
| `1.0.0b4`             |  03:53 (02:42)  |  03:25 (03:11)  |
| `django_jsonb`    |  03:40 (03:26)  |  03:28 (03:13)  |

It is clear that for SqlAlchemy very little has changed. One might think this is unsurprising since the database schema was not changed, but the changes in the `BackendNode` layer are not trivial and could have changed performance. This test shows that this is not the case.
For Django, the submission becomes a bit slower, but the overall performance is slightly faster. I have repeated the test a few more times and the trend is consistent. This seems to be an acceptable change in performance for the JSONB changes.

## Immutable model properties
On top of the `django_jsonb` commit that was tested above, which included the change in the Django `Node` schema, as well as a reworking of the backend node interface and implementation, another commit was added to improve efficiency. The `ModelWrapper` that wraps database model instances in the backend interface will ensure that, once a node is stored, the instance will be refreshed or flushed if a model field is retrieved or set, respectively. This includes properties like the `pk` and `uuid` despite those being immutable in `aiida-core`. The refresh is therefore unnecessary but is triggered very often. In this additional commit, these fields are marked as "immutable" which will then omit the database refresh if they are accesses, *even* if the node is stored. To test the impact of this change, the tests were repeated for both backends.

In the following table, the results are shown, where "Original" refers to the tests explained above with the `django_jsonb` branch and the "Immutable fields" is exactly the same, but with the single additional commit:

|Test                       | Django          | SqlA  |
|------------------------|------------------|----------------|
| Original                  |  03:40 (03:26)  |  03:28 (03:13)  |
| Immutable fields    |  02:50 (01:52)  |  02:41 (01:49)  |

The change in efficiency is significant. The submission time is almost cut in half, for both backends and the overall running time is reduced by 25%.

## Addressing local changes
As explained in the beginning of this post, a few local changes had to be applied to the code for efficiency reasons. Here we get rid of these changes, one-by-one, to study the impact. All of the following tests have been used with the code of the `django_jsonb` + "Immutable fields" as a base line. Then for each test, only the specific change was reverted and the test repeated. Since the effects are expected to be more or less identical for both backends, the tests have only been performed for SqlAlchemy.


|Test                      | SqlA            |
|--------------------------|-----------------|
| Baseline                 |  02:50 (01:52)  |
| Hashing enabled          |  02:45 (02:16)  |
| Expire on commit enabled |  02:59 (02:37)  |
| Link validation enabled  |  23:10 (23:00)  |

The re-enabling of both the hashing and the expire-on-commit seem to have little effect on the overall run time, but the submission time becomes somewhat slower, especially for the expire-on-commit. The big problem, however, is the re-enabling of the link validation. The submission of the work chains becomes progressively slower. Initially it takes less than a second, but near the end of the test each submission takes over 5 seconds. This is due to the usage of "god" input nodes. A single input node that is used over and over again as an input. Each time it is used a link has to be added and the link validation will verify that no cycles are introduced. This requires to compare all existing links, of which there will be more and more each iteration.

**Comment by szoupanos** [comment]
These are very interesting results and thanks a lot @sphuber for reporting them and doing the corresponding benchmarks! We briefly discussed them yesterday but maybe it needs a bit more thought to see if they can be used (in a more extended version) for the paper too.
