### ISSUE TITLE
Indexing the uuid field of node database-table/ORM-class

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida_core#307]
so far uuid are not indexed and this is responsible for performance issues when querying on uuids since uuids are, practically, strings.

As a reminder, this issue has been derived by a discussion on incremental sharing of the AiiDA graph. If someone receives updates of the graph of someone else (who has previously shared it), the updates have to be incremental and, possibly, a search on uuid is required to establish whether the "fetched" nodes are already present in the database of the receiver and, in this case, have not to be "merged".

**Comment by szoupanos** [comment]
Fixed with pull request #396
