### ISSUE TITLE
Automatic attributes setter for new Data nodes

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#31]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Think to a way to automatically set new attributes of stored nodes.
This should be user dependent (e..g, files stored in ~/.aiida), e.g. with a function that is called automatically every time a node of a given type is stored.
Manage also correctly the exception handling: even if there are errors, a warning should be issued but the node should be saved anyway!

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/31

**Comment by giovannipizzi** [comment]
This use case does not seem particularly relevant, I will close this issue until when someone seems interested in this.
