### ISSUE TITLE
purpose of 'import readline'?

### ISSUE THREAD

**Issue by toxa81** [aiidateam/aiida_core#312]
What is the purpose of 'import readline' in functions like computer_setup?. Apparently, it has some issues on OSX (https://pewpewthespells.com/blog/osx_readline.html) and I observe a weird behaviour of standard input which goes away when I remove the import of readline module.

**Comment by giovannipizzi** [comment]
It's to have interactive input when required. The command was not originally meant to be used when sending data from stdin. We're in the process of converting these commands to use click and accept also parameters from the command line (as we recently did for 'verdi install', now called 'verdi setup' and that can take all parameters from command line).
