### ISSUE TITLE
"python setup.py install" cannot install plum library and django 

### ISSUE THREAD

**Issue by pescobar** [aiidateam/aiida_core#313]
When trying to install aiida-0.7.0 doing `python setup.py install` I get this error:

```
Searching for plum
Reading https://pypi.python.org/simple/plum/
No local packages or working download links found for plum
error: Could not find suitable distribution for Requirement.parse('plum')
```

If I manually execute `pip install git+https://bitbucket.org/aiida_team/plum.git@v0.4.3#egg=plum` (the url is copied from the `requirements.txt` file) then it works and I can go forward with the installation. Then I get this error:

`error: The 'django' distribution was not found and is required by aiida`

To workaround it I have to manually do `pip install django` and then I can finish the installation doing `python setup.py install`

It would be nice if `python setup.py install` works without needing any workaround.

**Comment by giovannipizzi** [comment]
Hi, thanks for the feedback. In the 'develop' branch we have an improved setup.py that should solve all these issues. We're in the process of finishing the documentation and fixing some final tweaks before release. As this will be solved with the new release (date not scheduled yet, but expected by the end of the month), I close this issue.
