### ISSUE TITLE
verdi code update problem (sqla)

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#314]
## potentially interesting for

@lekah

## environment

Ubuntu 14.04
aiida-version: current develop
installed with pip install -e . in the repo
backend: sqla

## expected behaviour:

verdi code update <codename> allows me to interactively change some of <codename>'s attributes if <codename> hasn't been used.

## observed behaviour:

verdi code update <codename> raises AttributeError with message 'DbNode' object has no attribute 'outputs_q'

## steps to reproduce

1. setup and configure a localhost computer using transport direct
2. setup a code named testcode using simpleplugins.templatereplacer as input plugin
3. run verdi code update testcode

```bash
echo "test_localhost
localhost
Local computer for testing
True
local
direct
$HOME/aiida_run/
mpifun -np {tot_num_mpiprocs}
1
EOF
EOF" | verdi computer setup

verdi computer configure test_localhost

echo "testcode
Test code
False
simpleplugins.templatereplacer
test_localhost
/usr/local/bin/nonexistent
EOF
EOF" | verdi code setup

verdi code update testcode
```

## test

I tried to extend the travis file with a test for this. It suceeded for django but failed at aiida computer configure for sqla. It's in [this branch](/DropD/aiida_core/tree/code-update-test) of my fork

**Comment by lekah** [comment]
@szoupanos Please undo commit 9f73b9319d1b03730e84a439281819c9c2e3d961 
which is to blame for the observed AttributeError.
The _q  relationships are being used and they are extremely useful for appender-queries inside the sqlalchemy backend.

**Comment by fernandogargiulo1986** [comment]
Let me point out that the relationship pattern using "backref" rules out 
the inclusion of relationship objects in both the Parent and Child class.

From http://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html :

Alternatively, the|backref| 
<http://docs.sqlalchemy.org/en/latest/orm/relationship_api.html#sqlalchemy.orm.relationship.params.backref>option 
may be used on a *single*|relationship()| 
<http://docs.sqlalchemy.org/en/latest/orm/relationship_api.html#sqlalchemy.orm.relationship>instead 
of using|back_populates| 
<http://docs.sqlalchemy.org/en/latest/orm/relationship_api.html#sqlalchemy.orm.relationship.params.back_populates>:

Indeed, we verified that the redundancy of relationship objects -- _q 
relationships in particular-- did alter in some cases the predicted 
behavior of ORM classes related by foreign keys.

Note that using the "backref" parameter in a relationship object of the 
parent class automatically introduces a similar objects into the Child 
class.

In the class Node, you now have a relationships called "outputs" which 
is backreffed to "input", meaning that an additional relationship 
"input" is present in each Node object (perhaps not in the class, not sure).

One should be able to refactor all the code dependent on the _q 
relationships with the new names, if not done yet.

I would check this before undoing the commit

F

**Comment by lekah** [comment]
@fernandogargiulo1986 Thanks, that would be great. I didn't think about these additional constraints.
One thing that might facilitate: Keep in mind that  the _q  relationship are only for appender queries, and we don't ever populate it. And one can also work without backref, e.g. explicitly defining inputs and outputs of a Node.

**Comment by fernandogargiulo1986** [comment]
From

git grep -e "_q" | grep -v "qu" | grep -v "qs" | grep -v "qb" | grep -v 
"qe" > foo

cat foo

I get the output:

Binary file 
aiida/backends/tests/export_import_test_files/graph_6255491_where_are_parents_of_6537645.pdf 
matches
Binary file 
aiida/backends/tests/export_import_test_files/parents_of_6537645.aiida 
matches
aiida/backends/tests/pwinputparser.py:                for ref_q, q in 
zip(ref_site.position, site.position):
aiida/backends/tests/pwinputparser.py:                for ref_q, q in 
zip(ref_row, row):
*aiida/orm/implementation/sqlalchemy/node.py:        return 
self.dbnode.outputs_q.all()*
aiida/scheduler/plugins/test_slurm.py:862538^^^R^^^None^^^rosa10^^^user5^^^20^^^640^^^nid0[0099,0156-0157,0162-0163,0772-0773,0826,0964-0965,1018-1019,1152-1153,1214-1217,1344-1345]^^^normal^^^1-00:00:00^^^32:10^^^2013-05-23T11:41:30^^^longsqw_L24_q_11_0^^^2013-05-23T03:04:21
Binary file docs/source/images/AiiDA_transparent_logo.png matches

I guess line in bold is the offending one.

Nevertheless, it should work fine if you replace it by

*return self.dbnode.outputs.all()*

cheers

Fernando

**Comment by szoupanos** [comment]
@lekah 
Leo, can you please provide here some QB examples where you make use of these appender queries (_q relationships)?
My understanding (from the discussion that we had) is that some of the QB queries throw exceptions now.

**Comment by lekah** [comment]
There are no appender queries in the QB!

**Comment by szoupanos** [comment]
Pull request #409 fixes this problem.
Moreover the output, input, children and parents relationships are evaluated lazily now (please see the pull request for more information).

The user & dbcomputer relationships of DBNode were not turned to dynamic because SQLA doesn't allow 'dynamic' loaders to be used with many-to-one/one-to-one relationships.

**Comment by DropD** [comment]
Is there a reason for this to still be open?

**Comment by DropD** [comment]
closing, since I cannot reproduce the bug anymore.
