### ISSUE TITLE
verdi work tree shows also data and not only CALL links

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#316]
I think it should only instead show sub-calculations (i.e. follow CALL links)

To reproduce, run a simple wf (e.g. the sync example from the workflow) and then run ``verdi work tree`` after the workflow completes (and therefore returns some data).

**Comment by giovannipizzi** [comment]
See also issues #223 and #286

**Comment by muhrin** [comment]
The behaviour described by Gio above is already there in `verdi work status`.  To be discussed if we should just drop `verdi work tree` completely.

**Comment by greschd** [comment]
As a counter-point, I have been using ``verdi work tree`` a lot to quickly inspect my workflows, including checking the outputs.

**Comment by sphuber** [comment]
@greschd can you confirm whether with the current `verdi work status` and `verdi calculation status` you still see a use for `verdi work tree` and what added value do you see? If there is still a valid use for `tree` I would like to fix it and close this issue

**Comment by greschd** [comment]
No, I think with the new ``verdi work status`` the ``tree`` command is no longer needed.

**Comment by sphuber** [comment]
I would vote for just getting rid of `verdi work tree`. @muhrin objections to that?

**Comment by sphuber** [comment]
Fixed in #1299
