### ISSUE TITLE
node.out.<TAB> completion

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#317]
For workfunctions that don't return a dictionary but just a node, the output link is called ``_return``. Now, when using TAB completion on ``node.out.<TAB>``, the link is passed to ``dir()``, but things that start with an underscore are not shown by default by iPython (unless you start typing an underscore: ``node.out._<TAB>``, and then you see it).

Question: what is the best way to deal with this? Should we just suggest to people to always return a dict? I think we should not change the default behavior of the tab completion of ipython. On the other hand, if the user presses TAB and does not see anything, he thinks there is no output, and instead I think he should see it... 

Maybe we can call the default return always ``return`` rather than ``_return``? In the end it is not something really internal.

**Comment by sphuber** [comment]
The default return link has been renamed to `return` so that problem is fixed. However, the `out` method is still broken for example when going up to inputs which has multiple links. In that case a random one will be chosen, without warning.

**Comment by giovannipizzi** [comment]
Closing in favour of #2230
