### ISSUE TITLE
Improvements to the daemon-managed WorkChains needed

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#318]
We need to give the user the possibility to easily and clearly understand what the daemon is doing w.r.t. WorkChains.
Now, the only simple tool is ``verdi work list``, but has some shortcomings (shows also JobCalculations, is not sorted, limits by default the number of results, does not give a clear information on what the different WorkCalculations are, ...). 
Moreover, there should be a way to show only currently running WorkChains, by default (paralleling what ``verdi calculation list`` does).

**Comment by giovannipizzi** [comment]
I'm going to create a branch now and already commit a partial fix to the first part. I will branch off the tutorial_ts_jan branch, so that if modifications are minor, we can put the fixes in that branch.

**Comment by giovannipizzi** [comment]
We need now a way to know 
* if a WorkChain is running (and therefore show it) or not (and by default hide it). Is there such a field that we can query for?
* also, if would be good to know if the WorkChain was launched by the user, or it is a subWorkChain, so that by default we show only user WorkChains (and possibly subworkchains in a tree structure, like for the old workflows). Probably for this we just need to inspect the 'call' links?

**Comment by sphuber** [comment]
Changed the milestone to pre-1.0 release because more work on #318 needs to be done.

**Comment by sphuber** [comment]
I was trying to implement the `--project` option that exists for `verdi calculation list` in order to be able to specify which attributes the user wants projected, but I cannot figure out how to make this work in `click`. It supports multivalue options, but then the exact number needs to be specified through `nargs`. I cannot find anything on how to enable an unknown number of options.

**Comment by broeder-j** [comment]
Yes this is true. One solution I can think of is parsing a string like `--project 'pk uuid time'`? which you will split then split for spaces and create the project from the resulting list. this would also allow for projecting several times the same thing `--project 'pk uuid time pk label'`, which is currently not possible.

**Comment by sphuber** [comment]
Fixed in PR #888 
The `project` option was partially fixed by @vdikan  in a PR into develop
