### ISSUE TITLE
Put plum on pip

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#323]
Needed before releasing the next version of AiiDA and having ``pip install aiida`` work

**Comment by muhrin** [comment]
I've put in a support request at pypi to claim the 'plum' package name:

https://sourceforge.net/p/pypi/support-requests/697/

Still waiting for a response but from previous tickets it looks like they do get around to it eventually.
Worse case I'll call it something else.  Let me know if it gets to a point where we can't wait anymore.

**Comment by muhrin** [comment]
Done in pull request #397
