### ISSUE TITLE
Clean-up documentation from old stuff

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#325]
Work is happening in the [documentation branch](/aiidateam/aiida_core/tree/documentation)

- [ ] clean-up old docs
- [x] remove all documentation about SQLite and MySQL
- [x] clean up installation guide
- [x] remove documentation on the old QueryTool
- [x] Remove the old QueryTool code
- [ ] unify 'Modules' and 'aiida package'

**Comment by giovannipizzi** [comment]
For the installation guide on the Mac (tried on a clean 10.12 Sierra):

One often gets library errors with psycopg2. Beside what already written in the docs (add to the path the location of the pg_* executables, also suggested by the psycopg2 error message), I had to do the following:


1. install 'Interactive installer by EnterpriseDB'

2. cd /usr/local/lib

3. ln -s /Library/PostgreSQL/9.6/lib/libpq.5.dylib .
   ln -s /Library/PostgreSQL/9.6/lib/libssl.1.0.0.dylib .
   ln -s /Library/PostgreSQL/9.6/lib/libcrypto.1.0.0.dylib .

Note: `DYLD_FALLBACK_LIBRARY_PATH` would work, but then it doesn't work in subprocesses, e.g. when running 'make html' for the docs, because of the security features of the Mac.

**Comment by giovannipizzi** [comment]
Also, make sure that nowhere we refer to the `requirements.txt` or `optional_requirements.txt` that are removed in #348 (and also mention that, in case of need, they can be dynamically generated with the script in `utils/`)

**Comment by sphuber** [comment]
Already large parts, mostly installation and setup, are rewritten and updated to conform to the code. It has also been restructured. The new texts still need to be read by a second person and verified. Especially the parts specific to Mac OS X.

The rest of the documentation is in desperate need of restructuring, proof reading and where needed updating.

Here a representation of the new structuring with subsections that need to be proof read.
Check them when they are read and approved:

Installation
- [ ] Quick Install
- [ ] Optional configuration
- [ ] Virtual environment
- [ ] Database
- [ ] Verdi setup
- [ ] Installation requirements
- [ ] Troubleshooting
- [ ] Updating AiiDA from a previous version

Get started
- [ ] Starting the daemon
- [ ] Setup of the computers and codes

**Comment by szoupanos** [comment]
I had a quick look at readthedocs
http://aiida-core.readthedocs.io/en/latest/installation.html?highlight=requirements

And I did not see somewhere to be mentioned how we maintain an existing AiiDA installation.
In general requirements "evolve" (even within the same version of AiiDA). So when you have AiiDA 0.8.* and you checkout frequently the latest code from develop, new requirements might be added.

There should be a clear way how we can install these new requirements in an existing AiiDA installation without the need to install AiiDA from scratch.

(I hope you did not cover this topic and I missed it)

**Comment by sphuber** [comment]
The link you pasted is of course reflecting the develop branch and does not include my reorganization in the documentation branch, but I also don't remember seeing the section that you describe, nor have I written it. There is a small section that provides instructions for upgrading, but this only covers upgrades within different minor versions such as from 0.7.x to 0.8.x.

**Comment by szoupanos** [comment]
Oooops, sorry - I thought that it was already online.

Yes, the section on the needed updates for passing from one version to the other was written by me.

What I describe above is a bit different and was not really needed before (with the old installation method - before quick setup etc) because there was a requirements.txt file that we were supposed to keep up-to-date.

My understanding is that this file disappears now and can be generated by running a script.
This makes less clear how to keep requirements up-to-date in an existing AiiDA installation.

**Comment by giovannipizzi** [comment]
Fixed in #443
