### ISSUE TITLE
show list of plugins

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#330]
We have `verdi calculation plugins`. I think it is useful to add also `verdi data plugins`.
More generally, with the new plugin system, we might have a `verdi plugin` command, with a subcommand to show plugins for each entry point (data, calculation, workflows, ...) that are installed. 

Knowing the plugins that are available (and which string can be used to load them in the `*Factory` methods) is a very common question in the tutorial.

**Comment by DropD** [comment]
Do you agree that it would also be helpful to have access to such
functionality in the verdi shell?

Am 25.01.2017 10:44 schrieb "Giovanni Pizzi" <notifications@github.com>:

**Comment by giovannipizzi** [comment]
Yes, having both options (verdi command + verdi shell) is even better. If with tab completion, then it's perfect (for a functionality analogous to the data factory).
If you have ideas on how it would look like to the user, feel free to suggest.
E.g.: `DataFactoryCreator.ParameterData` etc. (with a better name, though?)

**Comment by DropD** [comment]
assigning to pre-1.0 because commandline will be revisited for that anyway

**Comment by giovannipizzi** [comment]
should be fixed, @sphuber please check

**Comment by sphuber** [comment]
Fixed in #2204
