### ISSUE TITLE
Sqlalchemy thread-safe session

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida_core#338]
Current usage of the SQLAlchemy session is not thread-safe. 
This hampers a safe usage of the new workflows that largely rely on multi-threading python libraries. 

One possibility would by to use the `scoped_session` proxy for `python session` which, when invoked returns always the same session within the same thread, but different ones within different threads.

See
[http://docs.sqlalchemy.org/en/latest/orm/contextual.html](http://docs.sqlalchemy.org/en/latest/orm/contextual.html)
and 
[http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#session-faq-whentocreate)](http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#session-faq-whentocreate)

This should achieve the main goal of having a common session within the same thread and separated sessions within different threads. This should be probably complemented by developing good practices for opening and closing the session at the right time. 

Finally, the session must be transparent to the user but we should define few good practices when writing asynchronous workflows such as not querying from one thread for objects which are being created by another thread.

**Comment by fernandogargiulo1986** [comment]
Some advancement has been achieved for QueryBuilder backed by Django. In this case, the session instantiated to work with aldjemy is now local. We tested that querying with querybuilder with pure SQLA as a backend works fine as long as no objects are written in the db.

**Comment by sphuber** [comment]
Threads are no longer being used, so this can be closed

**Comment by szoupanos** [comment]
Yes, and multiple sessions problems were addressed by using the scoped session.
