### ISSUE TITLE
verdi computer setup doesn't show defaults anymore

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#340]
This is essential, especially e.g. for the AiiDA work directory and the mpirun command, as people don't know that they can use e.g. `{tot_num_mpiprocs}` in the mpirun command (and I have at least one case where people hardcode there a static number).

**Comment by giovannipizzi** [comment]
Even more, for `verdi computer configure`, not having the defaults means that all the code that parses `~/.ssh/config` is not useful anymore. Instead, the defaults should be the ones read from there.

**Comment by DropD** [comment]
Cannot reproduce on current develop. Neither was the code for this changed as far as i know.

Please confirm that the bug persists.

**Comment by giovannipizzi** [comment]
You are right, probably it was a problem in my installation. I'm closing this.
