### ISSUE TITLE
ssh Bluegene issue

### ISSUE THREAD

**Issue by obgeneralao** [aiidateam/aiida_core#352]
On the part 
         ssh bgpfen squeue
    I  got an error:
              no squeue in (/usr/bin:/bin:/usr/sbin:/sbin)
However, when I do
        ssh bgpfen 'export PATH=/opt/slurm/bin:$PATH && squeue'
    It worked

On what part of  'verdi computer setup' and 'verdi computer configure COMPUTERNAME' can I insert 'export PATH=/opt/slurm/bin:$PATH ' ?

I thought it would be in 'Text to prepend to each command execution:' but it did not work.

When I do "ssh bgpfen 'echo $PATH' "
I got
/usr/bin:/bin:/usr/sbin:/sbin

But the full PATH in bgpfen is

/bgsys/drivers/ppcfloor/comm/bin/:/bgsys/drivers/ppcfloor/bin:/opt/slurm/lib:/opt/slurm/include:/opt/slurm/sbin:/opt/slurm/bin:
/opt/munge/lib:/opt/munge/include:/opt/munge/sbin:/opt/munge/bin:/home/fcparaan/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin
:/usr/games:/opt/gnome/bin:/opt/kde3/bin:/usr/lib/jvm/jre/bin:/bgsys/drivers/ppcfloor/bin:/opt/ibmcmp/xlf/bg/11.1/bin:/opt/ibmc
mp/vacpp/bg/9.0/bin:/opt/ibmll/LoadL/full/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/bgsys/drivers/ppcfloor/bin:/opt/ibmcmp/xlf/bg
/11.1/bin:/opt/ibmcmp/vacpp/bg/9.0/bin:/opt/ibmll/LoadL/full/bin

I am looking forward for your assistance

Thanks

**Comment by giovannipizzi** [comment]
Hi, 
AiiDA will always only do
`ssh bgpfen squeue`
so you need to make sure that the `export` command is properly done in your cluster (bgpfen) at login time.

This can be done by adding the command in the `.bashrc` and/or `.bash_profile` files in your cluster. If you need to know the difference between the two, and why instead it works if you just `ssh bgpfen` and then run `squeue` in the terminal, it's explained e.g. here http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html - I typically follow the recommendation at the end of the link, and put everything in `.bashrc`.

**Comment by obgeneralao** [comment]
I appreciate the reply.
It seems that  when i do `ssh bgpfen 'command'` it loads the etc/profile modifying ` .bashrc` and/or ` .bash_profile` or even `.profile` would not help at  all.

I will be contacting the sys ad of BG/P and see   what he can do


Thanks

**Comment by giovannipizzi** [comment]
Yes, good idea, he should be able to help. Anyway, one think I would check is whether the default shell is bash or something else - with bash, at least one of the files you mention should work.
