### ISSUE TITLE
Stucked on TOSUBMIT status

### ISSUE THREAD

**Issue by obgeneralao** [aiidateam/aiida_core#361]
Hi,

My `verdi computer test COMPUTER_NAME` was successful on 3 tests. Then I used the python script from  http://aiida-core.readthedocs.io/en/stable/_downloads/pw_short_example.py  and made some modifications.
It ran and returned a message "created calculation with PK=44". However when checking the job using `verdi calculation list` it got stucked on TOSUBMIT status. I am using slurm for job scheduler. 

Is there anything  that I should  look into?

By the way, a simple sbatch script would run in our cluster with no problem.

Thanks

**Comment by giovannipizzi** [comment]
Your daemon is probably not running. You must start with `verdi daemon start`. You can check it if is running from the first line of `verdi calculation list` (you should see a time smaller than ~30secs).

**Comment by obgeneralao** [comment]
Thanks a lot. :smiley: 
There is a lot that I need to learn on AiiDA. I am encountering more errors but I think its more on our cluster settings and the way my QE-codes were built.
