### ISSUE TITLE
Django QueryBuilder fails with datetime attribute

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#363]
```
c = Calculation()
now = timezone.now()
c._set_attr('now', now)
c.store()

QueryBuilder().append(Calculation, filters={'attributes.now': now}).all()
```
produces
```
  File "/home/martin/src/aiida_core/aiida/backends/querybuild/querybuilder_django.py", line 194, in _get_filter_expr_from_attributes
    elif isinstance(value_to_consider, datetime.datetime):
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
```

**Comment by fernandogargiulo1986** [comment]
Have you tried
```python
QueryBuilder().append(Calculation, 
                         filters={'attributes.now': {'==': now}}).all()
```
?

I am not sure if this can be the problem, but this is the way I would write down the query

**Comment by muhrin** [comment]
No, it doesn't help because the problem was caused by a mistake in imports in `querybuilder_django.py` line 8:
```
import datetime
from datetime import datetime
```
I have it fixed already (yet to commit).

BTW, as far as I know `'something': {'==': x}` is always equivalent to `'something': x`, IMHO the latter should be preferred as it's less typing and closer to the MongoDB convention which inspired parts of the QB (although I know this is not what the docs show).

**Comment by muhrin** [comment]
Also, do you know what the final story for datetime values in attrbitues was for SQLA?  I remember the student spending a lot of time on this.  As it stands I'm not sure it works.

**Comment by fernandogargiulo1986** [comment]
where do you import timezone from? django.utils or aiida.utils?

**Comment by muhrin** [comment]
`aiida.utils`

**Comment by lekah** [comment]
Yes, 'something': {'==': x} is always equivalent to 'something': x!
@muhrin In which branch did you fix it? If it is from develop, could you let me do this, as there will be merge conflicts otherwise? I can do it now, and this will become part of #351

**Comment by lekah** [comment]
The story of datetime values as attribute in the JSON-field is not concluded.

**Comment by lekah** [comment]
Update: #351 fixes this. This has been already done before (I  just forgot), so please refrain from committing.

**Comment by muhrin** [comment]
Cool, thanks man.  I added a test for this and fixes PEP-8 formatting issues in `querybuilder_django.py`.  Do you think it would be possible to merge `develop` on `https://github.com/muhrin/aiida_core.git` into your pull request?

If not, no worries, I'll hold off and do the merge later.

**Comment by muhrin** [comment]
On, and one other thing, line 13 in `querybuilder_django.py` needs `String` added to the group of things imported, so it becomes:
```
from aiida.backends.querybuild.sa_init import (
    and_, or_, aliased,  # Queryfuncs
    cast, Float, String, case, select, exists
)
```
otherwise line 117 (`mapped_entity = cast(mapped_entity, String)`) will fail.

**Comment by lekah** [comment]
Thanks, I added this line. I will update the pull request (just this line and a test). 
The merge will  fail, if it's just formatting issues I would prefer holding them back. The additional tests can be merged. @fernandogargiulo1986 or @giovannipizzi could you please review #351 so that these bugs are fixed in the develop? The longer we wait the more conflicts there will be.

**Comment by fernandogargiulo1986** [comment]
I checked-out PR #351 .Currently running some scripts performing some intensive usage of QueryBuilder.
