### ISSUE TITLE
QueryBuilder differentiate between an attribute existing and being None

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#364]
Currently `filters={'attributes.[whatever]': None}` will give back all the nodes that either have the attribute and its value None or don't have the attribute at all.  These are two logically distinct cases that should not be equated.  I currently have a use case that needs this behavior for the new daemon.

Suggestion:
Add an `exists` operator a la [MongoDB](https://docs.mongodb.com/manual/reference/operator/query/exists/#op._S_exists) so we can properly ask the two questions:
`filters={'attributes.[whatever]': None}` and 
`filters={'attributes.[whatever]': {'exists': [True or False]}}`

Happy to help, just let me know if adding this will break anything.  If not I'm happy to implement it.

**Comment by lekah** [comment]
We decided that this is the functionality we want, i.e. asking for None will also return values where there is no such key (I tried to stay as close to SQLAlchemy as possible).
What you need already exists as a functionality, but with a different syntax than you propose:
`
filters={'attributes': {'has_key': 'whatever'}}
`
If you want to check that something exists as a key and stores None as value:
`
filters={'attributes': {'has_key': 'whatever'}, 'attributes.whatever':None}
`
Let me know if that works.

**Comment by lekah** [comment]
We decided that this is the functionality we want, i.e. asking for None will also return values where there is no such key (I tried to stay as close to SQLAlchemy as possible).
What you need already exists as a functionality, but with a different syntax than you propose:
`
filters={'attributes': {'has_key': 'whatever'}}
`
If you want to check that something exists as a key and stores None as value:
`
filters={'attributes': {'has_key': 'whatever'}, 'attributes.whatever':None}
`
Let me know if that works.

**Comment by muhrin** [comment]
Thanks man, much appreciated.

I don't think this choice is the right way to go.  Having looked more deeply at SQLAlchemy I'm not at all impressed by a lot of design choices they made and I'm not don't think we should use them as an exemplar (except perhaps on how not to do things).

Here's my rationale for this case:  `None` is a valid value just as, say, `5` so when I say make a statement like "Is variable `x` equal to `None`"?  I'm actually making a statement and a question 1) `x` exists, *and*, 2) its value is equal to `None`.

Note, this is the behaviour of dictionaries in all languages I know (not sure about JavaScript actually) e.g.:
```
x = {'a': None}
'a' in d # True
x['b'] == None  # Assertion
```

Personally I would vote for changing this.

Back down to earth, the thing I want to accomplish is (using a `dict` as an example)
`'whatever not in d or d['whatever'] < 'some_value'`
Can I ask if something `has_not_key` at the moment?

**Comment by lekah** [comment]
Yes, we can discuss in one of the meetings maybe, I'm not against changing things if it improves clarity. I was maybe too focused on SQLAlchemy's syntax

As for your example:
`
filters={'or':[{'attributes': {'!has_key': 'whatever'}}, {'attributes.whatever':{'<':val}}]}
`
If you precede any operator with "!" it becomes the negation.
Check if not(d['whatever'] >= 'some_value') also works, would make writing the query easier.
`
filters={'attributes.whatever':{'!>=':val}}
`

**Comment by muhrin** [comment]
Thanks a lot for this Leo, really appreciate the help.
