### ISSUE TITLE
Fixes in install documentation: --user option in pip, missing links, virtual env, various things

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida_core#374]

**Comment by nmounet** [comment]
For the --user option in pip, add also a direct link to point to the end of the section where there are additional comments about this.
Also, one should maybe mention that after the "pip install -e ..." command, a folder of name "aiida-core" will be created inside the specified folder.

**Comment by fernandogargiulo1986** [comment]
Actually the ``-e`` option means *editable* mode , that is, the aiida package is an egg link that points to the actual repository so that changes in the latter will be reflected automatically in the AiiDA installation.

In general, only  those who are interested in developing AiiDA should use this option

**Comment by nmounet** [comment]
This option looks then extremely dangerous too me... even as a developer I would probably not use it.
So let's take it away?

**Comment by fernandogargiulo1986** [comment]
actually as a developer you do not really have the choice not to use it. But I agree that this should not be the default (maybe we mention it in a note)

**Comment by nmounet** [comment]
Sorry I misunderstood the point from the beginning with the 'pip install -e.'
So: with the -e option, any change you make to the code gets reflected in the all classes, verdi commands, etc.
While without it, you would not see any effect of any modification, which is a quite weird behaviour.
So probably, I would rather maintain it, it does not harm, even for a standard user (who typically also modifies small stuff every now and then, and will then assume it has an effect on what he runs! on similar grounds, look how unnatural it is that we have to restart the daemon to reflect any changes in the code of legacy workflows...)

**Comment by nmounet** [comment]
A few other things concerning the install documentation to be added / corrected: 
- some sort of quick help about virtual environments would be VERY beneficial, because if you do not know how it works you are rather lost. Actually there is something in the "Developers" section of the doc, we should at least link it within the install section,
- instructions on how to uninstall AiiDA (removal of ~/aiidapy is enough, from what I understood from Sebastiaan),
- replace "pip install -e git+https://github.com/aiidateam/aiida_core.git#egg=aiida_core [...]" with "pip install -e .[ extra requirements>] [...]" , done from the directory where you previously cloned the repository (see Fernando's instructions),
- the QuickStart section contains too few information (e.g. what "verdi quicksetup" does, etc.),
- missing instructions for updating, i.e. when you already have a db and profile configured in .aiida/config.json.
- verdi quicksetup or verdi quickinstall?

**Comment by nmounet** [comment]
The line to add to the .bashrc is
export PATH="${PATH}:~/aiidapy/bin
and not
export PATH="${PATH}:~/aiidapy/bin/verdi

**Comment by fernandogargiulo1986** [comment]
I actually sent my installation guide to Rico. He will probably pick up the relevant parts and integrate them into the documentation. Actually, my guide refers to a "developer installation".

**Comment by nmounet** [comment]
Still, there are things in your installation guide that are needed for a standard user installation, for instance, if you do not specify "verdi_shell" in the extra requirements, you end up with this terrible python shell and you do not understand what's happening.
Another option is to put the verdi shell in the default requirements. I don't see how any user could work with AiiDA without a shell...

**Comment by nmounet** [comment]
About migration:
- explain how to update from a very old AiiDA version (e.g. if you are at 0.5, you should first install 0.6, then migrate, then install 0.7, then migrate, then install 0.8, then migrate).
- the corresponding migration scripts have moved, they are not any more in the location indicated in the docs.

**Comment by nmounet** [comment]
See also issue #385 about PYTHONPATH.

**Comment by DropD** [comment]
Please have a look at the most recent updates in
https://github.com/DropD/aiida_core/blob/fix-374/docs/source/installation.rst
.

Note mainly the following changes:

* CHANGED: sections are reordered for better sidebar navigation (deeper
hierarchy)
* ADDED: FAQ section with info about virtualenvs and why we recommend them
* ADDED: all install types recommend cloning the repo and pip install -e
aiida_core[ssh,verdi_shell,REST] into a virtualenv at least
* EXTENDED: verdi quicksetup and setup mini reference
* ADDED: update 0.7 -> 0.8 section

Cheers,
Rico

**Comment by DropD** [comment]
Since there are no comments i will create a pull request.
