### ISSUE TITLE
docs: migrate 0.7 -> 0.8:

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#381]
1. install 0.8 in a virtualenv (because we are pinning versions)
2. undo all path changes to bashrc to add verdi and aiida-run
3. optionally alias verdi and aiida-run to the ones installed in the virtualenv
4. rerun verdi setup (to recreate aiida_daemon.conf)

**Comment by nmounet** [comment]
worked for me (even without following the recommendations in issue #382)

**Comment by DropD** [comment]
Am I right to assume that verdi setup actually runs the database migration? Otherwise,
5. run the migration command
should be added.

**Comment by nmounet** [comment]
'verdi setup' seems indeed to run a migration command. At least the db migration, not sure about the config files migration.
