### ISSUE TITLE
daemon should run in the correct virtualenv when multiple profiles are supported

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#382]
change the daemon file template (in aiida/common/setup.py) as follows:

command = {python} -m celery ...
replace {python} with sys.executable

**Comment by DropD** [comment]
Also, maybe it makes sense to remove the

user={local_user} line in the same pull request, even though it's not directly related.

The reason for this is that apparently {local_user} is sometimes not the same user that supervisor is supposed to change to, causing it to fail.

**Comment by DropD** [comment]
Actually, we can inject the current virtualenv's bin path into the environment used by the subprocess call in verdi daemon start. This way the daemon running will always be the one belonging to the instance of verdi it was called through.

**Comment by giovannipizzi** [comment]
PR #450 will solve this for the current version (0.8.0) of AiiDA: anyway supervisor is run from 'verdi daemon run', so we just need to make sure that the correct 'bin' folder is added to the PATH before running supervisor from subprocess.

**Comment by giovannipizzi** [comment]
In the meantime, I move this to the next release, and I describe what should happen next:
- we enable the possibility of running more daemons on different profiles at the same time, and each profile should be associated with a specific virtualenv.
