### ISSUE TITLE
jupyter cannot work with AiiDA if PYTHONPATH is not properly set

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida_core#385]
In a jupyter notebook opened from the virtual environment, the command

import aiida

will fail if one does not properly set up the PYTHONPATH ("export PYTHONPATH=${PYTHONPATH}:<AiiDA_folder>") . But the installation instructions do not mention any need to change the PYTHONPATH...

As a side comment, do we need to change the PATH (to point to the correct "verdi") each time we switch virtual environments?

**Comment by nmounet** [comment]
Actually, jupyter does not find itself in the right environment, apparently. I need to put the local python packages of the environment in the PYTHONPATH:
export PYTHONPATH="/home/aiida/aiidapy/local/lib/python2.7/site-packages:${PYTHONPATH}"

**Comment by DropD** [comment]
I strongly suspect you are using a jupyter which is not installed in your environment.
Please look at the output of `which jupyter`.
If it is not "<aiidapy-env-base-folder>/bin/jupyter", then activate your aiidapy environment and pip install jupyter. Run `which jupyter` again, if it points to an executable inside the environment, it will work without any changes.

Maybe we should add jupyter to extras_require['verdi_shell'] (or 'verdi_notebook'?)

**Comment by nmounet** [comment]
which jupyter -> /home/aiida/.local/bin/jupyter

Then, after pip install jupyter from aisde the env.:
which jupyter -> /home/aiida/aiidapy/bin/jupyter

and then no need to define the PYTHONPATH. So you are right.
I did not expect that one has to re-install every python-using software from inside  the virtual env... I suggest indeed that we put it in the extra requirements.

**Comment by nmounet** [comment]
The best would be a new "verdi notebook" command that would take care of loading the aiida_magics extension. And then a 'verdi_notebook' extra requirement would make sense.

**Comment by DropD** [comment]
fixed by #451
