### ISSUE TITLE
docs: Have a list of "extras" (install options)

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#388]
There should be a list of optional features that can be given when installing aiida, as in 
`pip install -e .[OPTION1,OPTION2]`.

the following information should be given
option name, description, notable dependencies, target audience (?)

Important: This should be linked prominently in the install docs!

**Comment by nmounet** [comment]
Default should be: verdi_shell, ssh
The rest would be optional.

**Comment by giovannipizzi** [comment]
Fixed in #443
