### ISSUE TITLE
Optimisation of AiiDA database queries for big databases

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#390]
In this issue we improve the performance of AiiDA database queries that have been observed to be slow in big databases. For the moment, the issues are:
- Slow daemon queries
- Slow workflows when using the old workflow manager
- Slow "verdi calculation list"

The above issues have to be seen and if possible to be fixed either at the database level or at the python level.
They should be looked at for both backends.

Spyros

----

- [x] Daemon queries / Django
- [ ] Workflows when using the old workflow manager / Django
- [ ] "verdi calculation list" / Django
- [ ] Daemon queries / SQLA
- [ ] Workflows when using the old workflow manager / SQLA
- [ ] "verdi calculation list" / SQLA

**Comment by ltalirz** [comment]
This is just some input from a particular use case (materialscloud). In the current version of materialscloud, we have

* size of all dbs as reported by postgresql: ~6GB
* size of .sql dump: 2.4GB
* size of compressed dump: 468MB

I also attach the output of the [Index size/usage statistics](https://wiki.postgresql.org/wiki/Index_Maintenance#Index_size.2Fusage_statistics) query, which seems to indicate that the size of the indices (when summed up) is significantly larger than the size of the actual tables.
The file also shows how often the indices were used (some of them aren't used at all).
Of course, this is may be just a very particular usage pattern (materialscloud), but perhaps this information can be useful.

[db_indices.txt](https://github.com/aiidateam/aiida_core/files/1369405/db_indices.txt)

**Comment by szoupanos** [comment]
@ltalirz 
Thanks for these comments

**Comment by giovannipizzi** [comment]
This should be fixed - at least decide what is urgent, and make another issue for things that we need to solve in a later release

**Comment by szoupanos** [comment]
I think that this discussion is old enough. My understanding is that the current optimization goals should be the group addition for SQLA, import/export optimization and Django conversion to JSONB

**Comment by giovannipizzi** [comment]
Ok, if it's old please close and open a new updated issue.
