### ISSUE TITLE
'verdi setup' always prompts info about the user even if he found it already in the db

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida_core#395]
When doing the setup from an existing dabase, in the end the user info are still asked, even if the user email was found already earlier:

Starting user configuration for nicolas.mounet@epfl.ch...
First Name: Nicolas
Last Name: Mounet
Institution: EPFL
An AiiDA user for email 'nicolas.mounet@epfl.ch' is already present in the DB:
Do you want to reconfigure it? [y/N]: n

I presume that if the user puts slightly different info, a new user be created automatically, which typically one wants to avoid.
Can't we simply ask BEFOREHAND if one wants to reconfigure the user, to avoid messing it up?

**Comment by sphuber** [comment]
Duplicate of #899
