### ISSUE TITLE
files to deploy aiida with apache outdated

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida_core#415]
The file wsgi.py present in aiida.backends.djsite.settings refers to the old restapi based on django.

We could update it consistently to the new restapi and move it to the right folder. Documentation and requirements  should be updated consistently.

**Comment by fernandogargiulo1986** [comment]
The file has been removed and the related  documentation too. Still we might want to add it correspondingly to the new restapi

**Comment by giovannipizzi** [comment]
Also, remove 'runserver' both from 'verdi runserver' and from documentation (it looks it reappeared in #443)

**Comment by waychal** [comment]
@giovannipizzi This wsgi file contains the configuration to run django application under apache. I guess this is outdated and not used anywhere.
For this there is some documentation available in docs/source/working_with_aiida/aiida_multiuser.rst.
Can you please confirm this? If yes I will remove both file and documentation.

**Comment by giovannipizzi** [comment]
Yes, please remove also `docs/source/working_with_aiida/aiida_multiuser.rst`

**Comment by sphuber** [comment]
Fixed in PR #2293
