### ISSUE TITLE
Convert input validation to use voluptuous exclusively

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida_core#418]
Instead of having, e.g.:
```spec.input('max', valid_type=int, default=4, required=True)```

put all the 'schema' validation in, e.g., the `validator` parameter which calls through to the voluptuous library:
```spec.input('max', validator=Required(int, default=4))```
which internally would be doing `Schema(Required(int, default=4))`

**Comment by sphuber** [comment]
Voluptuous has actually now been completely removed in favor of custom validation methods
