### ISSUE TITLE
Fix vary_rounds warning

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#460]
Is it something quick that we can fix for 0.8?

**Comment by DropD** [comment]
Yes, in aiida/common/hashing.py:41 there is a kwarg `all__vary_rounds=0.1`.

I have in the past experimentally commented this line with no adverse effects.

According to passlib it has been deprecated and is deemed not very effective security wise. From the changelog:

> The vary_rounds option has been deprecated, and will be removed in Passlib 2.0. It provided very little security benefit, and was judged not worth the additional code complexity it requires.

**Comment by szoupanos** [comment]
We should have a look if aiida_core/aiida/common/hashing.py (and the related code to this) is needed anymore.
I added it to detach a password hashing mechanism that we had from Django (it also may have a few lines "inspired" by Django)

**Comment by giovannipizzi** [comment]
Indeed, I agree. Spyros, if for the time being we still need this, can you add the file to the open_source_licenses.txt file where we mention the files inspired by Django?
