### ISSUE TITLE
ToContext should provide option to append result to a list in the context

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#463]
A common use case within a WorkChain is to launch multiple sub WorkChains of the same type in some sort of a loop construct. Currently the ToContext class provides no other way to assign these different results than to use different context keywords, for example by suffixing it with an index. This approach is error prone and semantically it makes more sense to store the results in a list, which can then later be addressed through the context. We should implement a sort of Append class that can act as a wrapper around the sub WorkChain future. For example

    for i in range(x):
        running = submit(SubWorkChain, **parameters)
        ToContext(subchains=append(running))

which can then be addressed in another WorkChain step in the following way:

    for index, subchain in self.ctx.subchains.iteritems():
         print subchain.get_outputs_dict()

**Comment by sphuber** [comment]
This functionality was implemented, but was done in an experimental branch that also included many other changes that were not ready for merging into develop, preventing this functionality from being merged into develop. Since it is important functionality I have backported it into a branch that branched of the release-0.9.0rc3 branch.

These changes are purely adding a feature and the user interface of Workchains remain unchanged. Any changes that were required in plum were temporarily added in the AiiDA branch to prevent having to update the plum version. This way it should be relatively easy to merge the feature branch into a release-0.9.1 branch

**Comment by broeder-j** [comment]
Thanks Sebastiaan! For everybody else: the work around so far was to parse a dict to ToContext. so create 'labels' and access them. This would spam you context for larger workflows and you have to be careful not to overwrite any of these context variables.

**Comment by sphuber** [comment]
This was implemented and merged
