### ISSUE TITLE
SQLA backend: there are still some failures in the connections in the logs...

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#468]
It looks that (even with the fixes of #467), there are still some (rare) errors in the logs.
See for instance this:
https://travis-ci.org/giovannipizzi/aiida_core/jobs/213615401#L1636
This error has appeared in at least a few runs in travis, so seems to be reproducible (at least for the timings of the test that is run, changing them might change the behaviour).

The reason is still not clear to me, and needs probably further investigation before declaring SQLA out of the 'experimental' phase

**Comment by sphuber** [comment]
Has not been reported in a long time, closing for now
