### ISSUE TITLE
Magic function %aiida does not work in virtualenv

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida_core#480]
The magic function ``%aiida`` calling a function contained in ``aiida.common.ipython.ipython_magics`` is used from within ipython to reproduce the same environment as verdi shell. It is also needed to put these lines

```python
c = get_config()
c.InteractiveShellApp.extensions = [
        'aiida.common.ipython.ipython_magics'
]
```

in the file ``~/.ipython/profile_default/ipython_config.py``.

Useless in ipython (you could have directly opened a verdi shell), %aiida is essential to correctly aiida-initialize Jupyter notebooks.

Now that AiiDA should be used only in a virtualenv, the standard installation re-installs ipython in the virtualenv and  ``~/.ipython/profile_default/ipython_config.py`` is no longer loaded loaded.

I do not manage to see where is the equivalent of this file in in a virtual env.

**Comment by fernandogargiulo1986** [comment]
Update:

``%aiida`` works if I start jupyter from the of the top of the tree of the aiida source code.

Ex.

```bash
cd ~/aiida_core

ll
total 148
drwxrwxr-x 11 gargiulo gargiulo  4096 Mar 24 10:15 ./
drwxrwxr-x  4 gargiulo gargiulo  4096 Feb  3 11:21 ../
drwxrwxr-x 16 gargiulo gargiulo  4096 Mar 21 09:41 aiida/
drwxrwxr-x  2 gargiulo gargiulo  4096 Jan 18 11:17 aiida.egg-info/
-rw-rw-r--  1 gargiulo gargiulo  1865 Mar 16 17:53 AUTHORS.txt
drwxrwxr-x  2 gargiulo gargiulo  4096 Feb  2 12:15 bin/
-rw-rw-r--  1 gargiulo gargiulo  9788 Jan  9 14:44 CHANGELOG.txt

jupyter notebook
```

**Comment by DropD** [comment]
i am not sure if jupyter will ever load an ipython profile by default.

run jupyter --paths for an overview of where jupyters config files are.

I have no experience with ipython magic and I won't have time to look deeper into this before august, Please reassign to someone else.

**Comment by fernandogargiulo1986** [comment]
The point is to have the ipython kernel used by jupyter to be started from the virtualenv,

To achieve this:

1. it is not even needed to install `jupyter` inside the virtual environment
2. Instead, from inside the virtual environment run: `pip install ipykernel`
3. From within the virtualenv, run 
```python -m ipykernel install --user --name=aiida_venv```
 optionally replacing `aiida_venv` with the name you want to assign to this kernel
4. Once you start `jupyter` (no need to be in the venv), open a notebook and choose from the menu `kernel->change kernel->aiida_venv`, where the last option will be the name chosen at point 3.
