### ISSUE TITLE
verdi calculation list much slower after update

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#497]
For my database I see an increase in the query time by 2 orders. Some searching related this to the new ways the calculation states are queries, which changed with commit e162de663c7e9011063d6c6b46ecc9b2b0079bf0.
I've attached the query plans for the two queries, produced before and after this commit (
[query-plans.sql.txt](https://github.com/aiidateam/aiida_core/files/902792/query-plans.sql.txt) ).

**Comment by szoupanos** [comment]
This should be related to #467 and how the state is now calculated.
