### ISSUE TITLE
orm.data.base missing in module documentation

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#501]
The ``orm.data.base`` module is missing in the documentation page for ``orm.data``. As a result, it is not possible to find these Data classes except by looking through the code. In my opinion, the base class itself doesn't need to be documented, but ``Float``, ``Int``, ``List`` etc. should be since they might be used in user code.

**Comment by giovannipizzi** [comment]
Its' now there http://aiida-core.readthedocs.io/en/latest/orm/dev.html#module-aiida.orm.data.base thanks to 0e11f352e2f661
