### ISSUE TITLE
Add in documentation how to make jupyter aware of aiida virtualenv

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida_core#516]
follow comment at issue #480

**Comment by fernandogargiulo1986** [comment]
For cross-check look at this 

http://help.pythonanywhere.com/pages/IPythonNotebookVirtualenvs

**Comment by broeder-j** [comment]
Why not just start jupyter in the aiida virtualenv?

**Comment by giovannipizzi** [comment]
We had at least one usecase where this wouldn't work.
But you are right.
I think that we should document both approaches and explain pros and cons of each.

**Comment by fernandogargiulo1986** [comment]
Fixed by pull request  #575
