### ISSUE TITLE
Running the tests with sqlalchemy erases all the users in the test-DB

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#526]
When running the tests in a profile configured with the Django-Backend, the users are not affected.
For a sqlalchemy test profile, the test erases the user. 
The expected behavior is (my opinion) that the users that were created during install (default user) are not being deleted. So best to never delete the user.

**Comment by sphuber** [comment]
The new policy is that the test database is wiped of all content and when tests are run, the database is populated with the required content. This should now be consistent for both backends
