### ISSUE TITLE
Export relies heavily on DbPath and model specific queries.

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#552]
We need to replace the DbPath with recursive queries ( see #258 ). The export functionality heavily uses the DbPath for queries written with the model-classes. As far as I can see, the QueryBuilder has all the needed functionality to deal with the necessary queries in an agnostic way. If this can be implemented, we would reduce the necessary code and make the export more robust and easier to change in the future.

**Comment by lekah** [comment]
With 02a4c73 one in principle has a backend-agnostic way to get all the information for the export. There is still a bit to do because of the django_to_sqla_schema etc things, but this should be easy for someone who knows what the keys need to be.

**Comment by szoupanos** [comment]
Thanks Leo!

2 fast comments/questions:
- If we don't explain in the QB documentation how to write link queries, maybe it is a good moment to do it now.
- Why did you have to rewrite part of the Django export method? I understand that the children relation is based on the DbPath table and the outputs on the DbLink table (and this is the reason why you created get_all_parents_dj). Does this mean that the children relation does not exist at all? My understanding was that it will exist but it will be computed on the fly.

**Comment by lekah** [comment]
Regarding the first comment: There is some documentation on these features: http://aiida-core.readthedocs.io/en/latest/querying/querybuilder/usage.html?highlight=edges
If this is not enough, I would put that into a new issue.
Your second comment is a bit hard to interpret. Some points
 - A children relationship on the backend-orm level will not exist any more, if we merge the branch tc_wo_dpbath. You will have to use the QueryBuilder for now. I don't think it's possible to implement this CTE with Django, and if it is, it will be nightmare.
 - I rewrote the Django part because it was very hard to understand what the export_tree_sqla is doing exactly, mainly due to all the schema_dependant dictionaries. 

This pull request is only about making all the queries no longer rely on the DbPath. After that (in a separate issue) we can focus on making one nice backend-agnostic export_tree function that does everything for us.

**Comment by szoupanos** [comment]
Thanks for the query builder link on the edges. I missed this.
Yes, we can have a better look at the DbPath pull request (how it is/will be implemented the TC and the changes at the schema).
If the import/export tests are passing (and they are as I see at #554) I think that it is OK for now.
