### ISSUE TITLE
kill method for SGE scheduler

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#59]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

The kill method has now been implemented for calculations, that in turn refers to the scheduler kill method (see commit ab7afb9).
The SGE scheduler now therefore lacks a kill implementation.
Most probably, this is identical to the PbsPro one, but this has to be tested.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/59

**Comment by DropD** [comment]
Pull request #549 seems to have implemented this sucessfully. Closing this
