### ISSUE TITLE
The ASE parser appears not to work

### ISSUE THREAD

**Issue by RKBK** [aiidateam/aiida_core#593]
When running a calculation through the ASE interface, I get the following message in the log:

```
*** 1 LOG MESSAGES:
+-> ERROR at 2017-06-15 14:48:56.481161+00:00
|   Error parsing calc 108. Traceback: Traceback (most recent call last):
|     File "/home/rasmus/Programs/aiida/aiida_core/aiida/daemon/execmanager.py", line 826, in retrieve_computed_for_authinfo
|       successful, new_nodes_tuple = parser.parse_from_calc()
|     File "/home/rasmus/Programs/aiida/aiida_core/aiida/parsers/plugins/ase/__init__.py", line 50, in parse_from_calc
|       from aiida.backends.djsite.utils import get_dblogger_extra
|   ImportError: No module named djsite.utils
```

The weird thing is that I can run the command 
```
from aiida.backends.djsite.utils import get_dblogger_extra
```
in a normal python interpreter just fine.

**Comment by RKBK** [comment]
I should note that it happens after applying this change:

https://github.com/aiidateam/aiida_core/pull/592

**Comment by giovannipizzi** [comment]
Hi,
did you restart your deamon? And is it possible that your Damon is using a different version of AiiDA, for some reason? E.g., is this `/home/rasmus/Programs/aiida/aiida_core/` the path you expect?

**Comment by RKBK** [comment]
Of course, @giovannipizzi , I didn't realize I had to restart the daemon! I restarted it and now it worked:

```
*** 2 LOG MESSAGES:
+-> ERROR at 2017-06-16 06:59:51.394952+00:00
|   Standard output not found
+-> ERROR at 2017-06-16 06:59:51.421193+00:00
|   [parsing of calc 114] The parser returned an error, but it should have created an output node with some partial results and warnings. Check there for more information on the problem
```

So I think the merge request I submitted actually was needed to get it to work.

(of course, now I need to figure out the problem that ASE-Espresso doesn't seem to get launched properly on the cluster, but that's another issue)
