### ISSUE TITLE
Remove or properly link to plugin documentation for all references of Quantum ESPRESSO in the docs

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#607]
In #601 all the Quantum ESPRESSO plugin code has been migrated from aiida-core to the aiida-quantumespresso package. The relevant doc files have also been migrated, but there might still be some stale references. In addition, where applicable, useful links to the plugin and its docs should be made

**Comment by giovannipizzi** [comment]
Working on it, already reactivated docs for aiida-quantumespresso (http://aiida-quantumespresso.readthedocs.io/en/latest/)
