### ISSUE TITLE
Installation crashes with non-default email

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#611]
I provided an email different from the default one, which makes the installation crash due to an AttributeError.
We are using an instance method there which does not exist!
`
  File "/home/kahle/.virtualenvs/aiida-production-liscreen1/local/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 598, in setup
    User().user_configure(email)
AttributeError: 'User' object has no attribute 'user_configure'
`

**Comment by DropD** [comment]
It seems that the `aiida.cmdline.commands.user.User.user_configure` has been refactored into a click command without updating `setup`

**Comment by DropD** [comment]
It looks like the offending line has been changed about three months ago. Can anyone still reproduce this with 0.9.1?
