### ISSUE TITLE
verdi user configure crashes

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#612]
If I configure an imported user, aiida (current develop) crashes with cryptic messages:

`  File "/home/kahle/.virtualenvs/aiida-production-liscreen1/local/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
TypeError: configure() got multiple values for keyword argument 'email'
`

**Comment by sphuber** [comment]
Is this still an issue or is this a duplicate of one of the `verdi user` and `verdi setup` related bugs that were fixed recently

**Comment by ltalirz** [comment]
I was working on the documentation until a few minutes ago. I'll have a look into it now.

**Comment by ltalirz** [comment]
@lekah Could you give me a set of commands to follow in order to reproduce your error?

In #823 I now added tests for verdi user configure (some fixes were needed), but perhaps there is some cornercase that I am not catching.

**Comment by lekah** [comment]
@ltalirz It must have been fixed, I can't reproduce the error! Tried really hard :(

**Comment by ltalirz** [comment]
Terrible times ;)

**Comment by sphuber** [comment]
Fixed in PR #823

**Comment by sphuber** [comment]
Thanks Leo^2
