### ISSUE TITLE
unidentified issue with ssh connect string

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#626]
This concerns the [string](https://github.com/aiidateam/aiida_core/blob/6447da598abbcf1619e13bd8e20964a2b3e26f23/aiida/transport/plugins/ssh.py#L1394)  used by verdi for connecting to another computer via ssh.

```
connect_string = """ssh -t {machine} {further_params} "if [ -d {escaped_remotedir} ] ; then cd {escaped_remotedir} ; 
bash -l ; else echo '  ** The directory' ; echo '  ** {remotedir}' ; echo '  ** seems to have been deleted, I logout...' ; fi" """.format(
  | further_params=further_params_str,
  | machine=self._machine,
  | escaped_remotedir="'{}'".format(remotedir),
  | remotedir=remotedir)
```
Benedikt Ziebarth reported a problem connecting to a Red Hat Enterprise Linux Server (release 7.3) and fixed the issue, curiously, by escaping the whitespace in the  `echo` statements, i.e.
````
connect_string = """ssh -t {machine} {further_params} "if [ -d {escaped_remotedir} ] ; then cd {escaped_remotedir} ; 
bash -l ; else echo '\ \ **\ The\ directory' ; echo '\ \ **\ {remotedir}' ; echo '\ \ **\ seems\ to\ have\ been\ deleted,\ I\ logout...' ; fi" """.format(
````

I personally understand neither why the issue arises nor why escaping the whitespaces fixes it.
I do wonder, however, whether it is a good idea to use `{remotedir}` instead of `{escaped_remotedir}` in the `echo` statement. What if the name of the directory includes apostrophes?

Anyhow, I just deposit this issue here for reference in case it turns up for anyone else.

**Comment by ltalirz** [comment]
For the moment, let's just make sure that `remotedir` and `escaped_remotedir` are properly escaped:
Probably, `remotedir` should be escaped using `escape_for_bash` but be careful about usage inside single/double quotes.
When finished, add a test!

**Comment by astamminger** [comment]
@ltalirz Since this is a very special topic, most likely due to our internal IT infrastructure, I will close this  issue for now. However, I will check if this problem persists with upcoming AiiDA releases and will re-open the issue if this is the case.
