### ISSUE TITLE
InlineCalculation output is always stored with linktype Return

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#628]
The data instances outputted by an Inline Calculation are stored as "returned" by the inline calculation. However they have to be created by the InlineCalculation (otherwise there's an exception when storing the result).
Now, if we enforce that data returned by an inline calculation is created by this inline calculation, it means that inline calculation preserve the directed acyclic graph (DAG)! 
But we will not be able to take this into account when querying, because return links cannot be part of a DAG (DbPath table or recursive query function). Now, I would therefore argue to make the default linktype (since there's only one now) a Create-Link! This means that we can go through ancestor-descendant relationships via InlineCalculations.

**Comment by nmounet** [comment]
I agree that the returned objects of an InlineCalculation should be linked with "create links", because we really need to be able to do recursive queries for these.
