### ISSUE TITLE
verdi work kill needs to be implemented

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida_core#661]
currently submitted work chains/Processes are unkillable. or at least not straight forward.
(correct me if I am wrong). Maybe one can use the self.abort() method for this verdi command, or use how this is implemented.

**Comment by broeder-j** [comment]
This should kill all subprocesses/calculations also. Not a pressing issue, but a feature one should not forget about.

**Comment by sphuber** [comment]
Fixed in #821
