### ISSUE TITLE
External AiiDA scheduler plugins aren't loaded

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#670]
We are trying with Nicola Spallanzani to load an external scheduler plugin with the new plugin mechanism.

More precisely, if the scheduler plugin is placed at the scheduler plugin folder (aiida/scheduler/plugins) and is registered, in the setup.py of AiiDA, it is correctly recognised and can be used during a computer setup.

I suppose that this is the classic behaviour.

We followed the instructions mentioned at
http://aiida-core.readthedocs.io/en/latest/developer_guide/plugins/new_system.html
and the structure of the quantum-espresso plugin (https://github.com/aiidateam/aiida-quantumespresso-epfl)

But the results are not positive,
So more specifically, a folder with the necessary files was created:
- __init__.py
- pbspro_spyros.py (the plugin)
- setup.py
- setup.json (with the necessary entry points)

It can be found attached. 
[my_scheduler.zip](https://github.com/aiidateam/aiida_core/files/1252363/my_scheduler.zip)

It can be installed with "pip install".
It is visible to AiiDA but it can not be used.

A first question is if the above files are sufficient for the plugin.
A second remark is that I understand that the external plugin mechanism for the scheduler plugins is not yet implemented.

E.g. the following changes allow the external plugins to be listed but there is an exception when the plugin needs to be used (so it needs further work)

```
diff --git a/aiida/scheduler/__init__.py b/aiida/scheduler/__init__.py
index b48bcf3..9bf58c3 100644
--- a/aiida/scheduler/__init__.py
+++ b/aiida/scheduler/__init__.py
@@ -65,9 +65,10 @@ class Scheduler(object):

     @classmethod
     def get_valid_schedulers(cls):
-        from aiida.common.pluginloader import existing_plugins
-
-        return existing_plugins(Scheduler, "aiida.scheduler.plugins")
+        from aiida.common.pluginloader import all_plugins
+        return all_plugins('schedulers')
```

**Comment by sphuber** [comment]
I have fixed the plugin loading (see PR #682 ) and tested it with an external scheduler plugin.
The test plugin just defines a test scheduler for SLURM and is attached here as tarball for reference.
[aiida-test-scheduler.tar.gz](https://github.com/aiidateam/aiida_core/files/1269455/aiida-test-scheduler.tar.gz)

Together with PR #681, which fixed the `PbsBaseClass` scheduler being shown as an option during `verdi computer setup`, external scheduler plugins installed through the plugin system should now work.

**Comment by szoupanos** [comment]
Thanks for this. I tested it with my example and I did not get the desired result.
I will also check the differences between the 2 schedulers (yours and mine).

**Comment by szoupanos** [comment]
There was a problem with my plugin (declaration in json and also some imports). After correcting it, I managed to create a new computer with this scheduler and to correctly run calculations (it is a copy of the pbspro scheduler plugin).

I attach it for completeness.
[my_scheduler.tar.gz](https://github.com/aiidateam/aiida_core/files/1274623/my_scheduler.tar.gz)
