### ISSUE TITLE
pip install freeze when using zsh

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida_core#672]
I use zsh as my default shell. 
When I install aiida_core 0.9.0, pip hangs at first step.
And I change my shell to bash, the installation go smoothly.

My question is whether can i use zsh as my default shell when using aiida?

**Comment by vdikan** [comment]
@unkcpz May be a general problem with your setup. I use zsh as default, no shell-specific problems so far.

**Comment by unkcpz** [comment]
@vdikan Yes, I think you are right. When I delete the line `rentry >= 0.9.1` in the file `setup.py`, installation successed. And the rentry still installed after I did this.
