### ISSUE TITLE
slurm squeue order problem

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida_core#680]
I configure a computer using the slurm scheduler.  
When I run `verdi computer test <computer>`, I always get the warning 
```console
08/31/2017 02:53:14 PM, aiida.scheduler.slurm: [WARNING] Warning in _parse_joblist_output, non-empty stderr='squeue: error: Invalid job format specification: V'
08/31/2017 02:53:14 PM, aiida.scheduler.slurm: [WARNING] Unrecognized format for time string 'UNLIMITED'
08/31/2017 02:53:14 PM, aiida.scheduler.slurm: [WARNING] Error parsing the time limit for job id 2496334
08/31/2017 02:53:14 PM, aiida.scheduler.slurm: [WARNING] Error parsing submission_time for job id 2496334
  `-> OK, 1 jobs found in the queue.
```
I find my `squeue` output have the different order from what `aiida.scheduler.plugins.slurm` have defined.
My order of `squeue` is `             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)`

And my slurm version is 2.7.6. I find the latest slurm version 17.02 have the same squeue order.
Am I miss something? 
Thank you.

**Comment by unkcpz** [comment]
Sorry for my stupid question. I find the option `-o` of `squeue`  control the format of the output of job information. 
But I still want to know whether the warning concerned or can be just ignored?

**Comment by ltalirz** [comment]
Is the problem still present with the recent version of SLURM?
If not, could you please run one calculation with that scheduler with AiiDA and provide us with the relevant parts of the log files (~/.aiida/daemon/log/aiida_daemon.log, which would contain similar errors)?

**Comment by unkcpz** [comment]
It is the problem of my low version SLURM. Latest SLURM do not have this error. Thanks for your reply.
