### ISSUE TITLE
requirement `enum34==1.1.2` conflicts with current version of pylint

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#691]
pylint requires `astroid>=1.5.1` which requires `enum34 >= 1.1.3`

**Comment by sphuber** [comment]
I have updated the `setup_requirements.py` version numbers for `release_v0.10.0` and have confirmed that with `enum34==1.1.6` everything still works. This would therefore also solve this issue, correct?

**Comment by sphuber** [comment]
Fixed in `release_v0.10.0` which will be merged into `develop`. Closing
