### ISSUE TITLE
Plugin development docs should mention `reentry` install hooks

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#701]
The plugin's `setup.py` should contain

```python
setup(
    ...
    reentry_register=True,
    ...
)
```

This will make sure the plugin's entry points are registered by the `reentry` plugin manager when installed with `pip`.
If another install method is used, the same can be achieved by running `reentry scan` from the command line after installing the plugin python package.

**Comment by DropD** [comment]
@italirz Assigning to you because i believe you were going to update the plugin development docs to match the sample plugin anyway.

**Comment by ltalirz** [comment]
Closed via #829
