### ISSUE TITLE
Document how to do a pre-commit hook to check version numbers in plugins

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#703]
Currently, for a plugin, the version should be written in the setup.json file, so that it can be used by the aiida-registry.
At the same time, one wants to have it into `__init__.py`.
There's no easy way from the __init__.py to get it from the setup.json, as this will not be copied by pip when installing (by default).

The best solution is probably to document a pre-commit hook for JSON (+ a travis check?) to check that the two versions match. This should be added to the plugin documentation in AiiDA + to the template plugin structure.

**Comment by ltalirz** [comment]
This has been implemented by @DropD in his vasp plugin.
We are discussing whether to add this also to the plugin template aiidateam/aiida-plugin-template#5

**Comment by giovannipizzi** [comment]
Closing in favour of the issue on the aiida-plugin-template repo
