### ISSUE TITLE
Failure in the read the docs builds

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#708]
The ReadTheDocs builds fail
https://readthedocs.org/projects/aiida-core/builds/6007497/

Reason: this script https://github.com/aiidateam/aiida_core/blob/develop/docs/update_req_for_rtd.py should be run to update the requirements file for ReadTheDocs (that needs to be slightly different than the main one).

Tasks: 
- [x] Run the script and update the requirements file
- [x] Add a precommit hook (and a test in travis) to check this?

**Comment by ltalirz** [comment]
@DropD if #723 fixes this, could you please close the issue?
