### ISSUE TITLE
Does reconstruction of objects from dbnodes need to go through constructor?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#709]
The requirement that all constructors of classes derived from `Node` must support the `dbnode` keyword argument and cannot have any positional arguments [1]  may come a bit unexpected to a new contributor.

So, my question to the experts:
Is this by design, and do we essentially need to tell developers not to write their own constructors for, say, a new data plugin or would it be possible to move this "reconstruction" call to a separate function like `_reconstruct_from_dbnode`?

[1] Plus, when `dbnode` is passed, no other keyword arguments may be passed.

**Comment by sphuber** [comment]
This will be taken care of in #2178 .
Once `Node` will be migrated to the new backend interface implementation, which will ensure that construction from a `DbNode` instance will go through a class method of the collection `from_dbmodel` which should not incur the costs of the actual constructor
