### ISSUE TITLE
Wrong error message (I think)

### ISSUE THREAD

**Issue by abelcarreras** [aiidateam/aiida_core#711]
I think the error message should be the opposite: No valid parser found for the plugin.
I got this message when the job was OK and the parser was not found.

https://github.com/aiidateam/aiida_core/blob/84fe6c526e5f16544a64587cf0035a607bf454b0/aiida/orm/implementation/general/calculation/job/__init__.py#L132

**Comment by ltalirz** [comment]
Looking at the code, the error message seems reasonable (?)
Perhaps the confusion arises from the fact that the term 'plugin' is used for the implementation of the parser here, and does not refer to the whole AiiDA plugin.
One could change it to something like `"No class found for the parser '{}'. "`
Of course, the name chosen for the parser may not make it clear that it actually refers to a parser.
@abelcarreras What was the exact error message shown?

**Comment by abelcarreras** [comment]
Well, maybe it is just me that interpreted it wrong. But as you said I understand that the plugin is the whole thing (the 'job creator' + the parser). So if I get this message it seems like the parser is found and the rest of the plugin is missing, or that no valid plugin can be associated to the parser while the problem is actually with the parser that is not found/recognized. I think you suggestion is much more understandable.

It is just a little thing, not very important but took me confused some time so I made the comment.

**Comment by giovannipizzi** [comment]
Ok for me with Leopold suggestion. Thanks to both!
