### ISSUE TITLE
'local' and 'remote' codes

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#715]
Currently, the distinction between a `local` and a `remote` code isn't really about whether the code resides on your local machine or on the remote machine, which is what I would naively expect.
It's about whether aiida stores only the path to the code (`remote`) or the code itself (`local`)  ([documentation](https://github.com/aiidateam/aiida_core/blob/develop/docs/source/get_started/index.rst#local-codes)).

To illustrate the difference: For example, during testing and development, I might want to test a code on my local machine. If I designate the code as `local` (which it *is*), I have to `verdi setup code` every time the code changes.

In my opinion, the feature of storing the code can be valuable for provenance irrespective of whether, originally, the executable was located on a local or a remote machine. I would therefore suggest that we

 1. Add a prompt `store executable: yes/no` during `verdi code setup`. This would also determine whether the code has a fixed computer attached to it or not.
 1. Always ask for a computer, which becomes the default computer for the code. If `store executable: yes`, the code ~~can~~ is allowed to also run on other computers. 
 1. (optional, but useful) implement the storage of executables from remote locations. Alternatively, when users request to store the code in the database, one can check whether the specified computer has transport type `local` and give an error message otherwise.

**Comment by giovannipizzi** [comment]
Duplicate of #127

**Comment by giovannipizzi** [comment]
Not sure about 3, it's more complicated than that (e.g. it could run on a set of computers but not on others) and for similar reasons not sure on 2.
Agree on 1 (can you find also a better name for the .is_local() method of Code?). If we agree on a good name, things should at least become clear (the docs says it, but it's a tiny detail and people forget about it even if it's explicit)

**Comment by ltalirz** [comment]
@giovannipizzi 
regarding `is_local()`: why not `is_stored()`?

regarding comments on 2./3.:
That's no different from how it works at the moment though, right? Or do you check on which computers the 'local' executable can be run?

I think it is fair to leave the responsibility of the code actually being able to execute on different machines to the user (it's not something we can reasonably check).

**Comment by szoupanos** [comment]
I also think that this issue needs clarification. Even now, I had to check the documentation about the exact definition of the local code.

I am not sure if I totally understand points 2 & 3 and if they make the whole local/remote code situation easier.

For me the most obvious "solution" is to have always a "remote code" meaning that there should always be a machine attached to the code (this was my initial interpretation of the word "remote" before reading the documentation). Using the localhost as a remote machine is just a special case.

The whole idea of the local code can be encapsulated to a phrase like: "should I copy a local executable to the remote machine or do you want to specify a path to the executable at the remote machine"?

So my comments are similar to the conclusion of the discussion at #127

**Comment by ltalirz** [comment]
closing this duplicate - discussion continues in #127
