### ISSUE TITLE
WorkChains restart from first step when output doesn't match spec

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#722]
The example below will print hello world over and over again:

`
class ZombieWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
        super(ExampleWC, cls).define(spec)
        spec.output('out', valid_type=NumericType)
        spec.outline(cls._step)

    def _step(self):
        print 'hello world'
`

**Comment by lekah** [comment]
I did a few more trials, and the problem has nothing to do with the output, but with an exception being raised.
The following WorkChain reproduces that problem:

`
class ZombieWorkChain(WorkChain):
    @classmethod
    def define(cls, spec):
        super(ZombieWorkChain, cls).define(spec)
        spec.output('out', valid_type=NumericType)
        spec.outline(cls._step1, cls._step2, cls._step3)
    def _step1(self):
        print 'I am a zombie'
    def _step2(self):
        raise Exception()
    def _step3(self):
        # This step is never reached
        pass
`

The same instance is constantly being launched over and over again, starting from the _step1

**Comment by sphuber** [comment]
That would indeed be a dangerous and troublesome phenomenon, but I am having trouble reproducing it. Which branch are you running this in and how are you running it?

**Comment by lekah** [comment]
I am using the most recent develop-version of AiiDA (f0c8e2c1e2d302bd55859fcf7c6afe0f7b2365e2) using the installation via pip. I have a tar.gz attached that reproduces the error for me,  also when I try different installations of AiiDA and different versions of plum. 
If you have trouble reproducing my case: extract the attached .tar.gz and activate a virtual environment, then execute ./test.sh. Do
[zombie.tar.gz](https://github.com/aiidateam/aiida_core/files/1334552/zombie.tar.gz)
 you see the same exception message twice?

**Comment by sphuber** [comment]
I think this has to do with the fact that you are ticking the workflow engine manually. If you just run the daemon itself, do you see the same behavior? When I just run the daemon it works as expected, but when I call  `tick_workflow_engine` I get the zombie behavior
