### ISSUE TITLE
Tests for the verdi commands

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#731]
Since we discussed a bit with Rico, here are some ideas about the verdi command testing. These came from the discussion that we had on PR #724 

There are two levels where a command should be checked:
a) it's functionality 
b) it's syntax

For (a) there are not a lot to be said. Theoretically speaking, everyone who writes a command, should write a test that checks its functionality. Or differently, the functionality should be described by the test and there should be the needed implementation.

For (b) there should be an efficient way to check (b1) that the commands receive the expected arguments (no-one changed by accident their signature) and that these are passed correctly to the main code of the command (2b).

(2b) is click’s job and it is the task of it’s developers that it works as advertised.

For (1b) we can get the signature of every command, e.g. the help of the command is updated directly by the defined (click) arguments and then, we can have a test that checks if the currently accepted arguments are those that we initially decided.

This test can be easy enough and universal (for all the commands).

**Comment by szoupanos** [comment]
Of course, other opinions (& comments) are more than welcome.

**Comment by sphuber** [comment]
Fixed after `verdi` was migrated to `click` in PR #1795 which included tests for most of the commands. If there are specific missing tests, a more specific issue should be opened
