### ISSUE TITLE
call clean_value only when needed

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#732]
The function `clean_value`
https://github.com/aiidateam/aiida_core/blob/58349feb2c90c9bef8797c9139856d6f238c7d4d/aiida/orm/implementation/general/node.py#L31
which replaces "BaseType AiiDA data nodes with their value, and List with a standard list" is called every time attributes of a node are set via `_set_attr`.

This seems unnecessary, and it should suffice to call `clean_value` only when actually storing the information inside the database.

This issue, together with a suboptimal way of setting up the list of atoms in `StructureData`, causes the computing time for importing large cif files into aiida be strongly dominated by calls to `clean_value` (#595).

**Comment by ltalirz** [comment]
Unfortunately, simply moving `clean_value` to the `store` function would come with some unwelcome changes to the UI. For example, `get_attr` may then return something different when called  _before_ and _after_ a node has been stored in the database.

After considering multiple options together with @giovannipizzi , we propose the following:
 * add a version of `_set_attr` that does *not* `clean_value` (could be a different method or `_set_attr` with a flag `clean_value`)
 * add internal variable`__has_unclean_attributes` to node that stores whether its attributes need to be cleaned upon storing
 * add a version of `_set_attr` that appends an item to a list attribute and only cleans the item, not the list (again, could be handled via a flag `append` of `_set_attr`)

While, unfortunately, this will not make existing code faster, it offers an easy interface for increasing speed where needed and does not change the user interface in unexpected ways.

**Comment by ltalirz** [comment]
One last detail:
Shouldn't we give programmers the freedom to skip `clean_value` entirely if they wish to do so?

One could skip 2. entirely or one could offer a "really dirty" version of `_set_attr` for people who know what they are doing.

**Comment by giovannipizzi** [comment]
I'm not sure about the "really dirty" version, what do you have in mind exactly? In any case, attributes have to be cleaned before sending to the DB, that can only store some specific data types

**Comment by ltalirz** [comment]
> In any case, attributes have to be cleaned before sending to the DB, that can only store some specific data types

Not if I already know that I only use these specific data types.

**Comment by ltalirz** [comment]
Fixed by #733
