### ISSUE TITLE
The shebang line at the beginning of the job script should be customizable

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida_core#739]
This line is currently hardcoded to `#!/bin/bash`, but it should be customizable in some way.

Some use cases:
- appending `-l` to the end (necessary for instance on Piz Daint in order to enable the `module` command - see https://user.cscs.ch/getting_started/running_jobs)
- using a bash executable at a different location
- using a different shell (if we are supporting anything else than bash)

https://github.com/aiidateam/aiida_core/blob/8f52eb0cea65552e423c0a6de9568c2b5a7c120c/aiida/scheduler/__init__.py#L148

**Comment by lekah** [comment]
Is it worth adding a new line in the computer setup? Default being of course #!/bin/bash?
It's a clean solution, but requires a few changes in parts of the code (setup, etc).

**Comment by giovannipizzi** [comment]
It's probably the best solution (and the rest of the code should use the "old" default if not set, e.g. in computers were already setup).
At this point it could be a good thing to decide how much of these things should be a 'computer' property or a 'authinfo' property (i.e. for the pair [computer, aiidauser]). Maybe this one is ok as computer property, though.
