### ISSUE TITLE
Search for undefined attributes

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#758]
I have a script that performs post processing on calculations and assigns some extra attributes. I would like to regularly re-run my script to process new calculations. For this purpose I need to search for calculations, which do not yet have my extra attributes. Hence, I would like to write something like this:

```
qb = QueryBuilder()
qb.append(WorkCalculation, filters={'extras.foo':{'==':None}})
```

**Comment by giovannipizzi** [comment]
This can already be done as follows:
```
qb = QueryBuilder()
qb.append(WorkCalculation, filters={'extras':{'has_key': 'foo'}})
qb.all()
```
This should be added to the docs

**Comment by oschuett** [comment]
Awesome! Thanks a lot :-)
