### ISSUE TITLE
Create verdi export migrate hook to migrate export archives

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#766]
We should expose an entrypoint like `verdi export migrate` for users to export existing export archives to new versions. The scripts are currently kept in the `docs/source/examples` source tree but are difficult to find and not easy to use. This functionality can be abstracted and made easily accessible

**Comment by DropD** [comment]
Is there actually code to do the migration other than for 0.1 -> 0.2?

**Comment by DropD** [comment]
Is the fix in #781 going into v0.10.0 and if so, is it enough to have a v0.1 -> v0.2 updater?
It seems fairly pointless to me, since i believe most people are not working with either of these versions.

**Comment by sphuber** [comment]
The version numbers `0.1` and `0.2` refer to the version of the format of the `data.json` and 'metadata.json` in export archives. The latest version in `aiida_core v0.10.0` will be `0.3`. The migration functionality for `0.2 -> 0.3` has already been implemented in another branch and will be merged in the release and develop branch soon.

**Comment by sphuber** [comment]
Merged into `release_v0.10.0` with PR #771
