### ISSUE TITLE
Fresh AiiDA installation with SQLA backend import error for alembic

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida_core#770]
In fresh AiiDA installation if you try to create profile (using verdi setup profilename) with SQLA backend it gives error error: ImportError: No module named alembic

**Comment by sphuber** [comment]
I just tried to create a new SqlA profile on a clean install of `release_v0.10.0` and for me it works. The `setup_requirements.py` explicitly mentions `alembic` but maybe it was added only in a recent commit. Can you still reproduce this issue with the latest `release_v0.10.0` branch?

**Comment by waychal** [comment]
It works fine now.
