### ISSUE TITLE
develop: setup_requirements broken for plumpy/invalid plumpy version

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida_core#774]
When trying to run `pip install -e .` I get the following error:

```
Collecting plumpy==0.7.9 (from aiida-core==0.9.1)
  Could not find a version that satisfies the requirement plumpy==0.7.9 (from aiida-core==0.9.1) (from versions: 0.7.9-fixed, 0.7.7, 0.7.8)
No matching distribution found for plumpy==0.7.9 (from aiida-core==0.9.1)
```

The list of available versions shows that the "-fixed" suffix inadvertently entered the version spec.

When fixing the dep in `setup_requirements.py` instead to

```
'plumpy==0.7.9-fixed',
```

I get the following warning during installation:

```
Collecting plumpy==0.7.9-fixed (from aiida-core==0.9.1)
  Downloading plumpy-0.7.9-fixed.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 491kB/s 
  Requested plumpy==0.7.9-fixed from https://pypi.python.org/packages/ec/31/1e4e6db90c32cad83a7e52188e87f7a09bce62d6c55ecf58d77d11a73ca6/plumpy-0.7.9-fixed.tar.gz#md5=082f86d41713bf93d07cffc0f6eb206b (from aiida-core==0.9.1), but installing version None
```

Seems there is still something wrong with that package.

Maybe make a brown-paper-bag release for plumpy called 0.7.9.1 instead?

**Comment by sphuber** [comment]
Plumpy has received another support release `0.7.10` and the setup requirements have been updated in PR #827 so this problem should now be solved
