### ISSUE TITLE
REST API: for user endpoint return selected values and remove password

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida_core#777]
In REST API, for user endpoint return selected values like first_name, last_name, id, date_joined, email, institution, etc. and remove password

**Comment by waychal** [comment]
All endpoints of the user will be removed for security reasons. 
In api.py user endpoints are commented and code is not completely removed. Resource and translator class is still there but not used.

**Comment by waychal** [comment]
merged pull request successfully

**Comment by waychal** [comment]
Remove user documentation

**Comment by ltalirz** [comment]
@waychal I'm reading through the documentation of the restapi and I'm starting to wonder:
Does it really make sense to remove the 'users' endpoint completely?

The list of users is something one could anyhow get from the database in other ways I guess (unless we want to completely hide any information about the users).
The main security concern was that the password field (although currently unused) was shown.
Why not simply hide the password field?

**Comment by sphuber** [comment]
Fixed in PR #878
