### ISSUE TITLE
Unable to store structure without cell

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#792]
The StructureData currently enforces a cell volume larger than 1.e-6:
https://github.com/aiidateam/aiida_core/blob/develop/aiida/orm/data/structure.py#L54

We would like to upload preliminary structures to AiiDA and then edit them afterwards. In order to record the full provenance, we have to be able to store structures without cells.

Example:
```
>>> atoms = ase.build.molecule("H2O")
>>> StructureData(ase=atoms)
...
ValueError: The cell volume is zero. Invalid cell.
```

**Comment by giovannipizzi** [comment]
I think this was "by design". You can put a default cell like `[[10,0,0],[0,10,0],[0,0,10]]` and set the `pbc` to `[False, False, False]`

**Comment by giovannipizzi** [comment]
If this is ok for you, please also close this issue

**Comment by oschuett** [comment]
Ok, thanks for the clarification.
