### ISSUE TITLE
Pbs Scheduler plugin options + processors per node vs. mpi processes per node

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#81]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Add the possibility to have scheduler plugin options. Most common case: string to define how to specify nodes, cpus per node, etc.

Probably specify a list of existing strings, and provide also the possibility for the user to define their own, with string substitution for tot_num_mpiprocs, or num_mpiprocs_per_machine, num_machines.

Moreover: Document it.

Important because e.g. different PBSPro flavors want a different syntax.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/81

**Comment by yakutovicha** [comment]
This issue has been already solved introducing set_resources method in the JobCalculation class.
