### ISSUE TITLE
Cannot compile the docs when my verdi profile points to a sqlalchemy version

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#810]
I am getting obscure messages when I compile the docs when my verdi-profile points to a sqlalchemy version. Even though alembic is installed and the profile passes tests, when compiling I get the following traceback:

(aiida-develop-general) leo@pegasus->docs$ verdi profile setdefault verdi test_sqla1
(aiida-develop-general) leo@pegasus->docs$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.5.2

Exception occurred:
  File "/home/leo/git/AiiDA/aiida_develop_general/docs/source/../../aiida/backends/sqlalchemy/utils.py", line 28, in <module>
    from alembic import command
ImportError: No module named alembic
The full traceback has been saved in /tmp/sphinx-err-Ffd78Y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:50: recipe for target 'html' failed
make: *** [html] Error 1

**Comment by sphuber** [comment]
I have just tried to build the docs with an sqla profile on the current `release_v0.10.0` branch and everything seems to work. @szoupanos has pushed various fixes related to alembic so perhaps the original error is really fixed. Could you verify that `release_v0.10.0` no longer has this issue?

**Comment by sphuber** [comment]
I realize the problem now. The import error for `alembic` probably arose because it wasn't installed, which probably happened because it was added recently as a dependency and @lekah did not run `pip install` again. Closing
