### ISSUE TITLE
Helpsstring/Interface Docstring for workchains

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida_core#814]
A User that runs work chains in an interpreter (jupyter) should have some nice way to know how the workchain should be used.

Is there a better solution then writing huge docstrings? Specs has help, maybe a workchain should get something like this.

**Comment by greschd** [comment]
I think we want the ``WorkChain`` to have a ``.help`` attribute which collects the docstring and the help from the spec (input / output ports). 

It might be possible to re-use parts of the auto-generated documentation parts, but not sure if this actually makes things simpler.

**Comment by sphuber** [comment]
The new `Process.builder` will give an easy handle to inspect the input documentation by exposing all the inputs and using the `help` of the `Port` as the docstring. As for the workchain description, in the shell, the user can use `WorkChain??` which will display the docstring. Implementing a class method to do what python already provides natively is a little counterproductive. Writing a docstring for the `WorkChain` class satisfies the requirement for online docs, in shell users as well as source code readers. I don't think we need to change this, right?

**Comment by greschd** [comment]
I guess not, since the requirement is now met by the builder. @broeder-j, what do you think? Can we close this?

**Comment by broeder-j** [comment]
So far I just wrote long docstrings for the workchains. For me it is fine now, as long everything from the usual python way works (which back then did not, it showed the superclass (work calculation, process) doctoring or something and that was the issue, if I remember correctly). Therefore the original issue is solved now. The thing with auto generation is anyway that you must be able to add stuff to it. Therefore for a developer if you write the doc in the doctoring or the specs, does not matter so much.

**Comment by broeder-j** [comment]
and if one adds that you can execute the workchain directly you can implement there the usual command line --help, which one can also utilize in notebooks and so on.
