### ISSUE TITLE
Search for is_sealed

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#815]
I have a script that performs post processing on calculations and assigns some extra attributes. I would like to regularly re-run my script to process new calculations. For this purpose I need to search for finished WorkCalculations, i.e. those that are sealed. Hence, I would like to write something like this:

qb = QueryBuilder()
qb.append(WorkCalculation, filters={'sealed':True})

**Comment by giovannipizzi** [comment]
@muhrin @sphuber is this doable? Maybe it's just _sealed?

**Comment by sphuber** [comment]
In the current state `v0.10.0` a `Calculation` and by inheritance any `WorkCalculation` get the option to be sealed through the `Sealable` mixin from `aiida.orm.mixins`. When a `Calculation` is sealed it means that an attribute with the key `Sealable.SEALED_KEY` will be set to true. I am not too familiar with the `QueryBuilder` but I think we can query for any `Node` attribute, in which case it should be relatively trivial to implement.

**Comment by giovannipizzi** [comment]
It is this, then:
```
from aiida.orm.calculation.work import WorkCalculation
qb = QueryBuilder()
qb.append(WorkCalculation, filters={'attributes._sealed': True})
```

@muhrin @sphuber I don't think the logic of 'sealing' is documented. Could you add a short page in the docs explaining it?

**Comment by sphuber** [comment]
I haven't added it because it has been changing a lot. Not sure if the current conception is robust and will stay this way

**Comment by giovannipizzi** [comment]
Ok. I'll close this issue in the meantime, then.

**Comment by oschuett** [comment]
I now realize that _sealing_ is a low-level concept and not part of the stable API. Then maybe instead you could provide something like `has_finished()` ?

In the end I need a simple way to distinguish failed WorkChains from those that are still running.

**Comment by sphuber** [comment]
In the current conceptualization, there is a difference between `has_finished` and `is_sealed` though. For example a `WorkCalculation` may be considered `finished` as in it is not running anymore and has gotten to the end of the execution, but the `sealed` refers to whether the `Node` is sealed. When it is sealed it really is marked as immutable. So it kind of depends on what you are looking for. For `WorkCalculation` specifically though, other than the `SEALED` attribute has three state keys `FINISHED_KEY`, `FAILED_KEY` and `ABORTED_KEY`. These are the three final states. If any of them is set, you can consider the `WorkCalculation` to be "finished", as in not running anymore.

**Comment by oschuett** [comment]
Oh that's good. Currently `workcalc.get_attr('_sealed')` is still a boolean. So, I guess this will come with the next release?
