### ISSUE TITLE
lacking documentation to explain basic objects and methods in workchains

### ISSUE THREAD

**Issue by tsohier** [aiidateam/aiida_core#828]
As a beginner in Workchains I found it difficult to figure out how to build/configure a workchain. Not sure I'm using the right vocabulary, but I'm talking about going through the process of specifying/using objects like spec, ctx, inputs or out to tell the workchain what I want it to do.
What are those objects and how do I use them?
What are their methods and attributes?
It feels like one has to look at the example on read the docs and do a lot of guess work.

Also, it would be nice to have an example drawing a parallel between how you launch a standard Aiida calculation versus how you do it in a workchain. Namely:

calc=code.new_calc()
calc.use_parameters(...)
calc.set_resources({"num_machines": 1})
....
calc.submit()

versus:
Proc = PwCalculation.process()
inputs=Proc.get_inputs_template()
inputs['code']=code
inputs['parameters']=....
inputs['_options']['resources']={"num_machines": 1}
.....
outputs=run(Proc, **inputs)

For example, It took me quite some time to figure out that the equivalent of "set_resources" was in "inputs['_options']['resources']" .

Thanks!

**Comment by sphuber** [comment]
This is a duplicate and is being monitored and managed in #1058
