### ISSUE TITLE
Stopping daemon with a database schema version conflict is impossible

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#831]
When a user upgrades their code base which introduces a database migration, any action that requires the database backend will throw the exception that there is a schema version conflict and will instruct the user to stop the daemon and then execute the migration command. However, since the `verdi daemon stop` command itself depends on the backend, this command will throw the exact same exception. The command only requires the backend to check the timestamps of the legacy workflow stepper in the `DbSettings` table, but unless that can be removed the backend dependency remains. It seems that the same checks are performed in `verdi daemon start` and by proxy therefore in `verdi daemon restart` so maybe it is not necessary to also have it in `verdi daemon stop`, but assuming for now that it has to stay in, there are two options:

* We use `_load_dbenv_noschemacheck` just for the `verdi daemon stop` command
* We introduce a `verdi daemon kill` that will stop the daemon without the database checks for the legacy workflow stepper and tell the user to call that command. However, if the checks performed in `verdi daemon stop` I think this is a bad solution as users might also use the command in normal situations.
* Alternatively, in the schema version check, when the exception is hit we detect whether the daemon is running (assuming this can be done backend independent) and if it is not we simply tell the user to perform the migration, or else we tell the user to revert the code upgrade, stop the daemon and reupdate the code and perform the migration. The latter situation is of course a pain in the ass.

**Comment by nmounet** [comment]
In `aiida.cmdline.commands.daemon.Daemon.daemon_stop`, the lines that requires the dbenv to be loaded (that use dbsettings and re-initialize the timestamps) are most probably useless.
Then the problem will disappear.
I will make some checks.

**Comment by sphuber** [comment]
Fixed in PR #858
