### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#84]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Add a table to store notifications and different ways to process them (verdi notifications, send emails, ...)

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/84

**Comment by giovannipizzi** [comment]
For the time being I close this, we'll see if this is needed in the future (but probably we'll implement something in the web interface)
