### ISSUE TITLE
StructureData does not store initial magnetic moments

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#854]
I would like to store the initial magnetic moments in the StructureData:
```
>>> atoms = build.molecule("H2O")
>>> atoms.center(vacuum=1.0)
>>> atoms.set_initial_magnetic_moments([1, 0, 0])
>>> atoms2 = StructureData(ase=atoms).get_ase()
>>> atoms2.get_initial_magnetic_moments() #  should be [1., 0., 0.]
[ 0.  0.  0.]
```
As a workaround we're currently using tags. However, they suffer from issue #853.

**Comment by giovannipizzi** [comment]
This is not supported by AiiDA's StructureData objects. We decided to drop the initial magnetic moments out of StructureData, and keep them in the input of the calculation (from my point of view, they are inputs to the calc, not properties of the structure).
Do you agree?

**Comment by oschuett** [comment]
Ok, I guess this makes sense. Still, it would be nice to have an official way of annotating a `StructureData`. Basically, a `set_extra()` for atomic kinds. A simpler alternative would be tags, see #853.
