### ISSUE TITLE
Pre-commit tests are skipped

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#860]
I have the following .pre-commit-config.yaml

```
# yet another python formatter
- repo: git://github.com/pre-commit/mirrors-yapf
  sha: v0.17.0
  hooks:
  - id: yapf
    language: system
    files: >-
      ^(aiida/control/)
      |(aiida/cmdline/tests)
      |(aiida/cmdline/commands/share.py)
      |(docs/update_req_for_rtd.py)
      |(.travis_data/test_setup.py)
      |(aiida/backends/tests/verdi_commands.py)
      |(aiida/utils/.*fixtures.py)

# prospector: collection of linters
- repo: git://github.com/guykisel/prospector-mirror
  sha: b27f281eb9398fc8504415d7fbdabf119ea8c5e1
  hooks:
  - id: prospector
    language: system
    exclude: '^(tests/)|(examples/)'
    files: >-
      ^(aiida/control/)
      |(aiida/cmdline/tests)
      |(aiida/cmdline/commands/share.py)
      |(docs/update_req_for_rtd.py)
      |(.travis_data/test_setup.py)
      |(aiida/backends/tests/verdi_commands.py)
      |(aiida/utils/.*fixtures.py)

- repo: local
  hooks: 
  - id: rtd-requirements
    name: Requirements for RTD
    entry: python ./docs/update_req_for_rtd.py --pre-commit
    language: system
    files: >-
      ^(setup_requirements.py)
      |(docs/requirements_for_rtd.txt)
      |(docs/update_req_for_rtd.py)
    pass_filenames: false

- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.4
  hooks:
  - id: check-yaml

- repo: local
  hooks:
  - id: travis-linter
    name: travis
    entry: travis lint
    files: .travis.yml
    language: ruby
    additional_dependencies: ['travis']
```

and for some reason the yap & the prospector tests are skipped (even if my file is in the corresponding lists)

E.g.

```
(aiidapy) aiida@ubuntu-aiida-vm1:~/aiida-code/aiida_core$ git add .
(aiidapy) aiida@ubuntu-aiida-vm1:~/aiida-code/aiida_core$ pre-commit
yapf.................................................(no files to check)Skipped
prospector...........................................(no files to check)Skipped
Requirements for RTD.................................(no files to check)Skipped
Check Yaml...............................................................Passed
travis...............................................(no files to check)Skipped
```

**Comment by DropD** [comment]
In general pre-commit tests are assigned to certain files or file types.
They are skipped when none of these files have changed.

What happened here was that the tests were skipped even though some of the
files *were* changed. The folders listed in the `files` key regex for both
yapf and prospector are recognized but single `.py` files seem not to be.

I will investigate how to add a single file to be checked.

**Comment by ltalirz** [comment]
seems like it's my fault. I wanted to split the string over multiple lines and I thought it worked, but it seems it always skips. I'll have a look.

**Comment by ltalirz** [comment]
If one can believe [this post](https://stackoverflow.com/a/21699210/1069467) on stackoverflow, then the problem might be that with `>-` line feeds aren't simply removed, but are translated into single spaces.

An alternative way of still splitting the lines that seems to work for me is
```
   files: "\
      ^aiida/control/\
      |aiida/cmdline/tests\
      |docs/update_req_for_rtd.py\
      |.travis_data/test_setup.py\
      |aiida/backends/tests/verdi_commands.py\
      |aiida/utils/.*fixtures.py\
      "
```
Not the most pretty solution, but still a lot better than having everything on one line.

Note that I also removed the brackets, since they didn't seem to be necessary for the cases I tested (both folders and single files).

Let me know whether it works for you and feel free to change it in your next pull request.
