### ISSUE TITLE
postgres process going crazy?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#862]
This may be completely unrelated to aiida, but in case anyone else has ever had the same experience, I'd like to quickly ask:
Have you ever noticed the postgres process suddenly starting to make large amounts of data transfers over the network (GBytes over a few hours)? I am noticing this because I sometimes work on the train and it depleted the data allowance of my mobile already for the second time.

I've no idea why postgres would want to make any network transfers at all. I don't use postgres for anything else besides aiida and I don't have any remote computers configured that could be polled (I guess, in this case, it would anyhow be the daemon process that makes the transfers, right?). I verified that the postgres port is not open.
I know it's not much to go on, and I'll close the issue in case I'm the only one with this problem.

I'm running postgresql 9.5.7 installed via macports on MacOS 10.12.6

**Comment by DropD** [comment]
I am not sure I have seen that in action, but i have noticed that postgres is usually the process with the most data transfers (OSX: ActivityMonitor -> Network tab).

Postgresql 9.6.5 from `homebrew`, OSX 10.12.6

**Comment by ltalirz** [comment]
Thanks @DropD, you are right, also in my case the number of incoming packets and outgoing packets were equal.
I wasn't aware that the network tab also captures postgres talking to itself, so it might not have been postgres after all. I'll pay closer attention next time.
