### ISSUE TITLE
sqlalchemy: very expensive recursive check for dates

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#864]
The following function contains a rather expensive recursive procedure, whose only purpose (if I understand correctly) is to try and replace strings by datetime objects:

https://github.com/aiidateam/aiida_core/blob/17484b5920ecc4f6906c73867cfaf6b16658e219/aiida/backends/sqlalchemy/utils.py#L172-L198

Any ideas for a better way of achieving this?

In my use case, which involves importing a large number of .cif files into the database, this rather benign check is the single most expensive operation (it causes millions of `is_instance` calls).
In the total run time of the import process it's just 20%, so it's not absolutely critical for the moment, but still...

**Comment by giovannipizzi** [comment]
Indeed this is something we spent quite some time discussing when we started implementing SQLA. Datetimes is really I think the only missing feature in SQLA w.r.t. the Django implementation.
Maybe at the next AiiDA meeting let's discuss how we want to use datetimes - if they are useful and we really need to query them. I had the impression this is the case, but maybe it's not.

**Comment by sphuber** [comment]
This problem only applies to storing datetime type objects in JSONB fields, i.e. `attributes` or `extras`. Given that this is the only application and the only thing why this expensive deserialization logic is here, it is better to remove it and store simple strings. If datetime objects are required it should be left to the python implementation to cast the query results.

**Comment by szoupanos** [comment]
This will be needed for Django JSONB too.
It is fast currently because of the EAV, if we totally move to JSON, we will have to address this problem irrespective of the backend

**Comment by giovannipizzi** [comment]
I suggest removing support for dates in the attributes; if dates are just for logging, write them as a string (this needs to be done also by us when storing some date time from the scheduler, at least for some schedulers). If it's needed also for queries, it's up to the user to write it e.g. as a float (maybe together with a string representation as a different attribute). We should the document it and the suggested way of storing queryable dates. @sphuber do you agree?

**Comment by ltalirz** [comment]
> I suggest removing support for dates in the attributes; if dates are just for logging, write them as a string (this needs to be done also by us when storing some date time from the scheduler, at least for some schedulers). If it's needed also for queries, it's up to the user to write it e.g. as a float (maybe together with a string representation as a different attribute). We should the document it and the suggested way of storing queryable dates.

I fully agree with this proposal.

> That's OK but this implies that we lose timezone information etc.

Only for the "queryable" unix timestamps in attributes and extras.
Anyhow, it is an improvement over the current state, where anyhow strings would be stored (if anyone ever actually did store dates in attributes/extras)...

**Comment by giovannipizzi** [comment]
> That's OK but this implies that we lose timezone information etc.

In the suggestion that we put out, we should say to always store times in UTC.

> if anyone ever actually did store dates in attributes/extras...

We do to store time information from the scheduler (for some schedulers at least) - so we need a migration, e.g. converting to UTC time strings (so no need to put a timezone, that anyway now is probably not properly stored as we don't ask what timezone the supercomputer is)

**Comment by sphuber** [comment]
Remove support for datetime objects in attributes and extras and add validation in the setters that will raise. The message should then point to helper functions that can convert the datetime in a string.
* `datetime_to_string` if querying is not important
* `datetime_to_float` if they want to query somehow for them, storing in UTC as discussed before
The reverse deserializers should also be provided of course.
Note that when #2454 is addresses, existing datetime objects in the attributes for Django have to be converted and they should use one of these two functions as a default.

**Comment by szoupanos** [comment]
This should be addressed together with #2788

I copy also here what I wrote there about DbSetting
> We should see in both issues what we do with DbSetting that also contains dates and is stored in JSONB.
