### ISSUE TITLE
segfault _exportstring for cif/tcod data

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#882]
I have structures containing hundreds of atoms and when using the `_exportstring` function for `cif` and `tcod` formats on the structure node, I receive a segfault
````
In [1]: n = load_node(104)

In [2]: n
Out[2]: <StructureData: uuid: 10a9728f-20c4-4d6d-8cd8-372710e6c66d (pk: 104)>

In [3]: #n.get_db_columns

In [4]: n.get_export_formats()
Out[4]: ['cif', 'tcod', 'xsf', 'xyz']

In [5]: n._exportstring('cif')
python(83919,0x7fff94ba23c0) malloc: *** mach_vm_map(size=16171194568346177536) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11
````

`xyz` and `xsf` formats work fine.

I'll try to investigate a bit more, if I find the time - help is welcome!

**Comment by ltalirz** [comment]
Following a suggestion by @giovannipizzi I installed the latest pycifrw version (4.3) and checked whether I could get it to work there - unfortunately not straightforwardly.

The `AddCifItem` used in
https://github.com/aiidateam/aiida_core/blob/7894a19cea0bfe0b351bf43e8f728b2895e308c7/aiida/orm/data/cif.py#L250
is now deprecated and simply replacing it with the `AddItem` function one should use with v4.3 doesn't work either because this one doesn't loop over things.

I stopped at this point - does it make sense to go on and adapt it to check whether the segfault is gone in the latest version? According to git blame the last person to work on this bit was  @merkys

**Comment by merkys** [comment]
I propose switching from pycifrw to pycodcif (also on PyPI now) – Python bindings of cod-tools CIF parser (I am a developer of it). pycodcif's interface/data structure is more stable and I volunteer to rewrite the associated AiiDA code. However, there is a single catch I can not get past by on Mac: ``ssize_t`` C type is undefined there and I can not find an equivalent. Does anyone have experience with it?

**Comment by ltalirz** [comment]
I'm not an expert, but I guess this is compiler-dependent?
Perhaps this helps: https://stackoverflow.com/questions/29543394/which-c-compilers-automatically-define-size-t-without-requiring-a-header-inclu

**Comment by giovannipizzi** [comment]
By doing `grep ssize_t *` on my Mac (10.12) I see e.g. 
```
string.h:#include <sys/_types/_ssize_t.h>
```
and indeed inside `sys/_types/_ssize_t.h`
there's
```
#ifndef _SSIZE_T 
#define _SSIZE_T 
typedef __darwin_ssize_t        ssize_t; 
#endif  /* _SSIZE_T */
```
Does this help?
Probably you need an ifdef to know if you're on a Mac. Probably this helps: https://stackoverflow.com/questions/6802903/c-ifdef-mac-os-x-question

**Comment by merkys** [comment]
Thanks, @giovannipizzi. Could you check please whether anything like ``ssize_`` is defined in Mac's ``unistd.h``? This header should provide compatibility with POSIX API.

**Comment by giovannipizzi** [comment]
There's `#include <sys/_types/_ssize_t.h>` in that file, so I would say so.
Are you working on GitHub? Do you know that travis automatic tests can run at every commit a test, and they also support Mac beside linux?

**Comment by merkys** [comment]
Thanks! Yes, I mirror my work on GitHub. I'll look into how to integrate with Travis.

**Comment by merkys** [comment]
@giovannipizzi, for the time being, could you try installing pycodcif on Mac: ``pip install pycodcif --user``? I've made an attempt to fix ``ssize_t`` issue, but I'm not sure that the build process won't fail again.

**Comment by giovannipizzi** [comment]
I will continue this on private emails with @merkys for what concerns pycodcif

**Comment by ltalirz** [comment]
Anyhow, if the cod-tools cif parser api is going to be more stable and there are no drawbacks from our perspective (parsing speed + breadth of support for the cif format) we would of course be perfectly happy to switch!

**Comment by merkys** [comment]
Great then! I have managed to get pycodcif build on Mac, therefore I will rewrite the ``CifData`` class as soon as I find some time.

**Comment by ltalirz** [comment]
@merkys What's the status of the transition? Anything you need help with?
I'll be doing a few things with .cif files, so it would be great to move forward on this.

**Comment by merkys** [comment]
@ltalirz currently I am overwhelmed by other stuff and can not find time to work on this. While ``pycodcif`` could be already used to parse CIF files, C bindings for CIF writing (needed by ``CifData``) are yet to be developed.

**Comment by ltalirz** [comment]
I'll close this for the moment. Happy to reopen, when there is progress.

For reference, here are my personal requirements for switching to another library (like pycodcif)
* fully pip-installable (we cannot afford to add another dependency to aiida that needs to be installed by hand)
* as fast or faster as PyCifRW using `scan_type='flex'`. I.e. it should be able to parse the [attached CIF files](https://github.com/aiidateam/aiida_core/files/1753519/structures.zip) in ~200ms per file

**Comment by merkys** [comment]
> * fully pip-installable (we cannot afford to add another dependency to aiida that needs to be installed by hand)

Makes perfect sense. A pre-release version of pycodcif is in PyPI already, however, this one is not ready to cover both reading and writing CIF files yet (read-only currently).

> * as fast or faster as PyCifRW using scan_type='flex'. I.e. it should be able to parse the attached CIF files in ~200ms per file

In 2015 pycodcif was 10x faster than PyCIFRW and parsed ~350k CIFs of the Crystallography Open Database in 4 minutes. I need to rerun the benchmarks with the newest versions of course.

In any case I will keep you updated.

**Comment by ltalirz** [comment]
@merkys We have a use case in our group where we would like to be able to validate CIF files programmatically. I'd be very happy to use cod-tools for that, perhaps even add a corresponding tool on Materials Cloud that people could use to validate CIF files via cod-tools (if you would be ok with that).

I would like to use the python interface, however, and I while `pip install pycodcif` works on Ubuntu 18.04 it still doesn't work on my mac.
I'd be happy to contribute fixes to the python package (also updating the pypi description a bit) but for this I would kindly ask you the following:

> Please  move the pycodcif codebase from the `cod-tools/src/components/pycodcif` in the SVN to a github repository, so I can start collaborating with you more easily.

Would you be happy to do that?

**Comment by ltalirz** [comment]
@merkys Thanks for the info!
Concerning the validation: Does that mean you perform [all the checks](http://journals.iucr.org/services/cif/datavalidation.html) done by the checkcif tool?

Thanks also for the link to the github mirror, which I hadn't discovered - I'll just make my PR there.

**Comment by merkys** [comment]
> Concerning the validation: Does that mean you perform [all the checks](http://journals.iucr.org/services/cif/datavalidation.html) done by the checkcif tool?

Certainly not all checks. Some of the checks of ``checkcif`` are arbitrary, and some we consider too strict, therefore we perform a subset of them.

**Comment by ltalirz** [comment]
@merkys The CIF issue is coming up again now and we're contemplating which python library to use for our CIF validator tool.

Since you are the expert, could you please some input on the pros and cons of using PyCIFRW vs pycodcif?

Things that came up so far in the discussion:
 * it was pointed out that the IUCR [lists pycifrw on their web site](https://www.iucr.org/resources/cif/software/pycifrw) but not codtools/pycodcif (perhaps you should get it listed there?)
 * pycifrw can write CIF files
 * pycifrw with `scan_type='flex'` is "fast enough" (parses [these structures](https://github.com/aiidateam/aiida_core/files/1753519/structures.zip) in ~200ms / file)

**Comment by merkys** [comment]
> Since you are the expert, could you please some input on the pros and cons of using PyCIFRW vs pycodcif?

Well, as one of the authors of pycodcif, I am biased, I must stress. Both packages parse CIF quite efficiently and closely following the CIF standard. pycodcif is capable of fixing some of the most common CIF problems (occurring in publication supplements), and pycifrw has built-in CIF validation tools (haven't tried, only read about them).

> * it was pointed out that the IUCR [lists pycifrw on their web site](https://www.iucr.org/resources/cif/software/pycifrw) but not codtools/pycodcif (perhaps you should get it listed there?)

I will ask for the inclusion. cod-tools/pycodcif will be included in [the list of CIF2-ready software](https://www.iucr.org/resources/cif/cif2/cif2-adoption) in the next update of the IUCr website. As I see this is not done often.

> * pycifrw can write CIF files

So as pycodcif can now. CIF manipulation is not tested thoroughly, but I am willing to fix occurring bugs.

> * pycifrw with `scan_type='flex'` is "fast enough" (parses [these structures](https://github.com/aiidateam/aiida_core/files/1753519/structures.zip) in ~200ms / file)

Tried on my machine with all files from your archive:
* pycifrw v4.4.1 (no `scan_type='flex'`): 7.5s
* pycodcif v2.4: 1s

I couldn't find a way to pass `scan_type='flex'` to pycifrw.

**Comment by ltalirz** [comment]
I checked the speed and on these type of structures `pycodcif` is indeed still about 30% faster than pycifrw with `scan_type='flex'`.

@merkys There may be potential for further optimization since my profiling indicates only 30% of the total time spent inside `pycodcif.parse` is inside `pycodcif._pycodcif.parse_cif`.
40% is spent in list comprehensions (`<listcomp>` in cProfile output) and 30% is spent in `extract_precision`.
