### ISSUE TITLE
verdi node delete

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#923]
The deletion of nodes should be exposed to the user. I suggest "verdi node delete [pk1 pk2...]"
This deletes the whole downward data provenance of the given nodes (i.e. all descendants linked by INPUT/CREATE).

To address:
1) What do we delete for WorkCalculations (What they called?/ignore?) ?
2) How many levels of flashing, warnings, confirmation do we need?

**Comment by broeder-j** [comment]
To 1. I think also what they call. If I know the workchain I just run is trash I want also all calculations launched by it deleted.

2. Like in the short code snippet: A feedback of what am I going to delete? how many nodes, links,... and one confirmation level

**Comment by broeder-j** [comment]
What I do: Mark nodes as trash in extras and then 'collect, empty garbage'. But this way there is a way back until the 'garbage collector' comes and therefore you can think about it again or first visualize the 'garbage' in a way.

**Comment by lekah** [comment]
Thanks @broeder-j  This is an interesting option, instead of having verdi node delete...
we could have an operation that first shows what is deleted (the graph) and then deletes.

And what you're saying is that you want a custom recipe for traversing the graph looking for nodes that you want to delete. You could add such a usecase to #924 , no?

**Comment by sphuber** [comment]
This functionality was added in PR #1083
