### ISSUE TITLE
verdi code show can be very slow

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#925]
Verdi code show PK can take several seconds to load and show.
I traced that back to the information Used_by which counts the number of outputs. If that surpasses a thousand, querying the number of outputs leads to a considerable delay. For 90000 calculations, I need to wait over 2 minutes.

I suggest removing that option from the defaults, and having instead a -l command line switch to print more information, that is potentially slower.

@giovannipizzi @nmounet  How does that sound?

**Comment by giovannipizzi** [comment]
It looks like a very good idea!
BTW, do we know if there is a simple way to speed up that count? (Maybe we're getting a lot of python classes while we could just ask the count to the DB, or something like this?)

**Comment by lekah** [comment]
With fixing the issue I can try to speed up the count. I doubt that this will solve the issue (slowness), though.
It's no big deal, I think, how many calculations ran this code is not vital information for the code, in my opinion.
In general, we should always think about what happens scaling things up to 10^6 nodes and more!

**Comment by giovannipizzi** [comment]
Thanks!

**Comment by sphuber** [comment]
Fixed in #1428
