### ISSUE TITLE
non-interactive verdi install

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida_core#93]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

Have verdi install run also in non-interactive mode (asked by the Gabor's group, for multi-user installation)

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/93

**Comment by giovannipizzi** [comment]
This is now fixed with the new ``verdi setup`` command that supports the --non-interactive flag.
