### ISSUE TITLE
different keywords in get_inputs and get_outputs

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida_core#937]
get_inputs(node_type=None, also_labels=False, only_in_db=False, link_type=None)

get_outputs(type=None, also_labels=False, link_type=None)

The fact the keywords are so different in these 2 semantically similar functions is very confusing.
We need to decide on keywords that are enforced in both functions, and ideally also used get_in/outputs_dict.

**Comment by sphuber** [comment]
This has been fixed
