### ISSUE TITLE
Add option for accout information in Scheduler 

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida_core#942]
I am new to AiiDA but it seems there is no internal method to specify which "account" the job will will charge to when submitting to a computing cluster. E.g To  add lines like `# PBS -A <account>` or `#SBATCH -A <account>`. 

While this can be got around by putting it in the computer's perpend lines or in the  `custom_scheduler_command`, it is perhaps worth adding a term to the to the `JobTemplate` and the underlying plugins? As a  example, I have multiple accounts with different service levels and often want to switch between them.

**Comment by giovannipizzi** [comment]
From an answer to the mailing list:

Indeed (see here: http://aiida-core.readthedocs.io/en/latest/state/calculation_state.html#setting-calculation-properties )
set_custom_scheduler_commands() is the command to use and was added exactly for the reason you describe:

Doc: set a string (even multiline) which contains personalized job-scheduling commands. These commands are set at the beginning of the job-scheduling script, before any non-scheduler command. (prepend_texts instead are set after all job-scheduling commands).

Indeed, this could be something asked in the configuration of a computer, but as you say a user might want to switch this at run time, depending on the type of calculation.
The question is how much this is scheduler-independent. E.g. in some SLURM clusters we have we use partitions, in others we use accounts, or a combination of both; I don’t know if both concepts exist, e.g., for PBS.

Possible things we could do are
- add a method to calculations to set a scheduler_account, and internally the plugin knows which flag to add - this if we address my question above
- add to the computer setup the option to specify not only prepend text but also custom scheduler commands (however, these cannot be overridden, so one should configure different computers for different accounts).

**Comment by giovannipizzi** [comment]
As a comment, I'm not sure it's a good idea to expose this for JobTemplate, because in this case the Calculation plugin should know about queues etc. - in #74 we suggest to expose this for computers (via DbAuthInfo) that hopefully solves also your use case, so I'm closing this issue - if not, please write any further comment there

**Comment by greschd** [comment]
As a side note on this, there are also scheduler commands which should ideally be set on the code. For example, SLURM has the ``--constraint``, which describes which features the given nodes should have (e.g., to select nodes with / without GPU). Since different codes might need different node features, that's probably the best way to put this.

**Comment by greschd** [comment]
@giovannipizzi I didn't quite understand from this if it's possible to set the ``custom_scheduler_commands`` from configuration. Or is this only possible through the ``set_*`` function on the calculation?

**Comment by giovannipizzi** [comment]
Hi, yes, at the moment IIRC the only way to set them is at the calculation level via the `set_*` methods, or better in new AiiDA versions via `options`.

Indeed, there is a number of places where one might want to set defaults, but then the situation becomes quickly messy... Either we make a table of all places (computer, computer_configuration=dbauthinfo, code, calculation) TIMES (all possible configurable values) of what is settable where, and which defaults take precedence, or we find a clever global rule that is always valid (e.g. you can always set everything, and lower levels take precedence).

At the moment, the idea is to expose everything at least at the lowest (calculation) level so at least these features are customisable, even if it is more complex to put defaults.
