### ISSUE TITLE
Adapt examples/work/test_pw.py to point to the correct QE path and pseudos

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida_core#945]
This file is outdated and it uses wrong path to the QE plugin (e.g. from aiida.orm.calculation.job.quantumespresso.pw import PwCalculation) and points to the wrong place for the needed psedopotentials.

It is an easy fix. Maybe other scripts should be updated too.

**Comment by sphuber** [comment]
For this particular example there are three potential solutions as I see it

1.  Put `aiida_quantumespresso` import in `try/except` and raise exception when it is not installed
2. Add `aiida_quantumespresso` as a dependency of `aiida_core`
3. Remove or move the examples to `aiida_quantumespresso`

The second option is something we definitely don't want to do I think. The first one would be an option, however, given that it really is a quantum espresso example, I think it really belongs in that repository. But I already have examples there that are almost identical and even provide a nice command line interface.

Conclusion: shall I just remove the obsolete QE specific examples?

**Comment by sphuber** [comment]
@giovannipizzi just added you to assignees to get your opinion on the above discussion.

**Comment by giovannipizzi** [comment]
I agree: 2 is not viable, I would avoid 1, and I would go for 3. If there are better examples, let's just remove it. If it's simpler/still makes sense to keep, let's move it. Thanks!

**Comment by sphuber** [comment]
Even the non-QE examples in `examples/work` are extremely outdated and most of them don't run. I am tempted to remove all of them and replace them by some simple new and concise ones.

**Comment by szoupanos** [comment]
Thanks for the fast reaction on this - Actually I did not manage to see it early enough to reply in time.

Why did you remove also test_pw.py?
Do we have a simple submission script that shows how to submit calculations?
In case someone is not interested to use workchains/new workflows?

**Comment by szoupanos** [comment]
Moreover, the submit(JobCalc, **inputs)) that was mentioned at the end of the test_pw and the JobCalc.get_inputs_template() is somewhere documented?
Is this the new approach for submitting calculations?

**Comment by sphuber** [comment]
I could whip up an example based on the `TemplatereplacerCalculation` job calculation class, but for the actual `run` call to work we need to pass a `Code`. For the travis-tests we use the `torquessh-doubler` dummy code, but I don't think we can easily use this for this particular example. I think it will only make it more confusing. However, without a proper code, I am not sure how I can complete an example that actually "runs" like the dummy workchains for example. Any ideas?

**Comment by giovannipizzi** [comment]
I think that if there is no example with the new way of submitting calcs, an example should be added (but this cannot be on QE, he test_pw is now in the aiida-qe plugin).
It should be doable (at least to show that it works) also with the TemplatereplacerCalculation (in the tests, a code is created for it).

**Comment by szoupanos** [comment]
Thanks for the info. I found the test_pw at the QE repository. 
Let's have a small chat during the next AiiDA meeting about the new calculation submission (why it is needed, what does it serve, how it is used etc).
