### ISSUE TITLE
Remove async from aiida.work.run

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida_core#946]
`aiida.work.run` still provides the method `async` which will return the `MultithreadedEngine` from `plum`. However, I thought that we deprecated `async` or at the very least, it should not be used anymore. Should we simply remove it, or should we put a deprecation warning on it that we will remove it in the next release? Mind you, the warning will only be in `develop` and not in `0.10.0`.

**Comment by sphuber** [comment]
Should we include this before the release of `0.11.0`? It is definitely not going to be supported in the next version.

**Comment by giovannipizzi** [comment]
If anyway we do not support it/it creates problems, I would already include this in 0.11.0

**Comment by sphuber** [comment]
Do you want to keep it as is currently and just stick a deprecation warning in the function definition? And then we remove it in `1.0`, or you want to remove it now?

**Comment by sphuber** [comment]
Fixed in #1040
