### ISSUE TITLE
debugging: more helpful error message for db-tests in case of import error

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#953]
## Description

The following type of error message is common when running aiida tests in case of import errors (missing dependencies for instance).

```
File ".../aiida-core/aiida/backends/testbase.py", line 165, in run_aiida_db_tests
    test_suite.addTest(test_loader.loadTestsFromName(modulename))
  File ".../lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'persistence'
```

The error message could easily be very helpful if only the name of the module was output too

## Possible solution

The AttributeError could be caught in `run_aiida_db_tests` in `aiida/backends/testase.py` and the more helpful message could be output containing the `modulename`.

**Comment by sphuber** [comment]
Fixed in #968
