### ISSUE TITLE
Node deletion script is out of date

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#984]
The "how to delete nodes" recipe in the documentation is out of date, since the ``parents__in`` doesn't seem to work. Also, it only seems to take into consideration the first layer of children.

Note: This will be obsolete if #923 is implemented.

Attaching my modified deletion script (very much untested):
[delete_nodes.py.txt](https://github.com/aiidateam/aiida_core/files/1549841/delete_nodes.py.txt)

**Comment by broeder-j** [comment]
Thanks for sharing!

**Comment by sphuber** [comment]
This was removed in PR #1083 because the `verdi node delete` command was added that effectively implements the script from the cookbook
