### ISSUE TITLE
verdi export file format specification

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida_core#988]
Since we are currently planning to use .aiida files on Materials Cloud as the primary source for the provenance information, I believe we should provide at least a rudimentary specification of the .aiida file format.

I've searched in the documentation but was unable to find a format specification.
I think it is fine to start with something short - a basic outline of the format - and one can refer to the [existing documentation of the database schema](http://aiida-core.readthedocs.io/en/latest/developer_guide/database_schema.html#).
Some hints on how versioning of the db schema is handled would also be very welcome.

**Comment by sphuber** [comment]
As far as I know, it is not a custom AiiDA format, but rather just an extension choice. Depending on the options used in `verdi export create` it will actually either be a `.tar.gz` or `.zip` archive file. Untarring or unzipping respectively, will simply unpack the file into a directory `nodes` and two files `data.json` and `metadata.json`.

Now of course, if this isn't documented, it probably should and we should maybe also ask ourselves if it is useful to "mask" the real extension with the faux `.aiida` extension

**Comment by ltalirz** [comment]
@sphuber Thanks for the clarification.

If you point me to the code / documents / ... that I should look at, I'm happy to make a first draft in a pull request.

As I said, one helpful piece of information would also be how to find out which "version" of the format one is looking at (I guess currently it is only the db schema that is versioned?)

**Comment by sphuber** [comment]
No the export format is also versioned, separately from the database versioning, and is stored in the `export_version` key of the `metadata.json` file. The import functionality will verify this version number and complain if it differs from the export version of the source code. If this is the case, we provide a cli tool `verdi export migrate` that will automatically upgrade the export file to the new version. It will only ever do this in single steps. For example, the current version is `0.3`. If you have an archive with version `0.1`, calling `verdi export migrate` will transform it to version `0.2`. Calling it a second time will update it to the current `0.3` version. Currently, there is no command that will show you the version of an existing archive, but another issue already exists (#584 ) to provide a `verdi export` command that will display some information about the contents of an archive. Displaying the export version would be a good candidate.

Regarding the documentation, I have not yet looked in the documentation on where the best location would be to put this.

**Comment by ltalirz** [comment]
@sphuber I would propose the developer documentation, at the same level as the [documentation of the db schema](http://aiida-core.readthedocs.io/en/latest/developer_guide/database_schema.html#)

**Comment by sphuber** [comment]
But the export functionality should also be very useful to regular users and then it also important to know that there is a format version and how to use the command line tools, no?

**Comment by ltalirz** [comment]
ideally, regular users should not have to worry about the format specification.
I agree that the usage of `verdi export migrate` needs to be mentioned in the user documentation (and it [is](http://aiida-core.readthedocs.io/en/latest/installation/updating.html?highlight=verdi%20export%20migrate))

**Comment by giovannipizzi** [comment]
@ltalirz you mean this? http://aiida-core.readthedocs.io/en/latest/import_export/main.html#file-format

**Comment by sphuber** [comment]
Ah excellent, that already describes everything we need. But yes, you are correct, the example json's do not correspond to the latest version 0.3 and will have to be updated

**Comment by ltalirz** [comment]
Thanks! I was searching for "verdi export" and "verdi export format" and it was not showing up in the search results, nor being linked to from where I was looking.
I'll change that.

**Comment by sphuber** [comment]
Fixed in #994
