### ISSUE TITLE
workflows: run can not be called on FunctionProcess with inputs given in **kwargs

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida_core#989]
The `work.process.TestFunctionProcess.test_kwargs` test function asserts that

```
run(work.FunctionProcess.build(wf_with_kwargs), **inputs)
```

should work. 

The new `runner._object_factory` however only allows that on arguments that pass `work.utils.is_workfunction`.

@muhrin 
The question is should a FunctionProcess be considered a workfunction (by `work.utils.is_workfunction` and / or by `runner._object_factory`)?
Or should the test be updated to not make this assertion anymore?

**Comment by sphuber** [comment]
Fixed in PR #990
